### ISSUE TITLE
Severe corruption/artifacting with opengl + gpu-next

### ISSUE THREAD

**Issue by awused** [mpv-player/mpv#11499]
### Important Information
mpv --version:
mpv 0.35.1 Copyright © 2000-2023 mpv/MPlayer/mplayer2 projects
 built on UNKNOWN
FFmpeg library versions:
   libavutil       57.28.100
   libavcodec      59.37.100
   libavformat     59.27.100
   libswscale      6.7.100
   libavfilter     8.44.100
   libswresample   4.7.100
FFmpeg version: 5.1.2

- Fedora 37
- Installed from the Fedora official repos
- Hadn't tried gpu-next before, so can't say when it started
- Window manager is i3 (version 4.22 (2023-01-02)), reproduces with and without a compositor
- Nvidia proprietary drivers (525.89.02-1.fc37), this is on a 4090 in case that's relevant

### Reproduction steps

`mpv --no-config --vo=gpu-next --gpu-api=opengl`

opengl works fine without gpu-next, and gpu-next works fine with vulkan.

### Expected behavior
Normal playback.

### Actual behavior
Severe artifacting and corruption, even for the gui overlay. Does not persist when the videos are paused. https://i.imgur.com/iUeEieh.png https://i.imgur.com/MFPkgSl.png

### Log file

https://0x0.st/HoeZ.log

### Sample files

Seems to reproduce on every video file I've tried regardless of codecs.

**Comment by haasn** [comment]
Can't reproduce this locally. @philipl ?

**Comment by philipl** [comment]
Yep, reproduces as stated. I'm sure it's nvidia specific.

**Comment by philipl** [comment]
![image](https://user-images.githubusercontent.com/512286/228011478-d89dc97f-4335-457f-81d7-b7ca6fbe0846.png)

**Comment by philipl** [comment]
Compare with:
![image](https://user-images.githubusercontent.com/512286/228011571-e586b8a1-012c-4bef-857b-ed75429795d9.png)

**Comment by awused** [comment]
It might be related, but I tried gpu-next with vulkan (and gpu-context x11vk) for a bit and ran into frequent hangs. Playback seems fine as long as I don't touch my mouse, but interacting with other windows or resizing mpv seems to result in hangs where even `mpv -v -v` gives me nothing and I have to kill it. Video playback never recovers but audio playback does. No compositor for these tests.

`mpv --no-config --vo=gpu-next --gpu-api=vulkan --gpu-context=x11vk --vulkan-queue-count=8` seems to reproduce it more often. I had vulkan-queue-count=4 in my config and after experimentation, higher queue counts seem to lead to more frequent hangs. Just rapidly maximizing and minimizing the window should trigger it.

**Comment by haasn** [comment]
Is it possible for you to somehow compile/test the libplacebo demo programs to see if they also exhibit similar issues?

**Comment by philipl** [comment]
Yup, reproduces there too. Here is colors.
![image](https://user-images.githubusercontent.com/512286/228322636-6fc9d709-43eb-40f6-8510-e2b515b8c183.png)

**Comment by awused** [comment]
For what it's worth, `--no-config --vo=gpu-next --gpu-api=opengl` seems to be the worst-case scenario. If I run my full opengl config with `--vo=gpu-next` I still get glitchy playback, but the artifacts aren't nearly as omnipresent. At first I believed it was just a corrupted or poorly encoded file.

**Comment by monarc99** [comment]
@awused 
can you try different cscale values?

input.conf:

ctrl+d cycle-values cscale bilinear spline36 lanczos ewa_lanczos ewa_lanczossharp mitchell oversample

i have similar artefacts only with bilinear and oversample as cscale value. But that could be a different bug.

**Comment by awused** [comment]
I get the same artifacts with every one of those options except for ewa_lanczos and ewa_lanczossharp where they are significantly reduced but still present. Maybe if there are two different sources of artifacts those two options remove one of them. With `--no-config --vo=gpu-next --gpu-api=opengl --cscale=ewa_lanczos`:

![04-01_11-59-06](https://user-images.githubusercontent.com/1551320/229309458-7feaa774-f6dd-425f-a65b-e7c19549e5ba.png)

**Comment by Jertzukka** [comment]
I believe I just got this same issue. For me it seems like that large resolution files, created from the same source file by scaling with ffmpeg do not artifact. The smaller resolution of the file, the more it artifacts. Also, if you increase the display resolution of an artifacting video, the image improves but there's always artifacting at the very bottom. Pausing the video clears any artifacting immediately. vo=gpu has no such issues and everything works fine.

As previously mentioned gpu-api=vulkan doesn't seem to artifact.

According to my pacman.log, I upgraded mpv from 35.1-4 to 35.1-6 around a month ago, but I only now noticed the issue so I suspect it is quite recent. I upgraded the following nvidia drivers just few days ago, so that would be more likely the culprit.
[ALPM] upgraded linux61-nvidia (530.41.03-10 -> 530.41.03-13)

<details>
 <summary>System details</summary>
 Package versions:
- mpv 0.35.1-dirty Copyright © 2000-2023 mpv/MPlayer/mplayer2 projects
 built on Fri Apr 21 07:11:25 2023
FFmpeg library versions:
   libavutil       58.2.100
   libavcodec      60.3.100
   libavformat     60.3.100
   libswscale      7.1.100
   libavfilter     9.3.100
   libswresample   4.10.100
FFmpeg version: n6.0
- Operating System: Manjaro Linux 
KDE Plasma Version: 5.27.5
KDE Frameworks Version: 5.106.0
Qt Version: 5.15.9
Kernel Version: 5.15.114-2-MANJARO (64-bit)
Graphics Platform: X11
Graphics Processor: NVIDIA GeForce GTX 1060 6GB/PCIe/SSE2
- Manjaro stable repo
- Nvidia Driver 530.41.03
</details>



Screen recording of the artifacting.
400x400 video artifacting:
https://0x0.st/HcLl.mp4
180x180 video, increasing the display size makes it better, making it smaller makes artifacting worse:
https://0x0.st/HcLU.mp4
640x640 video, no artifacting. (Ignore different colormatrix value, happens even with bt709.
https://0x0.st/HcL0.mp4

### Log file

https://0x0.st/HcLg.log

### Sample files

400x400 video which does artifact with vo=gpu-next.
https://0x0.st/HcLE.mp4

**Comment by haasn** [comment]
Now testing on an RTX 3050, still can't reproduce this.

**Comment by Traneptora** [comment]
I can reproduce this on my RTX 3050. 
![image](https://github.com/mpv-player/mpv/assets/1342577/59d36bf3-0c57-4500-ad35-8eaccd8b2125)
[mpv-sucks.log](https://github.com/mpv-player/mpv/files/14284994/mpv-sucks.log)

**Comment by guidocella** [comment]
I no longer get artifacts on the 550 driver, can anyone else still reproduce them?

**Comment by Traneptora** [comment]
I can reproduce this on 550. `mpv --no-config av://lavfi:testsrc --vo=gpu-next --gpu-api=opengl --log-file=mpv-sucks.log`
![image](https://github.com/mpv-player/mpv/assets/1342577/30261f6d-9b3a-4631-a6ee-b4d603a8c835)
https://0x0.st/HRJl.log

**Comment by philipl** [comment]
It's not as bad. But I can still see it too.
![Screenshot from 2024-03-01 09-19-14](https://github.com/mpv-player/mpv/assets/512286/47f9f6f7-0935-4557-be6d-75f1d03dd36c)

**Comment by philipl** [comment]
I checked again, and it's even worse right now. Even with `--no-config --vo=gpu-next`, it not only is artifacting badly but it's also not rendering smoothly. It looks like a 60fps video is playing at 20 or 30 fps. If I switch to vulkan, it's fine.

**Comment by llyyr** [comment]
We found out this only happens on x11. The corruption isn't present on wayland

**Comment by monarc99** [comment]
yes, only X11 and when I activate user shader, they are also gone.

**Comment by kasper93** [comment]
> Not sure if this is related or an isolated incident, but I'm seeing similar artifacts on Windows + Vulkan + gpu-next + profile=high-quality, on Intel UHD 620.

Not Linux
Not X11
Not NVIDIA
Not OpenGL

Safe to say it is completely unrelated to this ticket.

> Also if I drag the window while playing a video, I get repeating/out of order frames.

For this we have https://github.com/mpv-player/mpv/issues/13811

**Comment by llyyr** [comment]
> > Also if I drag the window while playing a video, I get repeating/out of order frames.
> 
> For this we have #13811

It might not be related to vulkan, since similar issue was also reported here with egl https://github.com/mpv-player/mpv/pull/14511#issuecomment-2275486520 (3rd bullet point)

**Comment by guidocella** [comment]
> I'm seeing similar artifacts on Windows + Vulkan + `gpu-next` + `profile=high-quality`, on Intel UHD 620

I assume this is caused specifically by ewa `--cscale`?

**Comment by guidocella** [comment]
https://github.com/mpv-player/mpv/issues/13645 also occurs with ewa cscale, though it's different. So polar cscales have issues beyond Nvidia.

**Comment by llyyr** [comment]
@na-na-hi does `--vulkan-async-compute=no` or `--vulkan-async-transfer=no`

Also does this diff for libplacebo change anything?

```diff
diff --git a/src/renderer.c b/src/renderer.c
index 7622523d9530..ceb305eb0a97 100644
--- a/src/renderer.c
+++ b/src/renderer.c
@@ -734,6 +734,7 @@ static void dispatch_sampler(struct pass_state *pass, pl_shader sh,
 
     bool ok;
     if (info.config->polar) {
+        fparams.no_compute = true;
         // Polar samplers are always a single function call
         ok = pl_shader_sample_polar(sh, src, &fparams);
     } else if (info.dir_sep[0] && info.dir_sep[1]) {
```

**Comment by llyyr** [comment]
> Yes. No artifacts with the patch.

Then I suppose the question is whether vo_gpu uses compute shaders or gather shaders. If it uses compute shaders then why does it not glitch, and if it uses gather shaders then what needs to be updated in libplacebo logic so that it refuses to use compute shaders on this hardware.

**Comment by kasper93** [comment]
> Not sure if this is related or an isolated incident, but I'm seeing similar artifacts on Windows + Vulkan + `gpu-next` + `profile=high-quality`, on Intel UHD 620. The artifacts only show up when EWA scalers are active. Also if I drag the window while playing a video, I get repeat

For the record I can also see image corruption on Linux 6.10 with displayvk. It is lest severe, but definitely there. Also out-of-order frame display can also be reproduced.

**Comment by kasper93** [comment]
> Not sure if this is related or an isolated incident, but I'm seeing similar artifacts on Windows + Vulkan + `gpu-next` + `profile=high-quality`, on Intel UHD 620. The artifacts only show up when EWA scalers are active. Also if I drag the window while playing a video, I get repeating/out of order frames.
> 
> `vo=gpu` with any `gpu-api` or `gpu-next` with d3d11/opengl work fine.
> 
> ![winvulkan](https://github.com/user-attachments/assets/c82922c7-8d97-4668-a73a-fc7d747148fb)

@na-na-hi: I've looked into this. I happen to have the same GPU. The issue is fixed when not using compute shared for polar scaling or by preventing the merge into next pass, basically adding FBO in-between. This however on good working GPU, is ~20% performance penalty (10 vs 12 ms), so we cannot do that. We could have some list of affected devices, but so far I know only about this UHD620 on Windows. Those iGPUs are too slow for polar scaling anyway, so probably not used in practice, so no reports. Not sure what to do here, there seem to be no easy workaround that does not affect performance.

``` diff
diff --git a/src/renderer.c b/src/renderer.c
index e4295a51..0c950561 100644
--- a/src/renderer.c
+++ b/src/renderer.c
@@ -1865,6 +1865,8 @@ static bool pass_read_image(struct pass_state *pass)
             st->img.w = st->img.rect.x1 = src.new_w;
             st->img.h = st->img.rect.y1 = src.new_h;
             src.scale = 1.0;
+
+            img_tex(pass, &st->img);
         }

         pass_hook(pass, &st->img, plane_scaled_hook_stages[st->type]);
@@ -2069,6 +2071,8 @@ static bool pass_scale_main(struct pass_state *pass)
     img->h    = src.new_h;
     img->rect = new_rect;

+    img_tex(pass, img);
+
     pass_hook(pass, img, PL_HOOK_POST_KERNEL);

     if (use_sigmoid)
```

**Comment by mahkoh** [comment]
Everything in this issue looks like synchronization or layout issues to me. I'm surprised this hasn't been suggested before. Out-of-order frames are of course a classic and the corrupt tiles can also be a result of missing synchronization. See the image in https://gitlab.freedesktop.org/mesa/mesa/-/merge_requests/40382 for an example of corruption caused by two operations writing to an image concurrently. (The race mentioned in there is likely not related to this issue.)

I assume you've already run the pure-vulkan workloads with validation enabled?

**Comment by kasper93** [comment]
> Everything in this issue looks like synchronization or layout issues to me. I'm surprised this hasn't been suggested before.

It has not been suggested, because this is quite obvious. This was first thing I tried, but no matter how hard I synchronize things, it's not working. I'm afk, will continue later. Though the root cause is clear.

> I assume you've already run the pure-vulkan workloads with validation enabled?

Yes, of course. Also note that OP of this issue is about opengl on NVIDIA, while the comment I was responding to is Vulkan on Intel. The symptoms are similar, but since even colors demo app fail on opengl, not sure if we hit exact same thing. I don't think colors use compute, but hey. At least the other issue #13645 seems more similar, but then again reports says that it works on Vulkan.

Anyway, I will continue when I have time.

**Comment by mahkoh** [comment]
>It has not been suggested, because this is quite obvious.

🤷 I've also seen GPU driver bugs before that caused similar issues. What makes it look to me like this is an application issue is that it happens across multiple operating systems and multiple GPU vendors. And since you specifically called out your GPU in the previous post it sounded to me like you were still considering device-specific issues.

**Comment by kasper93** [comment]
> > It has not been suggested, because this is quite obvious.
> 
> 🤷 I've also seen GPU driver bugs before that caused similar issues. What makes it look to me like this is an application issue is that it happens across multiple operating systems and multiple GPU vendors. And since you specifically called out your GPU in the previous post it sounded to me like you were still considering device-specific issues.

That's correct. I don't rule out device specific issue, because at least for Vulkan, I don't know other system/gpu that is affected. OpenGL is different backed and this looks like application issue indeed. I'm focusing on Vulkan first.

**Comment by kasper93** [comment]
> Not sure if this is related or an isolated incident, but I'm seeing similar artifacts on Windows + Vulkan + `gpu-next` + `profile=high-quality`, on Intel UHD 620. The artifacts only show up when EWA scalers are active. Also if I drag the window while playing a video, I get repeating/out of order frames.
> 
> `vo=gpu` with any `gpu-api` or `gpu-next` with d3d11/opengl work fine.
> 
> ![winvulkan](https://github.com/user-attachments/assets/c82922c7-8d97-4668-a73a-fc7d747148fb)

Should be fixed/worked around by https://code.videolan.org/videolan/libplacebo/-/merge_requests/835

**Comment by mahkoh** [comment]
I've only taken a quick look at the libplacebo code but queue family transfers require two barriers: the first one on the old queue and the second one on the new queue with the exact same parameters and the two operations must be synchronized.

If keeping the image always in general layout fixes the issue, then you might be missing one of the two barriers and the driver only performs the layout transition in the barrier that you're not executing.

**Comment by kasper93** [comment]
> I've only taken a quick look at the libplacebo code but queue family transfers require two barriers: the first one on the old queue and the second one on the new queue with the exact same parameters and the two operations must be synchronized.
> 
> If keeping the image always in general layout fixes the issue, then you might be missing one of the two barriers and the driver only performs the layout transition in the barrier that you're not executing.

There is single queue (graphics+compute+transfer all share QF=0), images are VK_SHARING_MODE_EXCLUSIVE. There is no QF transfer, only pure layout transition. For me it looks like driver bug, also there is always top-left rect of the image valid. You can even see that in the above screenshot. For me it looks like a driver bug, and I really tried a lot of things to workaround it. Ideas are welcome, I can test anything, if you would like.

Additionally there are no VVL synchronization issues reported. 

Also note this Vulkan issue affect single GPU on single platform. I was not able to reproduce those issue on anything else.

(this issue was hijacked for Vulkan, while OP was reporting opengl issue.)

**Comment by Traneptora** [comment]
I can still reproduce this with mpv 71ebd08406547339a5decd9c61ab3e83739e96b3 and libplacebo d4624cbfb37fdef337a7da5794b66202671a89cd on Linux with nvidia and X11 (only X11, not Wayland).

<img width="344" height="287" alt="Image" src="https://github.com/user-attachments/assets/5f300b75-45fa-49de-8803-ab8b4b07b4d9" />

Log File:
[mpv-sucks.log](https://github.com/user-attachments/files/28672823/mpv-sucks.log)

**Comment by kasper93** [comment]
> I can still reproduce this with mpv [71ebd08](https://github.com/mpv-player/mpv/commit/71ebd08406547339a5decd9c61ab3e83739e96b3) and libplacebo d4624cbfb37fdef337a7da5794b66202671a89cd on Linux with nvidia and X11 (only X11, not Wayland).
> <img alt="Image" width="344" height="287" src="https://private-user-images.githubusercontent.com/1342577/604001104-5f300b75-45fa-49de-8803-ab8b4b07b4d9.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3ODEyNzY3NzMsIm5iZiI6MTc4MTI3NjQ3MywicGF0aCI6Ii8xMzQyNTc3LzYwNDAwMTEwNC01ZjMwMGI3NS00NWZhLTQ5ZGUtODgwMy1hYjhiNGIwN2I0ZDkucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI2MDYxMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNjA2MTJUMTUwMTEzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MGNmOThiNTg4ODU5ZjAzMzdlYmMzYTZjYmFiZjY1MTIwZTdjZDFjOGZmZWI1N2UwMTcwNDMyODgwOWE5NWY5ZCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmcmVzcG9uc2UtY29udGVudC10eXBlPWltYWdlJTJGcG5nIn0.vuSdKjY9Spgr56kHTOUxfl5q6YCHVj2qUa5QN5nciVw">
> 
> Log File: [mpv-sucks.log](https://github.com/user-attachments/files/28672823/mpv-sucks.log)

This should be fixed by https://code.videolan.org/videolan/libplacebo/-/merge_requests/863, see also https://forums.developer.nvidia.com/t/373037
