### ISSUE TITLE
Reading into cache leads to 100% cpu usage on 1 core (glibc bug)

### ISSUE THREAD

**Issue by mauricioquintela** [mpv-player/mpv#12076]
### Important Information

Provide following Information:
- mpv 65a95a7 / libplacebo 5613f832
- Arch Linux running 6.1.39-3-lts
- master git repo
- picom 10.2-1.1
- mesa 23.1.5-2
- screenshot of large cpu usage vs normal 
![image](https://github.com/mpv-player/mpv/assets/39190784/4890e022-533b-4f5a-af44-222d25934d79)
![image](https://github.com/mpv-player/mpv/assets/39190784/ac9c850b-4c45-48ec-a511-d6064aeea212)

### Reproduction steps

Open any file with cache=yes set. While cache state is "reading", cpu usage will have 1 core pegged to 100%. As soon at it reaches "eof", cpu usage returns to normal. Reproducible with --no-config, as long as --cache=yes is also set. 

### Expected behavior
As before, expect that 1 core isn't pegged at full usage and max turbo. 

### Actual behavior
One cpu core stays at 100% and full turbo while reading. Read speed also slows to a crawl (~250KB/s) after a while.

### Log file

[cache.txt](https://github.com/mpv-player/mpv/files/12265022/cache.txt)
[no-cache.txt](https://github.com/mpv-player/mpv/files/12265029/no-cache.txt)
[slow.txt](https://github.com/mpv-player/mpv/files/12265035/slow.txt)

### Sample files

Test video was local copy of https://www.youtube.com/watch?v=sIB9NmUwPG8 simply due to filesize: large enough that caching is not "instant", small enough that buffering does not take hit default cache limit and slowdown/cache limit mentioned.

**Comment by christoph-heinrich** [comment]
I have the same problem, must have been caused by a recent update on Arch.
I've already tried bisecting it to no avail (even commits from the beginning of July show that problem).
htop shows that the thread name is `mpv/demux`.
Some testing has revealed that the CPU usage is dependent on how much is already cached. At the beginning the CPU usage is low, but it doesn't have to load much to fully load that one core. It's easier to observe that with YouTube videos then with local files, because they take longer to load.

**Comment by mauricioquintela** [comment]
Precisely, i've started setting the governor to powersave when watching remote videos via yt-dlp/plex-mpv-shim to prevent fans from aggressively spinning up. 

Worst part is that the caching speed depends on how much is already cached (like it is getting bottlenecked), leading to very slow reads when the file gets big.

**Comment by monarc99** [comment]
One core of CPU has high IO-wait operation at 100%

Kernel 6.4.4, 6.4.5 and 6.1.39 LTS are affected:
The known issue and report:

[SOLVED] Linux 6.4.4 introduces high IO-Wait CPU operations on one ... / Kernel & Hardware / Arch Linux Forums 2
FS#79177 : Kernel 6.4.4 has regression with high iowait on one core
It is fixed in Kernel 6.4.6

Try a newer kernel.

**Comment by mauricioquintela** [comment]
> One core of CPU has high IO-wait operation at 100%
> 
> Kernel 6.4.4, 6.4.5 and 6.1.39 LTS are affected: The known issue and report:
> 
> [SOLVED] Linux 6.4.4 introduces high IO-Wait CPU operations on one ... / Kernel & Hardware / Arch Linux Forums 2 FS#79177 : Kernel 6.4.4 has regression with high iowait on one core It is fixed in Kernel 6.4.6
> 
> Try a newer kernel.

Hm, interesting. I've been running LTS for a while due to an [issue with AMD memory clocks on mainline](https://gitlab.freedesktop.org/drm/amd/-/issues/2657). I'll give mainline a test and edit this reply.

**Comment by mauricioquintela** [comment]
Rebooted into 6.4.8 for both mainline and zen. It is (very slightly) better, but CPU usage still rises as file is loaded, with slow reads and cpu at 100% still present:
![image](https://github.com/mpv-player/mpv/assets/39190784/2948a45f-8329-4c23-920e-58c9ce358eb2)

**Comment by KenJean** [comment]
Just to provide additional information for those who are debugging:

I am on Arch Linux, running zen-Kernel 6.4.8 and the problem persists.


⇒ KJ

**Comment by mauricioquintela** [comment]
From my limited testing, issue is present in both 6.3.38-LTS and 6.3.37-LTS as well.

**Comment by christoph-heinrich** [comment]
https://bugs.archlinux.org/task/79300

**Comment by lbatalha** [comment]
Started noticing same issue today when twitch streams started stuttering after about 10 minutes.
As the backbuffer cache increases so does CPU.

Updated to 6.4.8 mainline, mpv 0.36.0, libplacebo 5.264.1 (also tested 0.35.1 with 5.229.2) and issue persists, about ~13% cpu usage at 1m backbuffer, ~40% at 5 minutes.
If I record file to disk and play that, ofc, no issue since cache is disabled for local files and CPU sits at ~4% for the same content.

**Comment by mauricioquintela** [comment]
Rolled system back to 2023/08/02 (prior to glibc 2.38) via Arch Linux Archive. 
Both the high cpu usage and the very slow reads return to normal, with remote read speeds going from ~100KB/s back to saturating my connection at 15MB/s and the cpu usage staying very low (hwdec=vaapi is used).

**Comment by tomudo** [comment]
I have the same problem as others mentioned. I tested on Flatpak with no 100% CPU issue.

**Comment by jouven** [comment]
Same story. I'm on EOS (arch based), culprit seems to be glibc 2.38 (2.38-2 included), rolled the system packages before glibc 2.38 and the issue doesn't happen (mpv version is still the latest 0.36.0).

**Comment by DonRichie** [comment]
Same here, mpv reads around 2-3 minutes into the cache fast, then filling up the cache becomes very slow. Video is then unplayable.
Filliing cache stays slow when I seek through the video. Behavior is independent from hardware acceleration settings.

I updated my os today and then the problem appeared.

os: arch linux
Linux 6.5.0-rc4-1-mainline 

mpv 0.36.0 Copyright © 2000-2023 mpv/MPlayer/mplayer2 projects
 built on Sun Jul 23 05:49:29 2023
libplacebo version: v5.264.1
FFmpeg version: N-111698-g9549712056
FFmpeg library versions:
   libavutil       58.2.100 (runtime 58.14.100)
   libavcodec      60.3.100 (runtime 60.22.100)
   libavformat     60.3.100 (runtime 60.10.100)
   libswscale      7.1.100 (runtime 7.3.100)
   libavfilter     9.3.100 (runtime 9.10.100)
   libswresample   4.10.100 (runtime 4.11.100)

**Comment by llyyr** [comment]
It's a glibc bug, there's nothing mpv or ffmpeg can do about it. https://sourceware.org/pipermail/libc-alpha/2023-August/150653.html

Wait for them to fix it or downgrade

**Comment by ionenwks** [comment]
Generally I feel distros shouldn't be so eager to jump on the latest libc outside experimental venues, not that unusual that need to backport a major fix or two before unleashing it.

**Comment by Liupold** [comment]
For the record, setting `cache = no` in mpv config will not cause the high cpu usage  (which is evident from the issues initial comment).  If you have a fast storage and stable internet connection this might be a temporary fix.

**Comment by KenJean** [comment]
Can confirm that `cache = no` (or `--cache=no` on the command line) works as a temporary fix. Having to wait a tick occasionally (*very* occasionally, in my case) for the feed to catch up is infinitely better than having to restart **mpv** every few minutes.

Many thanks, Liupold !!

⇒ KJ

**Comment by christoph-heinrich** [comment]
Reducing cache size also works. I currently use:
```properties
demuxer-max-bytes=50MiB
demuxer-max-back-bytes=25MiB
```

**Comment by KenJean** [comment]
Even better !! You people are awesome !


⇒ KJ

**Comment by narpfel** [comment]
Another workaround: Using a different allocator, e. g. [`jemalloc`](https://jemalloc.net/), via `LD_PRELOAD`, as described here: https://github.com/jemalloc/jemalloc/wiki/Getting-Started

```console
$ LD_PRELOAD=`jemalloc-config --libdir`/libjemalloc.so.`jemalloc-config --revision` mpv ...
```

I also tried a patched `ffmpeg` that removes the usage of the regressed `memalign` feature, that also works:
<details>
<summary>patch</summary>

Note that on Arch `ffmpeg` also needs effadce6c756247ea8bae32dc13bb3e6f464f0eb to compile (see https://bugs.archlinux.org/task/79281).

```patch
diff --git a/libavutil/mem.c b/libavutil/mem.c
index 36b8940..4793376 100644
--- a/libavutil/mem.c
+++ b/libavutil/mem.c
@@ -100,45 +100,7 @@ void *av_malloc(size_t size)
     if (size > atomic_load_explicit(&max_alloc_size, memory_order_relaxed))
         return NULL;
 
-#if HAVE_POSIX_MEMALIGN
-    if (size) //OS X on SDK 10.6 has a broken posix_memalign implementation
-    if (posix_memalign(&ptr, ALIGN, size))
-        ptr = NULL;
-#elif HAVE_ALIGNED_MALLOC
-    ptr = _aligned_malloc(size, ALIGN);
-#elif HAVE_MEMALIGN
-#ifndef __DJGPP__
-    ptr = memalign(ALIGN, size);
-#else
-    ptr = memalign(size, ALIGN);
-#endif
-    /* Why 64?
-     * Indeed, we should align it:
-     *   on  4 for 386
-     *   on 16 for 486
-     *   on 32 for 586, PPro - K6-III
-     *   on 64 for K7 (maybe for P3 too).
-     * Because L1 and L2 caches are aligned on those values.
-     * But I don't want to code such logic here!
-     */
-    /* Why 32?
-     * For AVX ASM. SSE / NEON needs only 16.
-     * Why not larger? Because I did not see a difference in benchmarks ...
-     */
-    /* benchmarks with P3
-     * memalign(64) + 1          3071, 3051, 3032
-     * memalign(64) + 2          3051, 3032, 3041
-     * memalign(64) + 4          2911, 2896, 2915
-     * memalign(64) + 8          2545, 2554, 2550
-     * memalign(64) + 16         2543, 2572, 2563
-     * memalign(64) + 32         2546, 2545, 2571
-     * memalign(64) + 64         2570, 2533, 2558
-     *
-     * BTW, malloc seems to do 8-byte alignment by default here.
-     */
-#else
     ptr = malloc(size);
-#endif
     if(!ptr && !size) {
         size = 1;
         ptr= av_malloc(1);
@@ -156,11 +118,7 @@ void *av_realloc(void *ptr, size_t size)
     if (size > atomic_load_explicit(&max_alloc_size, memory_order_relaxed))
         return NULL;
 
-#if HAVE_ALIGNED_MALLOC
-    ret = _aligned_realloc(ptr, size + !size, ALIGN);
-#else
     ret = realloc(ptr, size + !size);
-#endif
 #if CONFIG_MEMORY_POISONING
     if (ret && !ptr)
         memset(ret, FF_MEMORY_POISON, size);
@@ -235,11 +193,7 @@ int av_reallocp_array(void *ptr, size_t nmemb, size_t size)
 
 void av_free(void *ptr)
 {
-#if HAVE_ALIGNED_MALLOC
-    _aligned_free(ptr);
-#else
     free(ptr);
-#endif
 }
 
 void av_freep(void *arg)
```

</details>

**Comment by Archer2011** [comment]
I can confirm that 
`LD_PRELOAD=`jemalloc-config --libdir`/libjemalloc.so.`jemalloc-config --revision` mpv ...` works

**Comment by mauricioquintela** [comment]
Can confirm, running
```
$ LD_PRELOAD=`jemalloc-config --libdir`/libjemalloc.so.`jemalloc-config --revision` mpv ...
```
fixes issue under current (2.38-2) version of glibc. CPU usage returns to normal, and cache fills saturating disk/network speed.

**Comment by Liupold** [comment]
> Another workaround: Using a different allocator, e. g. [`jemalloc`](https://jemalloc.net/), via `LD_PRELOAD`, as described here: https://github.com/jemalloc/jemalloc/wiki/Getting-Started
> 
> ```
> $ LD_PRELOAD=`jemalloc-config --libdir`/libjemalloc.so.`jemalloc-config --revision` mpv ...
> ```
> 
> I also tried a patched `ffmpeg` that removes the usage of the regressed `memalign` feature, that also works:
> 
> patch
> Note that on Arch `ffmpeg` also needs effadce6c756247ea8bae32dc13bb3e6f464f0eb to compile (see https://bugs.archlinux.org/task/79281).
> 
> ```diff
> diff --git a/libavutil/mem.c b/libavutil/mem.c
> index 36b8940..4793376 100644
> --- a/libavutil/mem.c
> +++ b/libavutil/mem.c
> @@ -100,45 +100,7 @@ void *av_malloc(size_t size)
>      if (size > atomic_load_explicit(&max_alloc_size, memory_order_relaxed))
>          return NULL;
>  
> -#if HAVE_POSIX_MEMALIGN
> -    if (size) //OS X on SDK 10.6 has a broken posix_memalign implementation
> -    if (posix_memalign(&ptr, ALIGN, size))
> -        ptr = NULL;
> -#elif HAVE_ALIGNED_MALLOC
> -    ptr = _aligned_malloc(size, ALIGN);
> -#elif HAVE_MEMALIGN
> -#ifndef __DJGPP__
> -    ptr = memalign(ALIGN, size);
> -#else
> -    ptr = memalign(size, ALIGN);
> -#endif
> -    /* Why 64?
> -     * Indeed, we should align it:
> -     *   on  4 for 386
> -     *   on 16 for 486
> -     *   on 32 for 586, PPro - K6-III
> -     *   on 64 for K7 (maybe for P3 too).
> -     * Because L1 and L2 caches are aligned on those values.
> -     * But I don't want to code such logic here!
> -     */
> -    /* Why 32?
> -     * For AVX ASM. SSE / NEON needs only 16.
> -     * Why not larger? Because I did not see a difference in benchmarks ...
> -     */
> -    /* benchmarks with P3
> -     * memalign(64) + 1          3071, 3051, 3032
> -     * memalign(64) + 2          3051, 3032, 3041
> -     * memalign(64) + 4          2911, 2896, 2915
> -     * memalign(64) + 8          2545, 2554, 2550
> -     * memalign(64) + 16         2543, 2572, 2563
> -     * memalign(64) + 32         2546, 2545, 2571
> -     * memalign(64) + 64         2570, 2533, 2558
> -     *
> -     * BTW, malloc seems to do 8-byte alignment by default here.
> -     */
> -#else
>      ptr = malloc(size);
> -#endif
>      if(!ptr && !size) {
>          size = 1;
>          ptr= av_malloc(1);
> @@ -156,11 +118,7 @@ void *av_realloc(void *ptr, size_t size)
>      if (size > atomic_load_explicit(&max_alloc_size, memory_order_relaxed))
>          return NULL;
>  
> -#if HAVE_ALIGNED_MALLOC
> -    ret = _aligned_realloc(ptr, size + !size, ALIGN);
> -#else
>      ret = realloc(ptr, size + !size);
> -#endif
>  #if CONFIG_MEMORY_POISONING
>      if (ret && !ptr)
>          memset(ret, FF_MEMORY_POISON, size);
> @@ -235,11 +193,7 @@ int av_reallocp_array(void *ptr, size_t nmemb, size_t size)
>  
>  void av_free(void *ptr)
>  {
> -#if HAVE_ALIGNED_MALLOC
> -    _aligned_free(ptr);
> -#else
>      free(ptr);
> -#endif
>  }
>  
>  void av_freep(void *arg)
> ```

There is also a [`jemalloc.sh`](https://github.com/jemalloc/jemalloc/blob/dev/bin/jemalloc.sh.in), which ships with the package, and seems works exactly the same way as the cmd mentioned above.

So we can run `jemalloc.sh mpv ...` after installing jemalloc. This works for me and seems neat. Thanks a lot @narpfel .

**Comment by xry111** [comment]
> Generally I feel distros shouldn't be so eager to jump on the latest libc outside experimental venues, not that unusual that need to backport a notable fix or two before unleashing it.
> 
> **Edit:** especially when you consider that you cannot downgrade it if you've built packages against it without rebuilding them against an older libc, as they will typically break (there's forward compatibility but not the other way around)

As a @lfs-book maintainer and the first person reporting the issue to Glibc: if we didn't jump into the latest Glibc we'd not notice the issue at all.  There must be a "first one" to hit the mine.

The problem is people should really try to diagnose the issue more carefully and report it to a proper location, instead of just directly reporting to "a random downstream package blown up by the mine".

**Comment by thesamesam** [comment]
> > Generally I feel distros shouldn't be so eager to jump on the latest libc outside experimental venues, not that unusual that need to backport a notable fix or two before unleashing it.
> > **Edit:** especially when you consider that you cannot downgrade it if you've built packages against it without rebuilding them against an older libc, as they will typically break (there's forward compatibility but not the other way around)
> 
> As a @lfs-book maintainer and the first person reporting the issue to Glibc: if we didn't jump into the latest Glibc we'd not notice the issue at all. There must be a "first one" to hit the mine.
> 

There's a difference between exposing the issue to all of your users vs having it in some testing area first, though. This isn't the first time that Arch updated day-0 and exposed that to all users, and then a bunch of pressure was directed at glibc maintainers to fix a bug very quickly.

**Comment by Toolybird** [comment]
> There's a difference between exposing the issue to all of your users vs having it in some testing area first

Fair point. But I will say in Arch's defence it does have some fairly thorough testing procedures in place (including a dedicated testing area). But in this case obviously the testing was not thorough enough :(

**Comment by xry111** [comment]
> > There's a difference between exposing the issue to all of your users vs having it in some testing area first
> 
> Fair point. But I will say in Arch's defence it does have some fairly thorough testing procedures in place (including a dedicated testing area). But in this case obviously the testing was not thorough enough :(

Actually we found the performance issue by running Mesa test suite.  Our ffmpeg testers have not noticed any issue yet...

**Comment by mauricioquintela** [comment]
For those that haven't been following the [upstream discussion](https://bugs.archlinux.org/task/79300), a patched [[1](https://inbox.sourceware.org/libc-alpha/877cq4yrpg.fsf@oldenburg.str.redhat.com/)] [[2](https://inbox.sourceware.org/libc-alpha/87pm3uajev.fsf@oldenburg.str.redhat.com/)] and pre-compiled version of glibc ([glibc-2.38-2.2-x86_64.pkg.tar.zst](https://drive.google.com/file/d/1a-xidrDmkF7Aa1LGbOtG1Uabp6xHPngK/view?usp=sharing)) and lib32-glibc ([lib32-glibc-2.38-2.2-x86_64.pkg.tar.zst](https://drive.google.com/file/d/1RkFGJvHn4HP41N5iZG1qp5wIp_isXDRO/view?usp=sharing))  is now available. This fixes the glibc bug with memalign, restoring old performance and caching behaviour.

**Comment by ShiroYasha139** [comment]
How do I use the jemalloc workaround in Freetube?

**Comment by nick-s-b** [comment]
> For those that haven't been following the [upstream discussion](https://bugs.archlinux.org/task/79300), a patched [[1](https://inbox.sourceware.org/libc-alpha/877cq4yrpg.fsf@oldenburg.str.redhat.com/)] [[2](https://inbox.sourceware.org/libc-alpha/87pm3uajev.fsf@oldenburg.str.redhat.com/)] and pre-compiled version of glibc ([glibc-2.38-2.3-x86_64.pkg.tar.zst](https://drive.google.com/file/d/1Pg5WXVzVL5P2Ws-z_ubVQ3npekNerBT7/view?usp=sharing)) and lib32-glibc ([lib32-glibc-2.38-2.3-x86_64.pkg.tar.zst](https://drive.google.com/file/d/1lZGwjDqRSwNzFORcf_NFmMxQFu3riZHK/view?usp=sharing)) is now available. This fixes the glibc bug with memalign, restoring old performance and caching behaviour.

Anything that depends on OpenSSL will throw all kinds of errors with this version of glibs. I reverted back.

**Comment by ionenwks** [comment]
> Anything that depends on OpenSSL will throw all kinds of errors with this version of glibc. I reverted back.

Regardless of if it works or not, I'd wait for your distro to patch glibc in their official repo than use random packages from elsewhere for something major like glibc. Meanwhile safer to use e.g. the jemalloc workaround.

May still take a bit given also normally don't dump patches on glibc trivially either.

**Comment by ionenwks** [comment]
Haven't tested much but for me these two glibc patches did solve this mpv issue and haven't seen side effects so far (openssl-3 works fwics), I'm on Gentoo though (where glibc-2.38 is currently still a opt-in either way).

My guess was that it may be an issue with that prebuilt package or how it was used rather than anything introduced by the patches and thus my suggestion to let the distro handle it.

**Comment by mauricioquintela** [comment]
Glibc 2.38-3 has now been pushed to Arch repos, officially fixing this issue. With that, I'm marking this as closed. Glad this could help people identify the issue.
