### ISSUE TITLE
ao=pipewire no sound

### ISSUE THREAD

**Issue by sommio** [mpv-player/mpv#13947]
### Important Information

- mpv-git v0.38.0-63-gb364e4a65c (via [AUR](https://aur.archlinux.org/packages/mpv-git))
- Arch Linux
- Mutter 46.0 
- Pipewire 1.0.5 

### Reproduction steps

1. mpv --no-config --ao=pipewire sample.mp4
2. mpv --no-config --ao=jack sample.mp4

`ao=jack` works fine, although on my system it is implemented via `pipewire-jack`.

### Log file

[pipewire.log](https://github.com/mpv-player/mpv/files/15047929/pipewire.log)
[pipewire-jack.log](https://github.com/mpv-player/mpv/files/15047931/pipewire-jack.log)

### Sample files

[Sample](https://github.com/mpv-player/mpv/assets/64189793/d2002a4b-9c6c-4280-b9fc-dfb84f1bcc30)

**Comment by ruihe774** [comment]
Is this issue introduced in v0.38? Did v0.37 work fine? Could you plz try reverting #13774 and/or #13774 to check if your issue is introduced by one of these changes on ao_pipewire in v0.38?

**Comment by sommio** [comment]
`git reset --hard 2cbb13db9edae33d8fe1b078835fd387e69946d3`  https://github.com/mpv-player/mpv/commit/2cbb13db9edae33d8fe1b078835fd387e69946d3
Errors can still be reproduced

[pipewire-mpv-git-0.37.0_737_g2cbb13db9e-1.log](https://github.com/mpv-player/mpv/files/15048052/pipewire-mpv-git-0.37.0_737_g2cbb13db9e-1.log)
[pipewire-jack-mpv-git-0.37.0_737_g2cbb13db9e-1.log](https://github.com/mpv-player/mpv/files/15048053/pipewire-jack-mpv-git-0.37.0_737_g2cbb13db9e-1.log)

**Comment by ruihe774** [comment]
fwd @t-8ch

**Comment by sommio** [comment]
I removed it at the suggestion of an archlinuxcn user:
`~/.config/pulse`
`~/.local/state/wireplumber`.
After rebooting it worked fine, thanks to him.
[mpv-0.38-pipewire-fine.log](https://github.com/mpv-player/mpv/files/15048216/mpv-0.38-pipewire-fine.log)

**Comment by t-8ch** [comment]
I suspect the "global" Volume was muted.
This is a different control from per-channel volumes which are exposed by pavucontrol and mpv.

**Comment by sommio** [comment]
In addition to `mpv` I used `netease-cloud-music-gtk4` and it worked fine.
Incidentally I usually control the volume with `wpctl set-volume @DEFAULT_AUDIO_SINK@ 0.x`.
At least now the problem is solved...not sure of the root cause though.

**Comment by ruihe774** [comment]
> netease-cloud-music-gtk4

`netease-cloud-music-gtk4` uses pulseaudio API, not pipewire API.

**Comment by amfern** [comment]
@sommio  solution worked for me too.

**Comment by neitsab** [comment]
Yep, can confirm renaming those folders **and** rebooting did the trick.

It had been two days I found myself all of a sudden without sound in mpv. The morning it was working, I suspended to RAM, and the afternoon no sound. All other applications had sound, and mpv output sound again when used with `--ao=pulse`. Somewhat standard Arch GNOME installation here. Rebooting hadn't changed anything.

Annoying, but easy fix. Thanks @sommio

**Comment by SandroHc** [comment]
For anyone looking for a quick fix that doesn't require a system reboot, the following is what works for me:
```shell
rm -rf ~/.local/state/wireplumber/stream-properties
systemctl --user restart wireplumber
```

---

I tracked the issue down to this line on `~/.local/state/wireplumber/stream-properties`. Resetting `channelVolumes` and `mute` restores sound. Still not sure what causes it; seems to be related to my Bluetooth headset.
```
Output/Audio:media.role:Movie={"channelMap":["FL", "FR"], "channelVolumes":[0.000000, 0.000000], "mute":true, "volume":1.000000}
```
