### ISSUE TITLE
mpv on Mac isn't playing this right, compared against mplayerX

### ISSUE THREAD

**Issue by CaledoniaProject** [mpv-player/mpv#1528]
I've uploaded the AVI here:
https://www.dropbox.com/s/s02dc72zmr51tgb/1.avi?dl=0

You can try to open it with both mpv and mplayerX and the difference is discernible. 

I took a screenshot:
![screen](https://cloud.githubusercontent.com/assets/1357701/5922128/2b4b38ea-a684-11e4-8a25-0d711c535d8c.png)

**Comment by CaledoniaProject** [comment]
FYI dropbox seems to render it correctly, no black outs

**Comment by wm4** [comment]
I'm unable to guess what your problem is.

**Comment by wm4** [comment]
As discussed on IRC, this seems to be an issue with the bundle, and doesn't happen when starting from command line.

**Comment by CaledoniaProject** [comment]
Still happens if I run mpv 1.avi
P.S I installed mpv-0.7.2 with homebrew

**Comment by pigoz** [comment]
Use mpv from git `brew install --HEAD mpv`. It looks like this bug is already fixed.

**Comment by wm4** [comment]
Also, 0.7.3 is the most recent release. Not sure if that fixes it.

**Comment by pigoz** [comment]
I tested and it's broken on 0.7.3

**Comment by CaledoniaProject** [comment]
Still broken:

%> mpv --version
mpv git-c63ca50 (C) 2000-2015 mpv/MPlayer/mplayer2 projects
 built on 2015-01-29T13:10:58
ffmpeg library versions:
   libavutil       54.15.100
   libavcodec      56.13.100
   libavformat     56.15.102
   libswscale      3.1.101
   libavfilter     5.2.103
   libswresample   1.1.100

**Comment by Rick74crx** [comment]
Just tried in OSX 10.10.2 with the latest master version and the file in the opening post, and it's definitely still not working, both with the bundle or by playing the file from terminal.

**Comment by pigoz** [comment]
Strange, now I can reproduce with both CLI and bundle. I think this might be linked to the ffmpeg version..

**Comment by pigoz** [comment]
Actually the sample video contains an alpha channel (who knows why...) and mpv is trying by default to blend the video to the black window background respecting the alpha. See http://mpv.io/manual/master/#video-output-drivers-alpha

`mpv --vo=opengl:alpha=no` and `mpv --vo=opengl:alpha=yes` seem to work (instead of the default: blend).

**Comment by wm4** [comment]
Wow, awesome.

**Comment by wm4** [comment]
Seems like the decoder outputs garbage on the alpha channel, which causes this.

**Comment by wm4** [comment]
Well, changed the default (commit a33b461), which "fixes" this, and in exchange will show garbage pixels instead of "transparency" with png files.

**Comment by wm4** [comment]
Reverted the fix. You now need FFmpeg git master to display this file correctly with vo_opengl default settings.
