### ISSUE TITLE
White lines during playback

### ISSUE THREAD

**Issue by karjonas** [mpv-player/mpv#16259]
### mpv Information

```bash
mpv v0.40.0-dirty Copyright © 2000-2025 mpv/MPlayer/mplayer2 projects
 built on Apr  4 2025 07:28:54
libplacebo version: v7.349.0
FFmpeg version: n7.1
FFmpeg library versions:
   libavcodec      61.19.100
   libavdevice     61.3.100
   libavfilter     10.4.100
   libavformat     61.7.100
   libavutil       59.39.100
   libswresample   5.3.100
   libswscale      8.3.100
```

### Other Information

```text
- Linux version: Arch Linux
- Kernel Version: Linux station 6.14.2-arch1-1 #1 SMP PREEMPT_DYNAMIC Thu, 10 Apr 2025 18:43:59 +0000 x86_64 GNU/Linux
- GPU Model: VGA compatible controller [0300]: Advanced Micro Devices, Inc. [AMD/ATI] Navi 32 [Radeon RX 7700 XT / 7800 XT] [1002:747e] (rev c8)
- Mesa/GPU Driver Version: Mesa 25.0.3-arch1.1
- Window Manager and Version: sway version 1.10.1
- Source of mpv: Official Arch Linux package
- Latest known working version: 0.39.0
- Issue started after the following happened: Upgrading to 0.40.0
```

### Reproduction Steps

When playing any video (I've only tried h264 and 265 formats) white horizontal lines appears from time to time. 

### Expected Behavior

No white horizontal lines.

### Actual Behavior

https://github.com/user-attachments/assets/ae7b1a79-38a8-4ccd-b218-959c26ed2f13

White horizontal lines. When using a screen-recorder on the machine the issue didn't happen so I had to record using a phone.

### Log File

[output.txt](https://github.com/user-attachments/files/19794541/output.txt)

### I carefully read all instruction and confirm that I did the following:

- [x] I tested with the latest mpv version to validate that the issue is not already fixed.
- [x] I provided all required information including system and mpv version.
- [x] I produced the log file with the exact same set of files, parameters, and conditions used in "Reproduction Steps", with the addition of `--log-file=output.txt`.
- [x] I produced the log file while the behaviors described in "Actual Behavior" were actively observed.
- [x] I attached the full, untruncated log file.
- [x] I attached the backtrace in the case of a crash.

**Comment by karjonas** [comment]
> Does it happen when the mpv window isn't fullscreen?

No.

> Can you start sway with export WLR_SCENE_DISABLE_DIRECT_SCANOUT=1 in your env and see if it happens still?

It happens still.

**Comment by llyyr** [comment]
> It happens still.

Are you absolutely certain? If the issue doesn't happen if you're screen recording or the window isn't fullscreen, then it points to an issue with direct scanout. But if it still happens with no direct scanout, then it's hard to say what the cause could be.

Can you provide `WAYLAND_DEBUG=1 mpv [file]` output when sway is launched with that env variable?

**Comment by llyyr** [comment]
> Do I need to these the other options or is this enough to pin it down?

You can --gpu-api=opengl, if it happens with that too then you report to https://gitlab.freedesktop.org/drm/amd/-/issues/ and if it happens with only the default --gpu-api=vulkan, then you report to mesa.

**Comment by karjonas** [comment]
mesa bug report: https://gitlab.freedesktop.org/mesa/mesa/-/issues/13066

**Comment by llyyr** [comment]
This is fixed in the kernel, will likely be in the next bugfix kernel release https://github.com/torvalds/linux/commit/8724a5380c4390eed81e271d22f34ff06453ded9

**Comment by kasper93** [comment]
We will need confirmation if white line artifacts are the same issue as RDNA4 corruption.

**Comment by kasper93** [comment]
The patch is in [v6.16-rc3](https://github.com/torvalds/linux/releases/tag/v6.16-rc3) if someone wants to test or otherwise wait for stable release.

**Comment by karjonas** [comment]
The issue is still there on my current version:

Linux station 6.16.4-arch1-1 #1 SMP PREEMPT_DYNAMIC Thu, 28 Aug 2025 19:49:53 +0000 x86_64 GNU/Linux

**Comment by kasper93** [comment]
Can you report it upstream? There is nothing we can do about this on mpv side.

**Comment by delet-this** [comment]
@karjonas The patch was for RDNA4, the issue is not yet fixed for RDNA3. Upstream is aware: https://gitlab.freedesktop.org/drm/amd/-/issues/4466

**Comment by brumansniffer** [comment]
Hello, i too experience this now on 6.18.2.arch2-1 with 7900xtx KDE wayland.

Setting `gpu-api=opengl` solves problem in fullscreen. Not sure why is this happening. It was working fine for the past 2 weeks until i upgraded

**Comment by llyyr** [comment]
Most likely radv/amdgpu regression. See if downgrading kernel or Mesa fixes it, then report it to the appropriate place

**Comment by brumansniffer** [comment]
> Most likely radv/amdgpu regression. See if downgrading kernel or Mesa fixes it, then report it to the appropriate place

trying out with lts kernel works - 6.12.63-1-lts. So its a kernel issue? i saw that you cant open up new issues on linux repo on github anymore, so should i just email torvalds directly or something?

**Comment by llyyr** [comment]
> trying out with lts kernel works - 6.12.63-1-lts. So its a kernel issue? i saw that you cant open up new issues on linux repo on github anymore, so should i just email torvalds directly or something?

https://gitlab.freedesktop.org/drm/amd/-/issues/

Try to find the exact version where it broke if possible, AMD people probably also will ask you to bisect the exact commit

**Comment by delet-this** [comment]
Unless I'm missing something it's the same issue linked few comments above, so any new information should probably go there
