### ISSUE TITLE
Input stuck while playing video with `--gpu-context=waylandvk` and `video-sync=display-resample`

### ISSUE THREAD

**Issue by DreamAlone666** [mpv-player/mpv#16689]
### mpv Information

```bash
mpv v0.40.0-dirty Copyright © 2000-2025 mpv/MPlayer/mplayer2 projects
 built on Jul 29 2025 22:42:28
libplacebo version: v7.351.0
FFmpeg version: n7.1.1
FFmpeg library versions:
   libavcodec      61.19.101
   libavdevice     61.3.100
   libavfilter     10.4.100
   libavformat     61.7.100
   libavutil       59.39.100
   libswresample   5.3.100
   libswscale      8.3.100
```

### Other Information

```text
- Linux version: Arch Linux
- Kernel Version: Linux lenovo-g5000-aph8-2023 6.16.1-2-cachyos-lto #1 SMP PREEMPT_DYNAMIC Sat, 16 Aug 2025 07:30:42 +0000 x86_64 GNU/Linux
- GPU Model: 01:00.0 VGA compatible controller [0300]: NVIDIA Corporation AD107M [GeForce RTX 4060 Max-Q / Mobile] [10de:28e0] (rev a1)
- Mesa/GPU Driver Version: nvidia open modules of 580.76.05 driver for the linux-cachyos-lto kernel
- Window Manager and Version: KDE Plasma 6.4.4 (Wayland)
- Source of mpv: cachyos-extra-znver4 repo
- Latest known working version: I've been using 0.40 for a few months with no problems
- Issue started after the following happened: May be some system updates a few days ago
```

### Reproduction Steps

Can be reproduced with `--gpu-context=waylandvk` and `video-sync=display-resample` on my machine.

### Expected Behavior

Can input normally with mouse and keyboard.

### Actual Behavior

While the video is playing, mpv does not respond to input, window resize, and window close events.
But when the video is paused, everything is fine.

Other `gpu-context` like `wayland` and `x11vk` work fine with `display-resample`.

### Log File

[display-resample.txt](https://github.com/user-attachments/files/21821177/display-resample.txt)

[no-display-resample.txt](https://github.com/user-attachments/files/21821179/no-display-resample.txt)

### I carefully read all instruction and confirm that I did the following:

- [x] I tested with the latest mpv version to validate that the issue is not already fixed.
- [x] I provided all required information including system and mpv version.
- [x] I produced the log file with the exact same set of files, parameters, and conditions used in "Reproduction Steps", with the addition of `--log-file=output.txt`.
- [x] I produced the log file while the behaviors described in "Actual Behavior" were actively observed.
- [x] I attached the full, untruncated log file.
- [x] I attached the backtrace in the case of a crash.

**Comment by NotMithical** [comment]
I had the exact same issue a few days ago after updating nvidia-open from 575 to 580 (also on Arch, KDE Plasma 6.4.4 Wayland as well). Solved it by explicitly setting `--wayland-internal-vsync=yes`.

This line from Nvidia's 580 release highlights may be relevant:
> Added support for the fifo-v1 Wayland protocol on Vulkan.

**Comment by Dudemanguy** [comment]
What's probably happening is that we request fifo instead of mailbox in the new driver update since it supports fifo-v1. There's no reason this should block input though so it has to be some weird nvidia bug. `--wayland-internal-vsync=yes` is the right workaround since that forces mailbox like before.

**Comment by captcapslock** [comment]
I had the same issue with mpv ignoring keyboard or mouse input or reacting with delay.

adding wayland-internal-vsync=yes to mpv.conf fixed the issue.

arch linux, kernel 6.16.0-zen2-1-zen, wayland, nvidia 580.76.05

**Comment by mahkoh** [comment]
You need to post WAYLAND_DEBUG output if you want this to get debugged.

**Comment by DreamAlone666** [comment]
> You need to post WAYLAND_DEBUG output if you want this to get debugged.

```sh
WAYLAND_DEBUG=1 mpv h264-1080x1920.mp4 --no-config --autofit-larger=90%x80% --gpu-debug --gpu-context=waylandvk 2> wayland_debug.txt
```

[wayland_debug.txt](https://github.com/user-attachments/files/21849000/wayland_debug.txt)

```sh
WAYLAND_DEBUG=1 mpv h264-1080x1920.mp4 --no-config --autofit-larger=90%x80% --gpu-debug --gpu-context=waylandvk --video-sync=display-resample 2> wayland_debug-display_resample.txt
```

[wayland_debug-display_resample.txt](https://github.com/user-attachments/files/21848945/wayland_debug-display_resample.txt)

```sh
WAYLAND_DEBUG=1 mpv h264-1080x1920.mp4 --no-config --autofit-larger=90%x80% --gpu-debug --gpu-context=waylandvk --video-sync=display-resample --wayland-internal-vsync 2> wayland_debug-display_resample-internal_vsync.txt
```

[wayland_debug-display_resample-internal_vsync.txt](https://github.com/user-attachments/files/21849030/wayland_debug-display_resample-internal_vsync.txt)

---

Above are some command lines and their corresponding stderr output.
Play the same ten-second video, and keep moving the mouse in the osd-bar area.

**Comment by mahkoh** [comment]
I think mpv never calls wl_display_read_events.

I was confused about why the clipboard thread didn't do this by accident but then I realized that it uses a separate wayland connection.

**Comment by ojsl1** [comment]
I have a similar unresponsiveness problem on AMD with all the `video-sync=display-*` options  (+`waylandvk`) also making the player unresponsive (and laggy) when resizing it, where having `wayland-internal-vsync=yes` also fixes them. I recorded a demo (below) of the behavior and the WAYLAND_DEBUG logs, as this being AMD I'm not sure whether it's related/i should create another issue.

https://streamable.com/xaq3we

All inputs like toggling fullscreen etc. similarly become unresponsive when it's still sluggishly redrawing the resize events, plus when the media is paused the frame doesn't update at all compared to when it's playing it periodically still updates.

mpv v0.40.0-dirty, manjaro linux, kernel: 6.15.10, de: kde plasma 6.4.4 wayland

**Comment by na-na-hi** [comment]
Can you check if https://github.com/mpv-player/mpv/pull/16704 fixes the issue?

**Comment by NotMithical** [comment]
> Can you check if [#16704](https://github.com/mpv-player/mpv/pull/16704) fixes the issue?

Yes, this fixes it on my system. Input is now working properly with `--wayland-internal-vsync=no`.

**Comment by DreamAlone666** [comment]
> > Can you check if [#16704](https://github.com/mpv-player/mpv/pull/16704) fixes the issue?
> 
> Yes, this fixes it on my system. Input is now working properly with `--wayland-internal-vsync=no`.

Can confirm on my machine as well, thanks so much!

**Comment by Dudemanguy** [comment]
Fixed by #16704

**Comment by awsms** [comment]
> Fixed by [#16704](https://github.com/mpv-player/mpv/pull/16704)

mh interesting, I'm still having mpv freezing all the time on an NVIDIA dGPU (610.57.04), 0 issues when running on the AMD APU. very easy to reproduce by hovering on the OSD while toggle play/pause.
as noted above, setting `wayland-internal-vsync=yes` fixes the issue on NVIDIA. am I the only one still experiencing this issue?

**Comment by DreamAlone666** [comment]
> > Fixed by [#16704](https://github.com/mpv-player/mpv/pull/16704)
> 
> mh interesting, I'm still having mpv freezing all the time on an NVIDIA dGPU (610.57.04), 0 issues when running on the AMD APU. very easy to reproduce by hovering on the OSD while toggle play/pause. as noted above, setting `wayland-internal-vsync=yes` fixes the issue on NVIDIA. am I the only one still experiencing this issue?

Sorry, can't reproduce with
```sh
mpv --no-config --wayland-internal-vsync=no --gpu-context=waylandvk --video-sync=display-resample 
```
using nvidia open modules of 610.57.04 driver. The fix seems to still be working on my machine.
