### ISSUE TITLE
mpv UI elements are non interactable/frozen when resizing using a window manager like Rectangle or Magnet

### ISSUE THREAD

**Issue by LightningRocks** [mpv-player/mpv#16732]
### mpv Information

```bash
mpv v0.40.0-dev-g09658a7ce Copyright © 2000-2025 mpv/MPlayer/mplayer2 projects
 built on Aug 26 2025 13:56:31
libplacebo version: v7.351.0
FFmpeg version: 7.1.1
FFmpeg library versions:
libavcodec      61.19.101
libavdevice     61.3.100
libavfilter     10.4.100
libavformat     61.7.100
libavutil       59.39.100
libswresample   5.3.100
libswscale      8.3.100
```

### Other Information

```text
- macOS version: macOS 26.0 (25A5349a)
- Source of mpv: Latest build from the mac_vsibility_render branch (I was having this issue with the master branch as well though)
- Latest known working version: Not sure, I am not sure if this has ever been fixed since I started using mpv on macOS
- Issue started after the following happened: Not sure here either

I did not have any issues on Windows, so I'm pretty sure it's a macOS specific issue

```

### Reproduction Steps

Open mpv
Resize mpv by dragging using Magnet/Rectangle or whatever window resize manager you use
UI elements will always be frozen until interacting with the player with a click for example
(Sometimes the UI elements don't also resize properly but I don't know if that's related to this issue)

This issue does not happen if I manually drag to resize mpv

My example is with UOSC enabled but it happens with the default mpv UI as well

### Expected Behavior

mpv UI elements should be working properly regardless of how I resize the window

### Actual Behavior

mpv UI elements are frozen when I force resize the window using a window manager until I force the window to be interacted with again myself

### Log File

[mpv.log](https://github.com/user-attachments/files/21998006/mpv.log)

### Sample Files

https://github.com/user-attachments/assets/02bcba28-6e11-4904-8117-2a6e6be4da7c

### I carefully read all instruction and confirm that I did the following:

- [x] I tested with the latest mpv version to validate that the issue is not already fixed.
- [x] I provided all required information including system and mpv version.
- [x] I produced the log file with the exact same set of files, parameters, and conditions used in "Reproduction Steps", with the addition of `--log-file=output.txt`.
- [x] I produced the log file while the behaviors described in "Actual Behavior" were actively observed.
- [x] I attached the full, untruncated log file.
- [x] I attached the backtrace in the case of a crash.

**Comment by Akemi** [comment]
on a side note, the functionality shown in the video is also a standard macOS functionality. it is also reproducible with it.

first guess, either some resizing event isn't triggered in those cases and/or we need to implement some additional events.

**Comment by Akemi** [comment]
@guidocella i can reproduce this with our menu too. what do you think could be missing in the mac backend that the menu is not interactable anymore after a resize, or what events/property changes/etc could be missing?

[edit]
it might be missing a mouse up event and thinks it's still being dragged. just another guess.

**Comment by guidocella** [comment]
As far as I can see `osdep/mac/input_helper.swift` calls `mp_input_set_mouse_pos()` on mouse move like most other backends so it doesn't seem to be missing something. I suggest trying with `--window-dragging=no` to check if dragging is indeed the cause.

**Comment by Akemi** [comment]
thanks @guidocella for your input. basically the mouse position wasn't reported anymore because the window was never removed from the `moving` state (missing mouse up event).

should be fixed by #16734.

**Comment by LightningRocks** [comment]
Just tested the commit, and it seems to work. Thanks for the quick update Akemi. Hope this and the black frame fix both get pushed soon

Edit: Most of the time it works fine, but sometimes when I right click upon resizing, it does not interact at first at all like with the original problem. It's like there's a slight delay in it and if I click too early it still exhibits the same issue as before

**Comment by Akemi** [comment]
> Edit: Most of the time it works fine, but sometimes when I right click upon resizing, it does not interact at first at all like with the original problem. It's like there's a slight delay in it and if I click too early it still exhibits the same issue as before

could you explain this in a bit more detail, please? i am not sure how to reproduce this.

**Comment by LightningRocks** [comment]
So when opening mpv, if I resize using the snap feature, if I right click too early after snapping with resize, the menu will still not be interactable. If I wait a bit of time like about 1 second and then do it, it will work normally as expected.

I am providing a video to show an example of what I mean. It's not the clearest but I had to click twice when opening it the first time in the video cause I clicked after resizing very quickly. The second time I intentionally was slower and it worked just fine when I did so. If you need any more info on it just let me know

https://drive.google.com/file/d/1xR5EjkEIzm-qUXSwz81W5pdfpAkuPW43/view?usp=sharing

Had to use Google Drive this time cause the file keeps corrupting if I send as mp4 for embed

**Comment by Akemi** [comment]
sry a bit late. i need a google account for this to request access. i would rather not create one. is it possible to share it publicly or using a different hoster?

**Comment by LightningRocks** [comment]
Oh I just noticed this. 

https://files.catbox.moe/a23a3z.mov

Tell me if this works for you @Akemi

**Comment by Akemi** [comment]
yeah that worked, thanks. 

first you said `it does not interact at first at all like with the original problem`, though in the provided video you open mpv 3 times, snap to top and out of those 3 times the menu opens and you can interact with the opened context menu (eg it changes the highlighted item when moving the mouse).

or did you mean the context menu doesn't open with the first right click (when clicked too early) and only a second right click is recognised and opens that context menu?

if it's the latter then it isn't really the same thing as the initial problem. in certain states macOS doesn't register certain user interaction. as an example, when going from/to fullscreen and while animating the spaces transition, mouse presses are not registered. this can be reproduced with safari for example, eg you can't open the context menu with right click while transitioning. this snap feature might fall into this category (the default snap feature does a 0.5sec animation, opposed to what you are using with no animation) and just prevents registering mouse events. though i tested several times now with the standard macOS snap feature and it is not reproducible. 

for now i don't think this is a problem on mpv's end.

**Comment by LightningRocks** [comment]
Yeah I meant the latter case. Sounds like it is a bug on MacOS end then. I will just have to live with it as a minor inconvience I guess. Thank you for explaining it to me

**Comment by Akemi** [comment]
okay, thank you for your patience.

for now this is just an assumption. though you can probably test it easily with `mpv --input-test --force-window --idle` from CLI. all key/mouse events that are recognised are logged on the terminal and the upper left corner of the window. if you try to reproduce the problem and the right click is recognised in the terminal log and/or upper left corner (might nit see it in corner since it is spammed with mouse move events), then it's at least not a mpv or macOS problem.

it would say something like:
```
[input] Key MBTN_RIGHT is bound to:
[input] 1.  'cycle pause' in <builtin>:1 (default)
[input] 2.  'script-binding osc/__keybinding7' in section {input} in <api>:3
```

**Comment by Akemi** [comment]
i merged the fix for the initial problem and closed this issue. though we can still investigate what the problem for the other issue is and if appropriate we might just open a new issue for this.

**Comment by LightningRocks** [comment]
Okay I tried to test the command line from the terminal. When I did manage to get the test to work, it did tell me that gpu-api metal is not supported but it seems to have a missing input period when I right click with the error. It does not  give me anything on Key MBTN_RIGHT

lightning@Mac ~ % /Applications/mpv.app/Contents/MacOS/mpv --input-test --force-window --idle
Option gpu-api: 'metal' isn't supported.
Error parsing option gpu-api (option parameter could not be parsed)
/Users/lightning/.config/mpv/mpv.conf:26: setting option gpu-api='metal' failed.
[uosc] script-opts/uosc.conf:104 unknown key 'ui_scale', ignoring
[input] Key MOUSE_ENTER is bound to:
[input] (nothing)
[input] Key MOUSE_MOVE is bound to:
[input] (nothing)
[input] Key MOUSE_MOVE is bound to:
[input] (nothing)
[input] Key MOUSE_MOVE is bound to:
[input] (nothing)
[input] Key MOUSE_MOVE is bound to:
[input] (nothing)
[input] Key MOUSE_MOVE is bound to:
[input] (nothing)
[input] Key MOUSE_LEAVE is bound to:
[input] (nothing)
[input] Key MOUSE_ENTER is bound to:
[input] (nothing)
[input] Key MOUSE_MOVE is bound to:
[input] (nothing)
[input] Key MOUSE_MOVE is bound to:
[input] (nothing)
[input] Key MOUSE_MOVE is bound to:
[input] (nothing)
[input] Key MOUSE_MOVE is bound to:
[input] (nothing)
[input] Key MOUSE_MOVE is bound to:
[input] (nothing)
[input] Key MOUSE_MOVE is bound to:
[input] (nothing)
[input] Key MOUSE_MOVE is bound to:
[input] (nothing)
[input] Key MOUSE_MOVE is bound to:
[input] (nothing)
[input] Key MOUSE_MOVE is bound to:
[input] (nothing)
[input] Key MOUSE_MOVE is bound to:
[input] (nothing)
[input] Key MOUSE_MOVE is bound to:
[input] (nothing)
[input] Key MOUSE_LEAVE is bound to:
[input] (nothing)
[input] Key MOUSE_ENTER is bound to:
[input] (nothing)
[input] Key MOUSE_MOVE is bound to:
[input] (nothing)
[input] Key MOUSE_MOVE is bound to:
[input] (nothing)
[input] Key MOUSE_MOVE is bound to:
[input] (nothing)
[input] Key MOUSE_MOVE is bound to:
[input] (nothing)
[input] Key MOUSE_MOVE is bound to:
[input] (nothing)
[input] Key MOUSE_MOVE is bound to:
[input] (nothing)
[input] Key MOUSE_MOVE is bound to:
[input] (nothing)
[input] Key MOUSE_MOVE is bound to:
[input] (nothing)
[input] Key MOUSE_MOVE is bound to:
[input] (nothing)
[input] Key MOUSE_MOVE is bound to:
[input] (nothing)
[input] Key MOUSE_MOVE is bound to:
[input] (nothing)
[input] Key MOUSE_MOVE is bound to:
[input] (nothing)
[input] Key MBTN_RIGHT is bound to:
[input] 1.  'cycle pause' in <builtin>:1 (default)
[input] 2.  'script-binding uosc/menu' in /Users/lightning/.config/mpv/input.conf:8
[input] 3.  'script-binding uosc/__keybinding9' in section {mbtn_right} in <api>:1
[input] Key MBTN_RIGHT is bound to:
[input] 1.  'cycle pause' in <builtin>:1 (default)
[input] 2.  'script-binding uosc/menu' in /Users/lightning/.config/mpv/input.conf:8
[input] 3.  'script-binding uosc/__keybinding9' in section {mbtn_right} in <api>:1

**Comment by LightningRocks** [comment]
https://github.com/user-attachments/assets/9c5d3a1b-eeaa-452d-aabd-f6d854eb2e7b

**Comment by LightningRocks** [comment]
I was able to get it to be seen at around 28 seconds

**Comment by Akemi** [comment]
> Okay I tried to test the command line from the terminal. When I did manage to get the test to work, it did tell me that gpu-api metal is not supported but it seems to have a missing input period when I right click with the error. It does not give me anything on Key MBTN_RIGHT

`gpu-api=metal` does not exists, so it is expected, eg it's `vulkan`. the log indicates a right click though, or was that just a second right click?

```
[input] Key MBTN_RIGHT is bound to:
[input] 1. 'cycle pause' in :1 (default)
```

at 28-30s in the video i see at least one right click recognised. still leaning to not being an mpv problem atm, sry.

**Comment by LightningRocks** [comment]
Well 1 was recognized but again that was with a delay. I try right clicking at the 28 second mark and there is nothing recognized by the first click. I click again right afterwards and then it is detected

> gpu-api=metal does not exists, so it is expected, eg it's vulkan. the log indicates a right click though, or was that just a second right click?

I guess I am supposed to just use gpu-api=vulkan then. I am still having this issue even after making that change

**Comment by Akemi** [comment]
> I guess I am supposed to just use gpu-api=vulkan then. I am still having this issue even after making that change

you don't need to set it manually, it will pick the right one. i was just mentioning it since you mentioned the error. the error itself is irrelevant to the problem here.

**Comment by LightningRocks** [comment]
Yeah I am not sure exactly how to make the issue I am having more clear here. It is easy to notice for me in person but I guess with screen recording it is not as easy to notice what I am trying to demonstrate. I can definitely replicate the issue on my end but maybe I need to try with some different settings. It could be UOSC or something in my mpv.conf that could be messing it up if you are not able to replicate. Or a Tahoe issue since it is still in beta

**Comment by Akemi** [comment]
can you reproduce it with the macOS default snap feature instead of the app you are using? maybe it is related to that.

**Comment by LightningRocks** [comment]
Okay yeah you are right. I cannot reproduce this with the native macOS default snap feature when I drag up to the menu. If that's the case, it must be an issue with Magnet. I tried this using Rectangle and I do not have any issues whatsoever
