### ISSUE TITLE
Window resizes slowly on KDE Wayland

### ISSUE THREAD

**Issue by thecaprisun** [mpv-player/mpv#16744]
### mpv Information

```bash
mpv v0.40.0 Copyright © 2000-2025 mpv/MPlayer/mplayer2 projects
 built on Jul 25 2025 09:22:44
libplacebo version: v6.338.2
FFmpeg version: 6.1.2 (runtime 6.1.3)
FFmpeg library versions:
   libavcodec      60.31.102
   libavdevice     60.3.100
   libavfilter     9.12.100
   libavformat     60.16.100
   libavutil       58.29.100
   libswresample   4.12.100
   libswscale      7.5.100
```

### Other Information

```text
- Linux version: NAME="Void"
- Kernel Version: Linux box 6.12.41_1 #1 SMP PREEMPT_DYNAMIC Sat Aug  2 03:38:07 UTC 2025 x86_64 GNU/Linux
- GPU Model:06:00.0 VGA compatible controller [0300]: Advanced Micro Devices, Inc. [AMD/ATI] Cezanne [Radeon Vega Series / Radeon Vega Mobile Series] [1002:1638] (rev c8)
- Mesa/GPU Driver Version: OpenGL version string: 4.6 (Compatibility Profile) Mesa 25.1.3
- Window Manager and Version: KDE Plasma (KWin) (Wayland) version 6.4.4
- Source of mpv: xbps
- Latest known working version: -
- Issue started after the following happened: -
```

### Reproduction Steps

- Be on the versions of the software that my system has
- Open mpv
- Resize the window

### Expected Behavior

The window resizes normally.

### Actual Behavior

The window resizes slowly.
https://github.com/user-attachments/assets/ec7dfaae-3dde-4fe0-98f4-6c6ae00e8eba
I don't really have anything to say past what you can see in the video.
(Same behavior if I'm not playing anything)

### Log File

[output.txt](https://github.com/user-attachments/files/22051661/output.txt)

### Sample Files

Unnecessary, the issue presents with any file or even no files open

### I carefully read all instruction and confirm that I did the following:

- [x] I tested with the latest mpv version to validate that the issue is not already fixed.
- [x] I provided all required information including system and mpv version.
- [x] I produced the log file with the exact same set of files, parameters, and conditions used in "Reproduction Steps", with the addition of `--log-file=output.txt`.
- [x] I produced the log file while the behaviors described in "Actual Behavior" were actively observed.
- [x] I attached the full, untruncated log file.
- [x] I attached the backtrace in the case of a crash.

**Comment by Dudemanguy** [comment]
This should be fixed on master by #16704. Can you double check?

**Comment by sinewavess** [comment]
> This should be fixed on master by #16704. Can you double check?

I currently do not have access to my PC, I'll be able to check in about 3 or 4 days.

**Comment by 0mhu** [comment]
Hi,
I have the same problem with gnome / mutter.
I rebuilt mpv with the latest master branch (commit 05656cdae754b22a1f2022653abf1de8a9e02c97) which contains that change.

However, the issue is not solved for me; Still experiencing the same laggy behavior.

**Comment by llyyr** [comment]
I can't reproduce the problem on mutter, can you provide mpv logs and WAYLAND_DEBUG=1 logs when the issue occurs?

`WAYLAND_DEBUG=1 mpv [video] --log-file=mpvsucks.log 2> wayland_debug.log` will produce two log files, upload both.

**Comment by 0mhu** [comment]
@llyyr , Ok. With playing back a video, it actually works. Haven't tried that. -_-
The issue only occurs when opening mpv without a video file.

Here with `WAYLAND_DEBUG=1 mpv [video] --log-file=mpvsucks.log 2> wayland_debug.log`

[mpvsucks.log](https://github.com/user-attachments/files/22626997/mpvsucks.log)
[wayland_debug.log](https://github.com/user-attachments/files/22626996/wayland_debug.log)

Here with `WAYLAND_DEBUG=1 mpv --player-operation-mode=pseudo-gui --log-file=mpvsucks.log 2> wayland_debug.log`

[mpvsucks.log](https://github.com/user-attachments/files/22627029/mpvsucks.log)
[wayland_debug.log](https://github.com/user-attachments/files/22627028/wayland_debug.log)

Don't know, if that even counts as a bug without using a video..

**Comment by llyyr** [comment]
Is it consistently laggy as in the video in OP or intermittent freezes when resizing? if it's the latter I can actually reproduce it

**Comment by 0mhu** [comment]
It's consistently lagging:
https://www.youtube.com/watch?v=ZNPCZPhjoJI

Same happens when you play back an audio file which obviously does not require any video rendering and only shows the cover image.

Out of interest I reduced my monitor refresh rate from 140 Hz to 60 Hz and then it is even slower. So slow, in fact, that it's absolutely unusable.

**Comment by llyyr** [comment]
I can reproduce this. something goes wrong with keepaspect-window=yes. if you set it to no it doesn't lag without a video anymore, i assume we're implicitly relying something that doesn't happen when there's no video playing

**Comment by Dudemanguy** [comment]
I can sometimes get some very minor lag in KDE in this case but it seems random and not affected by keepaspect at all so I guess it's not quite the same as whatever you guys are seeing in mutter.

**Comment by llyyr** [comment]
I can reproduce across all compositors actually. You just need `mpv --no-config --idle --force-window --keepaspect-window=yes`. Doesn't happen when there's video out

**Comment by o-alquimista** [comment]
> something goes wrong with keepaspect-window=yes. if you set it to no it doesn't lag without a video anymore

I cannot reproduce what you're describing on KDE 6.6.4 (Wayland). I'm running `mpv --no-config --idle --force-window --keepaspect-window=no`, but resizing the window is just as laggy as with `--keepaspect-window=yes`.

These are my system details:

- Operating System: Fedora Linux 43
- KDE Plasma Version: 6.6.4
- KDE Frameworks Version: 6.25.0
- Qt Version: 6.10.3
- Kernel Version: 6.19.12-200.fc43.x86_64 (64-bit)
- Graphics Platform: Wayland
- Processors: 8 × Intel® Core™ i3-10100 CPU @ 3.60GHz
- Memory: 16 GiB of RAM (15.5 GiB usable)
- Graphics Processor: AMD Radeon RX 6600

```
mpv v0.40.0 Copyright © 2000-2025 mpv/MPlayer/mplayer2 projects
libplacebo version: v7.351.0
FFmpeg version: 7.1.1 (runtime 7.1.2)
FFmpeg library versions:
   libavcodec      61.19.101
   libavdevice     61.3.100
   libavfilter     10.4.100
   libavformat     61.7.100
   libavutil       59.39.100
   libswresample   5.3.100
   libswscale      8.3.100
```

EDIT: oh, I need to build the latest mpv and see if it's any different.

**Comment by o-alquimista** [comment]
I cannot reproduce the problem at all on the latest mpv (`v0.41.0-536-g174bcec30`). Maybe it was fixed recently?

<details><summary>System and mpv info</summary>
<p>

- Operating System: Fedora Linux 43
- KDE Plasma Version: 6.6.4
- KDE Frameworks Version: 6.25.0
- Qt Version: 6.10.3
- Kernel Version: 6.19.12-200.fc43.x86_64 (64-bit)
- Graphics Platform: Wayland
- Processors: 8 × Intel® Core™ i3-10100 CPU @ 3.60GHz
- Memory: 16 GiB of RAM (15.5 GiB usable)
- Graphics Processor: AMD Radeon RX 6600

```
mpv v0.41.0-536-g174bcec30 Copyright © 2000-2026 mpv/MPlayer/mplayer2 projects
 built on Apr 21 2026 22:07:07
libplacebo version: v7.362.0 (v7.360.0-16-g409c9a82)
FFmpeg version: N-124075-gd1d873c003
FFmpeg library versions:
   libavcodec      62.30.100
   libavdevice     62.4.100
   libavfilter     11.17.100
   libavformat     62.13.102
   libavutil       60.30.100
   libswresample   6.4.100
   libswscale      9.7.100
```

</p>
</details>
