### ISSUE TITLE
Random black flicker with hwdec=vaapi

### ISSUE THREAD

**Issue by sjug** [mpv-player/mpv#1765]
I am running a brand new arch system and with mpv 0.8.3 I'm seeing random black video flicker (whole frame goes black) as the video plays. The flickers are not consistenent at the timestamps but they continue to occur. I have recently updated from mplayer-vaapi as it is now orphaned in arch, and I never had any of these issues prior.
The files are on the local disk, and I've tried adjusting the cache-size, but it made no difference.
While this file has subtitles, even files without them also flicker.
I've also tried every vo (opengl, opengl-hq, and vaapi) and the flicker still occurs regardless.

Please advise.

Here is mpv -v with software decoding
```
[cplayer] Command line: 'mpv' '-v' 'fam.mkv'
[cplayer] mpv 0.8.3 (C) 2000-2015 mpv/MPlayer/mplayer2 projects
[cplayer]  built on 2015-03-17T07:32:24
[cplayer] ffmpeg library versions:
[cplayer]    libavutil       54.20.100
[cplayer]    libavcodec      56.26.100
[cplayer]    libavformat     56.25.101
[cplayer]    libswscale      3.1.101
[cplayer]    libavfilter     5.11.102
[cplayer]    libswresample   1.1.100
[cplayer] 
[cplayer] Configuration: ./waf configure --prefix=/usr --confdir=/etc/mpv --enable-joystick --enable-zsh-comp --enable-libmpv-shared --enable-cdda
[cplayer] config.h:
[cplayer] 
[cplayer] #define DEFAULT_DVD_DEVICE "/dev/sr0"
[cplayer] #define DEFAULT_CDROM_DEVICE "/dev/sr0"
[cplayer] #define HAVE_CPLAYER 1
[cplayer] #define HAVE_LIBMPV_SHARED 1
[cplayer] #define HAVE_LIBMPV_STATIC 0
[cplayer] #define HAVE_STATIC_BUILD 0
[cplayer] #define HAVE_BUILD_DATE 1
[cplayer] #define HAVE_OPTIMIZE 1
[cplayer] #define HAVE_DEBUG_BUILD 1
[cplayer] #define HAVE_PDF_BUILD 0
[cplayer] #define HAVE_LIBDL 1
[cplayer] #define HAVE_DLOPEN 1
[cplayer] #define HAVE_VF_DLOPEN_FILTERS 0
[cplayer] #define HAVE_ZSH_COMP 1
[cplayer] #define HAVE_ASM 1
[cplayer] #define HAVE_TEST 0
[cplayer] #define HAVE_CLANG_DATABASE 0
[cplayer] #define HAVE_NOEXECSTACK 0
[cplayer] #define HAVE_LIBM 1
[cplayer] #define HAVE_MINGW 0
[cplayer] #define HAVE_POSIX 1
[cplayer] #define HAVE_POSIX_OR_MINGW 1
[cplayer] #define HAVE_WIN32_INTERNAL_PTHREADS 0
[cplayer] #define HAVE_PTHREADS 1
[cplayer] #define HAVE_STDATOMIC 1
[cplayer] #define HAVE_ATOMIC_BUILTINS 0
[cplayer] #define HAVE_SYNC_BUILTINS 0
[cplayer] #define HAVE_ATOMICS 1
[cplayer] #define HAVE_LIBRT 1
[cplayer] #define HAVE_ICONV 1
[cplayer] #define HAVE_DOS_PATHS 0
[cplayer] #define HAVE_WAIO 0
[cplayer] #define HAVE_TERMIOS_H 1
[cplayer] #define HAVE_SYS_TERMIOS_H 0
[cplayer] #define HAVE_TERMIOS 1
[cplayer] #define HAVE_SHM 1
[cplayer] #define HAVE_NANOSLEEP 1
[cplayer] #define HAVE_POSIX_SPAWN 1
[cplayer] #define HAVE_GLOB 1
[cplayer] #define HAVE_GLOB_WIN32_REPLACEMENT 0
[cplayer] #define HAVE_GLIBC_THREAD_NAME 1
[cplayer] #define HAVE_OSX_THREAD_NAME 0
[cplayer] #define HAVE_BSD_THREAD_NAME 0
[cplayer] #define HAVE_NETBSD_THREAD_NAME 0
[cplayer] #define HAVE_BSD_FSTATFS 0
[cplayer] #define HAVE_LINUX_FSTATFS 1
[cplayer] #define HAVE_LIBGUESS 1
[cplayer] #define HAVE_LIBSMBCLIENT 1
[cplayer] #define HAVE_LUA 1
[cplayer] #define HAVE_LIBASS 1
[cplayer] #define HAVE_LIBASS_OSD 1
[cplayer] #define HAVE_DUMMY_OSD 0
[cplayer] #define HAVE_ZLIB 1
[cplayer] #define HAVE_ENCODING 1
[cplayer] #define HAVE_JOYSTICK 1
[cplayer] #define HAVE_LIRC 1
[cplayer] #define HAVE_LIBBLURAY 1
[cplayer] #define HAVE_DVDREAD 1
[cplayer] #define HAVE_DVDNAV 1
[cplayer] #define HAVE_CDDA 1
[cplayer] #define HAVE_ENCA 1
[cplayer] #define HAVE_MPG123 1
[cplayer] #define HAVE_LADSPA 1
[cplayer] #define HAVE_LIBBS2B 0
[cplayer] #define HAVE_LCMS2 1
[cplayer] #define HAVE_VAPOURSYNTH_CORE 0
[cplayer] #define HAVE_VAPOURSYNTH 0
[cplayer] #define HAVE_VAPOURSYNTH_LAZY 0
[cplayer] #define HAVE_SDL2 0
[cplayer] #define HAVE_SDL1 0
[cplayer] #define HAVE_OSS_AUDIO_4FRONT 0
[cplayer] #define HAVE_OSS_AUDIO_NATIVE 1
[cplayer] #define HAVE_OSS_AUDIO_SUNAUDIO 0
[cplayer] #define HAVE_OSS_AUDIO 1
[cplayer] #define HAVE_RSOUND 0
[cplayer] #define HAVE_SNDIO 0
[cplayer] #define HAVE_PULSE 1
[cplayer] #define HAVE_JACK 1
[cplayer] #define HAVE_OPENAL 0
[cplayer] #define HAVE_ALSA 1
[cplayer] #define HAVE_COREAUDIO 0
[cplayer] #define HAVE_DSOUND 0
[cplayer] #define HAVE_WASAPI 0
[cplayer] #define HAVE_COCOA 0
[cplayer] #define HAVE_GDI 0
[cplayer] #define HAVE_WINMM 0
[cplayer] #define HAVE_OLE 0
[cplayer] #define HAVE_UUID 1
[cplayer] #define HAVE_WAYLAND 1
[cplayer] #define HAVE_X11 1
[cplayer] #define HAVE_XSS 0
[cplayer] #define HAVE_XEXT 1
[cplayer] #define HAVE_XV 1
[cplayer] #define HAVE_XINERAMA 1
[cplayer] #define HAVE_XRANDR 1
[cplayer] #define HAVE_GL_COCOA 0
[cplayer] #define HAVE_GL_X11 1
[cplayer] #define HAVE_EGL_X11 0
[cplayer] #define HAVE_GL_WAYLAND 1
[cplayer] #define HAVE_GL_WIN32 0
[cplayer] #define HAVE_GL 1
[cplayer] #define HAVE_VDPAU 1
[cplayer] #define HAVE_VDPAU_GL_X11 1
[cplayer] #define HAVE_VAAPI 1
[cplayer] #define HAVE_VAAPI_VPP 1
[cplayer] #define HAVE_VAAPI_GLX 1
[cplayer] #define HAVE_CACA 0
[cplayer] #define HAVE_JPEG 1
[cplayer] #define HAVE_DIRECT3D 0
[cplayer] #define HAVE_LIBAV 1
[cplayer] #define HAVE_LIBSWRESAMPLE 1
[cplayer] #define HAVE_LIBAVRESAMPLE 0
[cplayer] #define HAVE_RESAMPLER 1
[cplayer] #define HAVE_LIBAVFILTER 1
[cplayer] #define HAVE_LIBAVDEVICE 1
[cplayer] #define HAVE_AVCODEC_CHROMA_POS_API 1
[cplayer] #define HAVE_AVCOL_SPC_BT2020 1
[cplayer] #define HAVE_AVCODEC_VDPAU_ALLOC_CONTEXT 1
[cplayer] #define HAVE_AVCODEC_METADATA_UPDATE_SIDE_DATA 1
[cplayer] #define HAVE_AVFORMAT_METADATA_UPDATE_FLAG 1
[cplayer] #define HAVE_AVCODEC_REPLAYGAIN_SIDE_DATA 1
[cplayer] #define HAVE_AV_DISPLAYMATRIX 1
[cplayer] #define HAVE_AVFRAME_METADATA 1
[cplayer] #define HAVE_AVFRAME_SKIP_SAMPLES 1
[cplayer] #define HAVE_LIBAVCODEC_VAAPI_H 1
[cplayer] #define HAVE_VAAPI_HWACCEL 1
[cplayer] #define HAVE_VIDEODECODEACCELERATION_VDADECODER_H 0
[cplayer] #define HAVE_VIDEO_DECODE_ACCELERATION_VDA_DECODER_H 0
[cplayer] #define HAVE_VDA_HWACCEL 0
[cplayer] #define HAVE_VDA_GL 0
[cplayer] #define HAVE_VDPAU_HWACCEL 1
[cplayer] #define HAVE_DXVA2_HWACCEL 0
[cplayer] #define HAVE_TV 1
[cplayer] #define HAVE_SYS_VIDEOIO_H 0
[cplayer] #define HAVE_VIDEODEV 1
[cplayer] #define HAVE_TV_V4L2 1
[cplayer] #define HAVE_LIBV4L2 1
[cplayer] #define HAVE_PVR 1
[cplayer] #define HAVE_AUDIO_INPUT 1
[cplayer] #define HAVE_DVBIN 1
[cplayer] #define HAVE_WIN32_EXECUTABLE 0
[cplayer] #define HAVE_COCOA_APPLICATION 0
[cplayer] #define HAVE_APPLE_REMOTE 0
[cplayer] #define HAVE_SYS_SOUNDCARD_H (HAVE_OSS_AUDIO_NATIVE || HAVE_OSS_AUDIO_4FRONT)
[cplayer] #define HAVE_SOUNDCARD_H HAVE_OSS_AUDIO_SUNAUDIO
[cplayer] #define CONFIGURATION "./waf configure --prefix=/usr --confdir=/etc/mpv --enable-joystick --enable-zsh-comp --enable-libmpv-shared --enable-cdda"
[cplayer] #define MPV_CONFDIR "/etc/mpv"
[cplayer] 
[global] search dirs: /home/jug5/.config/mpv /home/jug5/.mpv /etc/mpv
[global] search dirs: /home/jug5/.config/mpv /home/jug5/.mpv /etc/mpv
[global] config path: 'encoding-profiles.conf' -> '/etc/mpv/encoding-profiles.conf'
[cplayer] Reading config file /etc/mpv/encoding-profiles.conf
[cplayer] 
[global] search dirs: /home/jug5/.config/mpv /home/jug5/.mpv /etc/mpv
[global] config file: 'mpv.conf|config'
[global]     -> '/home/jug5/.config/mpv/mpv.conf'
[cplayer] Reading config file /home/jug5/.config/mpv/mpv.conf
[cplayer] 
[cplayer] Setting option 'cache-secs' = '5' (flags = 4)
[cplayer] Setting option 'v' = '' (flags = 8)
[global] search dirs: /home/jug5/.config/mpv /home/jug5/.mpv /etc/mpv
[global] config file: 'input.conf'
[input] Falling back on default (hardcoded) input config
[input/#1] Setting up LIRC support...
[input/#1] Failed to open LIRC support. You will not be able to use your remote control.
[osc] Loading script @osc.lua...
[global] search dirs: /home/jug5/.config/mpv /home/jug5/.mpv /etc/mpv
[global] config file: 'scripts'
[global] search dirs: /home/jug5/.config/mpv /home/jug5/.mpv /etc/mpv
[global] config file: 'lua'
[osc] loading mp.defaults
[osc] loading @osc.lua
[global] search dirs: /home/jug5/.config/mpv /home/jug5/.mpv /etc/mpv
[global] config path: 'lua-settings/osc.conf' -> '(NULL)'
[osc] lua-settings/osc.conf not found. 
[cplayer] Done loading @osc.lua.
[ytdl_hook] Loading script @ytdl_hook.lua...
[global] search dirs: /home/jug5/.config/mpv /home/jug5/.mpv /etc/mpv
[global] config file: 'scripts'
[global] search dirs: /home/jug5/.config/mpv /home/jug5/.mpv /etc/mpv
[global] config file: 'lua'
[ytdl_hook] loading mp.defaults
[ytdl_hook] loading @ytdl_hook.lua
[cplayer] Run command: hook_add, flags=0, args=[on_load, 1, 10]
[cplayer] Done loading @ytdl_hook.lua.
[global] search dirs: /home/jug5/.config/mpv /home/jug5/.mpv /etc/mpv
[global] config file: 'scripts'
[global] search dirs: /home/jug5/.config/mpv /home/jug5/.mpv /etc/mpv
[global] config file: 'lua'
[global] search dirs: /home/jug5/.config/mpv /home/jug5/.mpv /etc/mpv
[global] config path: 'watch_later/51DB84918C0A44498C300EBE7DDFF753' -> '(NULL)'
[global] search dirs: /home/jug5/.config/mpv /home/jug5/.mpv /etc/mpv
[global] config path: 'watch_later' -> '(NULL)'
[global] search dirs: /home/jug5/.config/mpv /home/jug5/.mpv /etc/mpv
[global] config path: 'watch_later/51DB84918C0A44498C300EBE7DDFF753' -> '(NULL)'
[global] search dirs: /home/jug5/.config/mpv /home/jug5/.mpv /etc/mpv
[global] config path: 'watch_later' -> '(NULL)'
[cplayer] Playing: fam.mkv
[cplayer] Running hook: ytdl_hook/on_load
[cplayer] Run command: hook_ack, flags=0, args=[on_load]
[file] Opened: fam.mkv
[demux] Trying demuxer: disc (force-level: normal)
[demux] Trying demuxer: edl (force-level: normal)
[demux] Trying demuxer: cue (force-level: normal)
[demux] Trying demuxer: rawaudio (force-level: normal)
[demux] Trying demuxer: rawvideo (force-level: normal)
[demux] Trying demuxer: tv (force-level: normal)
[demux] Trying demuxer: libass (force-level: normal)
[demux] Trying demuxer: mkv (force-level: normal)
[mkv] Found the head...
[mkv] + a segment...
[mkv] /---- [ parsing seek head ] ---------
[mkv] \---- [ parsing seek head ] ---------
[mkv] |+ segment information...
[mkv] | + timecode scale: 1000000
[mkv] | + duration: 1297.312s
[mkv] | + segment uid ad e7 fd 65 2d e3 47 70 87 ed ce c3 d1 66 bb 96
[mkv] |+ segment tracks...
[mkv] | + a track...
[mkv] |  + Track number: 1
[mkv] |  + Track type: Video
[mkv] |  + Video track
[mkv] |   + Display width: 1280
[mkv] |   + Display height: 720
[mkv] |   + Pixel width: 1280
[mkv] |   + Pixel height: 720
[mkv] |  + Codec ID: V_MPEG4/ISO/AVC
[mkv] |  + CodecPrivate, length 40
[mkv] |  + Default duration: 41.708ms ( = 23.976 fps)
[mkv] | + a track...
[mkv] |  + Track number: 2
[mkv] |  + Track type: Audio
[mkv] |  + Audio track
[mkv] |   + Sampling frequency: 48000.000000
[mkv] |   + Channels: 6
[mkv] |  + Codec ID: A_AC3
[mkv] |  + Default duration: 32.000ms ( = 31.250 fps)
[mkv] | + a track...
[mkv] |  + Track number: 3
[mkv] |  + Track type: Subtitle
[mkv] |  + Codec ID: S_TEXT/UTF8
[mkv] |+ found cluster
[mkv] Deferring reading cues.
[mkv] All headers are parsed!
[mkv] Aspect: 1.777778
[demux] Detected file format: Matroska
[find_files] Loading external files in .
[global] search dirs: /home/jug5/.config/mpv /home/jug5/.mpv /etc/mpv
[global] config path: 'sub/' -> '(NULL)'
[cplayer]  (+) Video --vid=1 (h264)
[cplayer]  (+) Audio --aid=1 --alang=eng (*) (ac3)
[cplayer]  (+) Subs  --sid=1 --slang=eng (*) (subrip)
[cplayer] [V] fourcc:0x31637661  size:1280x720  fps:23.976
[vo/opengl/wayland] failed to connect to a wayland server: check if a wayland compositor is running
[vo/opengl/x11] X11 opening display: :0.0
[vo/opengl/x11] X11 running at 2560x1440 (":0.0" => local display)
[vo/opengl/x11] Detected wm supports NetWM.
[vo/opengl/x11] Detected wm supports ABOVE state.
[vo/opengl/x11] Detected wm supports BELOW state.
[vo/opengl/x11] Detected wm supports FULLSCREEN state.
[vo/opengl/x11] Display 0 (eDP1): [0, 0, 2560, 1440] @ 60.004441 FPS
[vo/opengl/x11] Current display FPS: 60.004441
[vo/opengl] GLX chose visual with ID 0xbc
[vo/opengl] GL_VERSION='3.0 Mesa 10.5.2'
[vo/opengl] Detected desktop OpenGL 3.0.
[vo/opengl] GL_VENDOR='Intel Open Source Technology Center'
[vo/opengl] GL_RENDERER='Mesa DRI Intel(R) HD Graphics 5500 (Broadwell GT2) '
[vo/opengl] GL_SHADING_LANGUAGE_VERSION='1.30'
[vo/opengl] OpenGL legacy compat. found.
[vo/opengl] Detected OpenGL features:
[vo/opengl]   - Framebuffers
[vo/opengl]   - VAOs
[vo/opengl]   - Float textures
[vo/opengl]   - RG textures
[vo/opengl]   - 1st class shader arrays
[vo/opengl]   - 1D textures
[vo/opengl]   - 3D textures
[vo/opengl]   - debugging extensions
[vo/opengl] 16 bit texture depth: 16.
[vo/opengl] Display depth: R=8, G=8, B=8
[vo/opengl] Reinit rendering.
[vo/opengl] Assuming 60.004441 FPS for framedrop.
[vd] Codec list:
[vd]     lavc:h264 - H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10
[vd]     lavc:h264_vdpau (h264) - H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10 (VDPAU acceleration)
[vd] Opening video decoder lavc:h264
[vd] Detected 4 logical cores.
[vd] Requesting 5 threads for decoding.
[vd] Selected video codec: H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10 [lavc:h264]
[vo/opengl/x11] Disabling screensaver.
[ad] Codec list:
[ad]     lavc:ac3 - ATSC A/52A (AC-3)
[ad]     lavc:ac3_fixed (ac3) - ATSC A/52A (AC-3)
[ad] Opening audio decoder lavc:ac3
[ad] Requesting 1 threads for decoding.
[ad] Selected audio codec: ATSC A/52A (AC-3) [lavc:ac3]
[global] search dirs: /home/jug5/.config/mpv /home/jug5/.mpv /etc/mpv
[global] config path: 'fonts' -> '(NULL)'
[sub] Subtitle filter chain: srt (subrip) -> ass (ass-text)
[global] search dirs: /home/jug5/.config/mpv /home/jug5/.mpv /etc/mpv
[global] config path: 'subfont.ttf' -> '(NULL)'
[global] search dirs: /home/jug5/.config/mpv /home/jug5/.mpv /etc/mpv
[global] config path: 'fonts.conf' -> '(NULL)'
[libass] Setting up fonts...
[libass] Done.
[cplayer] Starting playback...
[af] Audio filter chain:
[af]   [in] 48000Hz 5.1(side) 6ch floatp
[af]   [out] 48000Hz 5.1(side) 6ch floatp
[af]   [ao] 48000Hz 5.1(side) 6ch floatp
[ao/pulse] requested format: 48000 Hz, 5.1(side) channels, floatp
[ao/pulse] Library version: 6.0.0
[ao/pulse] Proto: 30
[ao/pulse] Server proto: 4294967295
[ao/alsa] requested format: 48000 Hz, 5.1(side) channels, floatp
[ao/alsa] using device: default
[ao/alsa] using ALSA version: 1.0.29
[ao/alsa] Got supported channel map: stereo (type FIXED)
[ao/alsa] trying to set ALSA channel map: FL FR
[ao/alsa] channel map reported by ALSA: FL FR
[ao/alsa] which we understand as: stereo
[ao/alsa] which is what we requested.
[ao/alsa] got buffersize=12288 samples
[ao/alsa] got period size 1024
[ao/alsa] device buffer: 12288 samples.
[ao/alsa] using soft-buffer of 12288 samples.
[cplayer] AO: [alsa] 48000Hz stereo 2ch float
[cplayer] AO: Description: ALSA audio output
[af] Adding filter lavrresample 
[af] Audio filter chain:
[af]   [in] 48000Hz 5.1(side) 6ch floatp
[af]   [lavrresample] 48000Hz stereo 2ch float
[af]   [out] 48000Hz stereo 2ch float
[af]   [ao] 48000Hz stereo 2ch float
[af] Removing filter lavrresample 
[af] Adding filter lavrresample 
[af] Audio filter chain:
[af]   [in] 48000Hz 5.1(side) 6ch floatp
[af]   [lavrresample] 48000Hz stereo 2ch float
[af]   [out] 48000Hz stereo 2ch float
[af]   [ao] 48000Hz stereo 2ch float
[ffmpeg/video] h264: Increasing reorder buffer to 1
[vd] VIDEO:  1280x720  23.976 fps    0.0 kbps ( 0.0 kB/s)
[vd] VDec: vo config request - 1280 x 720 (yuv420p)
[vd] VO Config (1280x720->1280x720,0x3EC)
[vf] Video filter chain:
[vf]   [vd] 1280x720 yuv420p BT.709 (HD)/TV CL=unknown
[vf]   [in] 1280x720 yuv420p BT.709 (HD)/TV CL=unknown
[vf]   [out] 1280x720 yuv420p BT.709 (HD)/TV CL=unknown
[cplayer] VO: [opengl] 1280x720 yuv420p
[cplayer] VO: Description: Extended OpenGL Renderer
[vo/opengl] Resize: 1280x720
[vo/opengl] Window size: 1280x720
[vo/opengl] Video source: 1280x720 (1280x720)
[vo/opengl] Video display: (0, 0) 1280x720 -> (0, 0) 1280x720
[vo/opengl] Video scale: 1.000000/1.000000
[vo/opengl] OSD borders: l=0 t=0 r=0 b=0
[vo/opengl] Video borders: l=0 t=0 r=0 b=0
[vo/opengl] Texture for plane 0: 1280x720
[vo/opengl] Texture for plane 1: 640x360
[vo/opengl] Texture for plane 2: 640x360
[vo/opengl] Reinit rendering.
[vo/opengl] compiling shader program 'frag_osd_libass', header:
[vo/opengl] [  1] #define VIDEO_SAMPLER sampler2D
[vo/opengl] compiling shader program 'frag_osd_rgba', header:
[vo/opengl] [  1] #define VIDEO_SAMPLER sampler2D
[vo/opengl] compiling shader program 'final', header:
[vo/opengl] [  1] #define VIDEO_SAMPLER sampler2D
[vo/opengl] [  2] #define SAMPLE(p0, p1, p2) sample_bilinear(p0, p1, p2, filter_param1_l)
[vo/opengl] [  3] #define USE_CONV CONV_PLANAR
[vo/opengl] [  4] #define USE_COLORMATRIX 1
[vo/opengl] [  5] #define SAMPLE_C(p0, p1, p2) sample_bilinear(p0, p1, p2, filter_param1_c)
[global] search dirs: /home/jug5/.config/mpv /home/jug5/.mpv /etc/mpv
[global] config path: 'fonts' -> '(NULL)'
[global] search dirs: /home/jug5/.config/mpv /home/jug5/.mpv /etc/mpv
[global] config path: 'subfont.ttf' -> '(NULL)'
[global] search dirs: /home/jug5/.config/mpv /home/jug5/.mpv /etc/mpv
[global] config path: 'fonts.conf' -> '(NULL)'
[osd/libass] Setting up fonts...
[osd/libass] Done.
[global] search dirs: /home/jug5/.config/mpv /home/jug5/.mpv /etc/mpv
[global] config path: 'fonts' -> '(NULL)'
[global] search dirs: /home/jug5/.config/mpv /home/jug5/.mpv /etc/mpv
[global] config path: 'subfont.ttf' -> '(NULL)'
[global] search dirs: /home/jug5/.config/mpv /home/jug5/.mpv /etc/mpv
[global] config path: 'fonts.conf' -> '(NULL)'
[osd/libass] Setting up fonts...
[osd/libass] Done.
[global] search dirs: /home/jug5/.config/mpv /home/jug5/.mpv /etc/mpv
[global] config path: 'fonts' -> '(NULL)'
[global] search dirs: /home/jug5/.config/mpv /home/jug5/.mpv /etc/mpv
[global] config path: 'subfont.ttf' -> '(NULL)'
[global] search dirs: /home/jug5/.config/mpv /home/jug5/.mpv /etc/mpv
[global] config path: 'fonts.conf' -> '(NULL)'
[osd/libass] Setting up fonts...
[osd/libass] Done.
[statusline] AV: 00:00:21 / 00:21:37 (1%) A-V:  0.000 Dropped: 0/1
[cplayer] Run command: quit, flags=9, args=[0]
[cplayer] EOF code: 6  
[cplayer] 
[ad] Uninit audio filters...
[af] Removing filter lavrresample 
[ad] Uninit audio decoder.
[vd] Uninit video.
[cplayer] 
[cplayer] Exiting... (Quit)
[ytdl_hook] Exiting...
[osc] Exiting...
[ao/alsa] draining...
[vo/opengl/x11] Enabling screensaver.
[vo/opengl/x11] uninit ...
```

mpv -v with vaapi
```
[cplayer] Command line: 'mpv' '-v' 'fam.mkv'
[cplayer] mpv 0.8.3 (C) 2000-2015 mpv/MPlayer/mplayer2 projects
[cplayer]  built on 2015-03-17T07:32:24
[cplayer] ffmpeg library versions:
[cplayer]    libavutil       54.20.100
[cplayer]    libavcodec      56.26.100
[cplayer]    libavformat     56.25.101
[cplayer]    libswscale      3.1.101
[cplayer]    libavfilter     5.11.102
[cplayer]    libswresample   1.1.100
[cplayer] 
[cplayer] Configuration: ./waf configure --prefix=/usr --confdir=/etc/mpv --enable-joystick --enable-zsh-comp --enable-libmpv-shared --enable-cdda
[cplayer] config.h:
[cplayer] 
[cplayer] #define DEFAULT_DVD_DEVICE "/dev/sr0"
[cplayer] #define DEFAULT_CDROM_DEVICE "/dev/sr0"
[cplayer] #define HAVE_CPLAYER 1
[cplayer] #define HAVE_LIBMPV_SHARED 1
[cplayer] #define HAVE_LIBMPV_STATIC 0
[cplayer] #define HAVE_STATIC_BUILD 0
[cplayer] #define HAVE_BUILD_DATE 1
[cplayer] #define HAVE_OPTIMIZE 1
[cplayer] #define HAVE_DEBUG_BUILD 1
[cplayer] #define HAVE_PDF_BUILD 0
[cplayer] #define HAVE_LIBDL 1
[cplayer] #define HAVE_DLOPEN 1
[cplayer] #define HAVE_VF_DLOPEN_FILTERS 0
[cplayer] #define HAVE_ZSH_COMP 1
[cplayer] #define HAVE_ASM 1
[cplayer] #define HAVE_TEST 0
[cplayer] #define HAVE_CLANG_DATABASE 0
[cplayer] #define HAVE_NOEXECSTACK 0
[cplayer] #define HAVE_LIBM 1
[cplayer] #define HAVE_MINGW 0
[cplayer] #define HAVE_POSIX 1
[cplayer] #define HAVE_POSIX_OR_MINGW 1
[cplayer] #define HAVE_WIN32_INTERNAL_PTHREADS 0
[cplayer] #define HAVE_PTHREADS 1
[cplayer] #define HAVE_STDATOMIC 1
[cplayer] #define HAVE_ATOMIC_BUILTINS 0
[cplayer] #define HAVE_SYNC_BUILTINS 0
[cplayer] #define HAVE_ATOMICS 1
[cplayer] #define HAVE_LIBRT 1
[cplayer] #define HAVE_ICONV 1
[cplayer] #define HAVE_DOS_PATHS 0
[cplayer] #define HAVE_WAIO 0
[cplayer] #define HAVE_TERMIOS_H 1
[cplayer] #define HAVE_SYS_TERMIOS_H 0
[cplayer] #define HAVE_TERMIOS 1
[cplayer] #define HAVE_SHM 1
[cplayer] #define HAVE_NANOSLEEP 1
[cplayer] #define HAVE_POSIX_SPAWN 1
[cplayer] #define HAVE_GLOB 1
[cplayer] #define HAVE_GLOB_WIN32_REPLACEMENT 0
[cplayer] #define HAVE_GLIBC_THREAD_NAME 1
[cplayer] #define HAVE_OSX_THREAD_NAME 0
[cplayer] #define HAVE_BSD_THREAD_NAME 0
[cplayer] #define HAVE_NETBSD_THREAD_NAME 0
[cplayer] #define HAVE_BSD_FSTATFS 0
[cplayer] #define HAVE_LINUX_FSTATFS 1
[cplayer] #define HAVE_LIBGUESS 1
[cplayer] #define HAVE_LIBSMBCLIENT 1
[cplayer] #define HAVE_LUA 1
[cplayer] #define HAVE_LIBASS 1
[cplayer] #define HAVE_LIBASS_OSD 1
[cplayer] #define HAVE_DUMMY_OSD 0
[cplayer] #define HAVE_ZLIB 1
[cplayer] #define HAVE_ENCODING 1
[cplayer] #define HAVE_JOYSTICK 1
[cplayer] #define HAVE_LIRC 1
[cplayer] #define HAVE_LIBBLURAY 1
[cplayer] #define HAVE_DVDREAD 1
[cplayer] #define HAVE_DVDNAV 1
[cplayer] #define HAVE_CDDA 1
[cplayer] #define HAVE_ENCA 1
[cplayer] #define HAVE_MPG123 1
[cplayer] #define HAVE_LADSPA 1
[cplayer] #define HAVE_LIBBS2B 0
[cplayer] #define HAVE_LCMS2 1
[cplayer] #define HAVE_VAPOURSYNTH_CORE 0
[cplayer] #define HAVE_VAPOURSYNTH 0
[cplayer] #define HAVE_VAPOURSYNTH_LAZY 0
[cplayer] #define HAVE_SDL2 0
[cplayer] #define HAVE_SDL1 0
[cplayer] #define HAVE_OSS_AUDIO_4FRONT 0
[cplayer] #define HAVE_OSS_AUDIO_NATIVE 1
[cplayer] #define HAVE_OSS_AUDIO_SUNAUDIO 0
[cplayer] #define HAVE_OSS_AUDIO 1
[cplayer] #define HAVE_RSOUND 0
[cplayer] #define HAVE_SNDIO 0
[cplayer] #define HAVE_PULSE 1
[cplayer] #define HAVE_JACK 1
[cplayer] #define HAVE_OPENAL 0
[cplayer] #define HAVE_ALSA 1
[cplayer] #define HAVE_COREAUDIO 0
[cplayer] #define HAVE_DSOUND 0
[cplayer] #define HAVE_WASAPI 0
[cplayer] #define HAVE_COCOA 0
[cplayer] #define HAVE_GDI 0
[cplayer] #define HAVE_WINMM 0
[cplayer] #define HAVE_OLE 0
[cplayer] #define HAVE_UUID 1
[cplayer] #define HAVE_WAYLAND 1
[cplayer] #define HAVE_X11 1
[cplayer] #define HAVE_XSS 0
[cplayer] #define HAVE_XEXT 1
[cplayer] #define HAVE_XV 1
[cplayer] #define HAVE_XINERAMA 1
[cplayer] #define HAVE_XRANDR 1
[cplayer] #define HAVE_GL_COCOA 0
[cplayer] #define HAVE_GL_X11 1
[cplayer] #define HAVE_EGL_X11 0
[cplayer] #define HAVE_GL_WAYLAND 1
[cplayer] #define HAVE_GL_WIN32 0
[cplayer] #define HAVE_GL 1
[cplayer] #define HAVE_VDPAU 1
[cplayer] #define HAVE_VDPAU_GL_X11 1
[cplayer] #define HAVE_VAAPI 1
[cplayer] #define HAVE_VAAPI_VPP 1
[cplayer] #define HAVE_VAAPI_GLX 1
[cplayer] #define HAVE_CACA 0
[cplayer] #define HAVE_JPEG 1
[cplayer] #define HAVE_DIRECT3D 0
[cplayer] #define HAVE_LIBAV 1
[cplayer] #define HAVE_LIBSWRESAMPLE 1
[cplayer] #define HAVE_LIBAVRESAMPLE 0
[cplayer] #define HAVE_RESAMPLER 1
[cplayer] #define HAVE_LIBAVFILTER 1
[cplayer] #define HAVE_LIBAVDEVICE 1
[cplayer] #define HAVE_AVCODEC_CHROMA_POS_API 1
[cplayer] #define HAVE_AVCOL_SPC_BT2020 1
[cplayer] #define HAVE_AVCODEC_VDPAU_ALLOC_CONTEXT 1
[cplayer] #define HAVE_AVCODEC_METADATA_UPDATE_SIDE_DATA 1
[cplayer] #define HAVE_AVFORMAT_METADATA_UPDATE_FLAG 1
[cplayer] #define HAVE_AVCODEC_REPLAYGAIN_SIDE_DATA 1
[cplayer] #define HAVE_AV_DISPLAYMATRIX 1
[cplayer] #define HAVE_AVFRAME_METADATA 1
[cplayer] #define HAVE_AVFRAME_SKIP_SAMPLES 1
[cplayer] #define HAVE_LIBAVCODEC_VAAPI_H 1
[cplayer] #define HAVE_VAAPI_HWACCEL 1
[cplayer] #define HAVE_VIDEODECODEACCELERATION_VDADECODER_H 0
[cplayer] #define HAVE_VIDEO_DECODE_ACCELERATION_VDA_DECODER_H 0
[cplayer] #define HAVE_VDA_HWACCEL 0
[cplayer] #define HAVE_VDA_GL 0
[cplayer] #define HAVE_VDPAU_HWACCEL 1
[cplayer] #define HAVE_DXVA2_HWACCEL 0
[cplayer] #define HAVE_TV 1
[cplayer] #define HAVE_SYS_VIDEOIO_H 0
[cplayer] #define HAVE_VIDEODEV 1
[cplayer] #define HAVE_TV_V4L2 1
[cplayer] #define HAVE_LIBV4L2 1
[cplayer] #define HAVE_PVR 1
[cplayer] #define HAVE_AUDIO_INPUT 1
[cplayer] #define HAVE_DVBIN 1
[cplayer] #define HAVE_WIN32_EXECUTABLE 0
[cplayer] #define HAVE_COCOA_APPLICATION 0
[cplayer] #define HAVE_APPLE_REMOTE 0
[cplayer] #define HAVE_SYS_SOUNDCARD_H (HAVE_OSS_AUDIO_NATIVE || HAVE_OSS_AUDIO_4FRONT)
[cplayer] #define HAVE_SOUNDCARD_H HAVE_OSS_AUDIO_SUNAUDIO
[cplayer] #define CONFIGURATION "./waf configure --prefix=/usr --confdir=/etc/mpv --enable-joystick --enable-zsh-comp --enable-libmpv-shared --enable-cdda"
[cplayer] #define MPV_CONFDIR "/etc/mpv"
[cplayer] 
[global] search dirs: /home/jug5/.config/mpv /home/jug5/.mpv /etc/mpv
[global] search dirs: /home/jug5/.config/mpv /home/jug5/.mpv /etc/mpv
[global] config path: 'encoding-profiles.conf' -> '/etc/mpv/encoding-profiles.conf'
[cplayer] Reading config file /etc/mpv/encoding-profiles.conf
[cplayer] 
[global] search dirs: /home/jug5/.config/mpv /home/jug5/.mpv /etc/mpv
[global] config file: 'mpv.conf|config'
[global]     -> '/home/jug5/.config/mpv/mpv.conf'
[cplayer] Reading config file /home/jug5/.config/mpv/mpv.conf
[cplayer] 
[cplayer] Setting option 'hwdec' = 'vaapi' (flags = 4)
[cplayer] Setting option 'vo' = 'opengl-hq' (flags = 4)
[cplayer] Setting option 'cache-secs' = '5' (flags = 4)
[cplayer] Setting option 'v' = '' (flags = 8)
[global] search dirs: /home/jug5/.config/mpv /home/jug5/.mpv /etc/mpv
[global] config file: 'input.conf'
[input] Falling back on default (hardcoded) input config
[input/#1] Setting up LIRC support...
[input/#1] Failed to open LIRC support. You will not be able to use your remote control.
[osc] Loading script @osc.lua...
[global] search dirs: /home/jug5/.config/mpv /home/jug5/.mpv /etc/mpv
[global] config file: 'scripts'
[global] search dirs: /home/jug5/.config/mpv /home/jug5/.mpv /etc/mpv
[global] config file: 'lua'
[osc] loading mp.defaults
[osc] loading @osc.lua
[global] search dirs: /home/jug5/.config/mpv /home/jug5/.mpv /etc/mpv
[global] config path: 'lua-settings/osc.conf' -> '(NULL)'
[osc] lua-settings/osc.conf not found. 
[cplayer] Done loading @osc.lua.
[ytdl_hook] Loading script @ytdl_hook.lua...
[global] search dirs: /home/jug5/.config/mpv /home/jug5/.mpv /etc/mpv
[global] config file: 'scripts'
[global] search dirs: /home/jug5/.config/mpv /home/jug5/.mpv /etc/mpv
[global] config file: 'lua'
[ytdl_hook] loading mp.defaults
[ytdl_hook] loading @ytdl_hook.lua
[cplayer] Run command: hook_add, flags=0, args=[on_load, 1, 10]
[cplayer] Done loading @ytdl_hook.lua.
[global] search dirs: /home/jug5/.config/mpv /home/jug5/.mpv /etc/mpv
[global] config file: 'scripts'
[global] search dirs: /home/jug5/.config/mpv /home/jug5/.mpv /etc/mpv
[global] config file: 'lua'
[global] search dirs: /home/jug5/.config/mpv /home/jug5/.mpv /etc/mpv
[global] config path: 'watch_later/51DB84918C0A44498C300EBE7DDFF753' -> '(NULL)'
[global] search dirs: /home/jug5/.config/mpv /home/jug5/.mpv /etc/mpv
[global] config path: 'watch_later' -> '(NULL)'
[global] search dirs: /home/jug5/.config/mpv /home/jug5/.mpv /etc/mpv
[global] config path: 'watch_later/51DB84918C0A44498C300EBE7DDFF753' -> '(NULL)'
[global] search dirs: /home/jug5/.config/mpv /home/jug5/.mpv /etc/mpv
[global] config path: 'watch_later' -> '(NULL)'
[cplayer] Playing: fam.mkv
[cplayer] Running hook: ytdl_hook/on_load
[cplayer] Run command: hook_ack, flags=0, args=[on_load]
[file] Opened: fam.mkv
[demux] Trying demuxer: disc (force-level: normal)
[demux] Trying demuxer: edl (force-level: normal)
[demux] Trying demuxer: cue (force-level: normal)
[demux] Trying demuxer: rawaudio (force-level: normal)
[demux] Trying demuxer: rawvideo (force-level: normal)
[demux] Trying demuxer: tv (force-level: normal)
[demux] Trying demuxer: libass (force-level: normal)
[demux] Trying demuxer: mkv (force-level: normal)
[mkv] Found the head...
[mkv] + a segment...
[mkv] /---- [ parsing seek head ] ---------
[mkv] \---- [ parsing seek head ] ---------
[mkv] |+ segment information...
[mkv] | + timecode scale: 1000000
[mkv] | + duration: 1297.312s
[mkv] | + segment uid ad e7 fd 65 2d e3 47 70 87 ed ce c3 d1 66 bb 96
[mkv] |+ segment tracks...
[mkv] | + a track...
[mkv] |  + Track number: 1
[mkv] |  + Track type: Video
[mkv] |  + Video track
[mkv] |   + Display width: 1280
[mkv] |   + Display height: 720
[mkv] |   + Pixel width: 1280
[mkv] |   + Pixel height: 720
[mkv] |  + Codec ID: V_MPEG4/ISO/AVC
[mkv] |  + CodecPrivate, length 40
[mkv] |  + Default duration: 41.708ms ( = 23.976 fps)
[mkv] | + a track...
[mkv] |  + Track number: 2
[mkv] |  + Track type: Audio
[mkv] |  + Audio track
[mkv] |   + Sampling frequency: 48000.000000
[mkv] |   + Channels: 6
[mkv] |  + Codec ID: A_AC3
[mkv] |  + Default duration: 32.000ms ( = 31.250 fps)
[mkv] | + a track...
[mkv] |  + Track number: 3
[mkv] |  + Track type: Subtitle
[mkv] |  + Codec ID: S_TEXT/UTF8
[mkv] |+ found cluster
[mkv] Deferring reading cues.
[mkv] All headers are parsed!
[mkv] Aspect: 1.777778
[demux] Detected file format: Matroska
[find_files] Loading external files in .
[global] search dirs: /home/jug5/.config/mpv /home/jug5/.mpv /etc/mpv
[global] config path: 'sub/' -> '(NULL)'
[cplayer]  (+) Video --vid=1 (h264)
[cplayer]  (+) Audio --aid=1 --alang=eng (*) (ac3)
[cplayer]  (+) Subs  --sid=1 --slang=eng (*) (subrip)
[cplayer] [V] fourcc:0x31637661  size:1280x720  fps:23.976
[vo/opengl-hq/wayland] failed to connect to a wayland server: check if a wayland compositor is running
[vo/opengl-hq/x11] X11 opening display: :0.0
[vo/opengl-hq/x11] X11 running at 2560x1440 (":0.0" => local display)
[vo/opengl-hq/x11] Detected wm supports NetWM.
[vo/opengl-hq/x11] Detected wm supports ABOVE state.
[vo/opengl-hq/x11] Detected wm supports BELOW state.
[vo/opengl-hq/x11] Detected wm supports FULLSCREEN state.
[vo/opengl-hq/x11] Display 0 (eDP1): [0, 0, 2560, 1440] @ 60.004441 FPS
[vo/opengl-hq/x11] Current display FPS: 60.004441
[vo/opengl-hq] GLX chose visual with ID 0xbc
[vo/opengl-hq] GL_VERSION='3.0 Mesa 10.5.2'
[vo/opengl-hq] Detected desktop OpenGL 3.0.
[vo/opengl-hq] GL_VENDOR='Intel Open Source Technology Center'
[vo/opengl-hq] GL_RENDERER='Mesa DRI Intel(R) HD Graphics 5500 (Broadwell GT2) '
[vo/opengl-hq] GL_SHADING_LANGUAGE_VERSION='1.30'
[vo/opengl-hq] OpenGL legacy compat. found.
[vo/opengl-hq] Detected OpenGL features:
[vo/opengl-hq]   - Framebuffers
[vo/opengl-hq]   - VAOs
[vo/opengl-hq]   - Float textures
[vo/opengl-hq]   - RG textures
[vo/opengl-hq]   - 1st class shader arrays
[vo/opengl-hq]   - 1D textures
[vo/opengl-hq]   - 3D textures
[vo/opengl-hq]   - debugging extensions
[vo/opengl-hq] 16 bit texture depth: 16.
[vo/opengl-hq] Display depth: R=8, G=8, B=8
[vo/opengl-hq] Testing user-set FBO format (0x805b)
[vo/opengl-hq] Create FBO: 16x16
[vo/opengl-hq] Reinit rendering.
[vo/opengl-hq] Reinit rendering.
[vo/opengl-hq] Assuming 60.004441 FPS for framedrop.
[vd] Codec list:
[vd]     lavc:h264 - H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10
[vd]     lavc:h264_vdpau (h264) - H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10 (VDPAU acceleration)
[vd] Opening video decoder lavc:h264
libva info: VA-API version 0.37.0
libva info: va_getDriverName() returns 0
libva info: Trying to open /usr/lib/dri/i965_drv_video.so
libva info: Found init function __vaDriverInit_0_37
libva info: va_openDriver() returns 0
[vo/opengl-hq/vaapi/vaapi] VA API version 0.37
[vo/opengl-hq/vaapi/vaapi] 8 image formats available:
[vo/opengl-hq/vaapi/vaapi]   YV12
[vo/opengl-hq/vaapi/vaapi]   I420
[vo/opengl-hq/vaapi/vaapi]   NV12
[vo/opengl-hq/vaapi/vaapi]   YUY2
[vo/opengl-hq/vaapi/vaapi]   UYVY
[vo/opengl-hq/vaapi/vaapi]   422H
[vo/opengl-hq/vaapi/vaapi]   RGBX
[vo/opengl-hq/vaapi/vaapi]   BGRX
[vd] Trying to use hardware decoding.
[vd] Selected video codec: H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10 [lavc:h264]
[vo/opengl-hq/x11] Disabling screensaver.
[ad] Codec list:
[ad]     lavc:ac3 - ATSC A/52A (AC-3)
[ad]     lavc:ac3_fixed (ac3) - ATSC A/52A (AC-3)
[ad] Opening audio decoder lavc:ac3
[ad] Requesting 1 threads for decoding.
[ad] Selected audio codec: ATSC A/52A (AC-3) [lavc:ac3]
[global] search dirs: /home/jug5/.config/mpv /home/jug5/.mpv /etc/mpv
[global] config path: 'fonts' -> '(NULL)'
[sub] Subtitle filter chain: srt (subrip) -> ass (ass-text)
[global] search dirs: /home/jug5/.config/mpv /home/jug5/.mpv /etc/mpv
[global] config path: 'subfont.ttf' -> '(NULL)'
[global] search dirs: /home/jug5/.config/mpv /home/jug5/.mpv /etc/mpv
[global] config path: 'fonts.conf' -> '(NULL)'
[libass] Setting up fonts...
[libass] Done.
[cplayer] Starting playback...
[af] Audio filter chain:
[af]   [in] 48000Hz 5.1(side) 6ch floatp
[af]   [out] 48000Hz 5.1(side) 6ch floatp
[af]   [ao] 48000Hz 5.1(side) 6ch floatp
[ao/pulse] requested format: 48000 Hz, 5.1(side) channels, floatp
[ao/pulse] Library version: 6.0.0
[ao/pulse] Proto: 30
[ao/pulse] Server proto: 4294967295
[ao/alsa] requested format: 48000 Hz, 5.1(side) channels, floatp
[ao/alsa] using device: default
[ao/alsa] using ALSA version: 1.0.29
[ao/alsa] Got supported channel map: stereo (type FIXED)
[ao/alsa] trying to set ALSA channel map: FL FR
[ao/alsa] channel map reported by ALSA: FL FR
[ao/alsa] which we understand as: stereo
[ao/alsa] which is what we requested.
[ao/alsa] got buffersize=12288 samples
[ao/alsa] got period size 1024
[ao/alsa] device buffer: 12288 samples.
[ao/alsa] using soft-buffer of 12288 samples.
[cplayer] AO: [alsa] 48000Hz stereo 2ch float
[cplayer] AO: Description: ALSA audio output
[af] Adding filter lavrresample 
[af] Audio filter chain:
[af]   [in] 48000Hz 5.1(side) 6ch floatp
[af]   [lavrresample] 48000Hz stereo 2ch float
[af]   [out] 48000Hz stereo 2ch float
[af]   [ao] 48000Hz stereo 2ch float
[af] Removing filter lavrresample 
[af] Adding filter lavrresample 
[af] Audio filter chain:
[af]   [in] 48000Hz 5.1(side) 6ch floatp
[af]   [lavrresample] 48000Hz stereo 2ch float
[af]   [out] 48000Hz stereo 2ch float
[af]   [ao] 48000Hz stereo 2ch float
[vd] Pixel formats supported by decoder: vdpau vaapi_vld yuv420p
[vaapi] Using profile 'VAProfileH264High'.
[vd] Pixel formats supported by decoder: vdpau vaapi_vld yuv420p
[vd] VIDEO:  1280x720  23.976 fps    0.0 kbps ( 0.0 kB/s)
[vd] VDec: vo config request - 1280 x 720 (vaapi)
[vd] VO Config (1280x720->1280x720,0x42A)
[vf] Video filter chain:
[vf]   [vd] 1280x720 vaapi BT.709 (HD)/TV CL=unknown
[vf]   [in] 1280x720 vaapi BT.709 (HD)/TV CL=unknown
[vf]   [out] 1280x720 vaapi BT.709 (HD)/TV CL=unknown
[cplayer] VO: [opengl-hq] 1280x720 vaapi
[cplayer] VO: Description: Extended OpenGL Renderer (high quality rendering preset)
[vo/opengl-hq] Resize: 1280x720
[vo/opengl-hq] Window size: 1280x720
[vo/opengl-hq] Video source: 1280x720 (1280x720)
[vo/opengl-hq] Video display: (0, 0) 1280x720 -> (0, 0) 1280x720
[vo/opengl-hq] Video scale: 1.000000/1.000000
[vo/opengl-hq] OSD borders: l=0 t=0 r=0 b=0
[vo/opengl-hq] Video borders: l=0 t=0 r=0 b=0
[vo/opengl-hq] Reinit rendering.
[vo/opengl-hq] Testing user-set FBO format (0x805b)
[vo/opengl-hq] Create FBO: 16x16
[vo/opengl-hq] Texture for plane 0: 1280x720
[vo/opengl-hq] Reinit rendering.
[vo/opengl-hq] Dither to 8.
[vo/opengl-hq] compiling shader program 'frag_osd_libass', header:
[vo/opengl-hq] [  1] #define VIDEO_SAMPLER sampler2D
[vo/opengl-hq] compiling shader program 'frag_osd_rgba', header:
[vo/opengl-hq] [  1] #define VIDEO_SAMPLER sampler2D
[vo/opengl-hq] compiling shader program 'indirect', header:
[vo/opengl-hq] [  1] #define VIDEO_SAMPLER sampler2D
[vo/opengl-hq] [  2] #define USE_COLOR_SWIZZLE rgbr
[vo/opengl-hq] [  3] #define USE_LINEAR_LIGHT_BT1886 1
[vo/opengl-hq] [  4] #define USE_CHROMA_FIX 1
[vo/opengl-hq] [  5] #define SAMPLE_C SAMPLE_TRIVIAL
[vo/opengl-hq] [  6] #define SAMPLE SAMPLE_TRIVIAL
[vo/opengl-hq] [  7] #define FIXED_SCALE 1
[vo/opengl-hq] compiling shader program 'scale_sep', header:
[vo/opengl-hq] [  1] #define VIDEO_SAMPLER sampler2D
[vo/opengl-hq] [  2] #define FIXED_SCALE 1
[vo/opengl-hq] [  3] #define DEF_SCALER0 \
[vo/opengl-hq] [  4]     SAMPLE_CONVOLUTION_SEP_N(sample_scaler0, vec2(0, 1), 6, lut_2d_l, weights6)
[vo/opengl-hq] [  5] #define SAMPLE sample_scaler0
[vo/opengl-hq] compiling shader program 'final', header:
[vo/opengl-hq] [  1] #define VIDEO_SAMPLER sampler2D
[vo/opengl-hq] [  2] #define USE_INV_BT1886 1
[vo/opengl-hq] [  3] #define USE_DITHER 1
[vo/opengl-hq] [  4] #define DEF_SCALER0 \
[vo/opengl-hq] [  5]     SAMPLE_CONVOLUTION_SEP_N(sample_scaler0, vec2(1, 0), 6, lut_2d_l, weights6)
[vo/opengl-hq] [  6] #define SAMPLE sample_scaler0
[vo/opengl-hq] Create FBO: 1280x720
[vo/opengl-hq] Create FBO: 1280x768
[global] search dirs: /home/jug5/.config/mpv /home/jug5/.mpv /etc/mpv
[global] config path: 'fonts' -> '(NULL)'
[global] search dirs: /home/jug5/.config/mpv /home/jug5/.mpv /etc/mpv
[global] config path: 'subfont.ttf' -> '(NULL)'
[global] search dirs: /home/jug5/.config/mpv /home/jug5/.mpv /etc/mpv
[global] config path: 'fonts.conf' -> '(NULL)'
[osd/libass] Setting up fonts...
[osd/libass] Done.
[global] search dirs: /home/jug5/.config/mpv /home/jug5/.mpv /etc/mpv
[global] config path: 'fonts' -> '(NULL)'
[global] search dirs: /home/jug5/.config/mpv /home/jug5/.mpv /etc/mpv
[global] config path: 'subfont.ttf' -> '(NULL)'
[global] search dirs: /home/jug5/.config/mpv /home/jug5/.mpv /etc/mpv
[global] config path: 'fonts.conf' -> '(NULL)'
[osd/libass] Setting up fonts...
[osd/libass] Done.
[global] search dirs: /home/jug5/.config/mpv /home/jug5/.mpv /etc/mpv
[global] config path: 'fonts' -> '(NULL)'
[global] search dirs: /home/jug5/.config/mpv /home/jug5/.mpv /etc/mpv
[global] config path: 'subfont.ttf' -> '(NULL)'
[global] search dirs: /home/jug5/.config/mpv /home/jug5/.mpv /etc/mpv
[global] config path: 'fonts.conf' -> '(NULL)'
[osd/libass] Setting up fonts...
[osd/libass] Done.
[ffmpeg/video] h264: Increasing reorder buffer to 1
[statusline] AV: 00:00:14 / 00:21:37 (1%) A-V:  0.000 Dropped: 0/1
[cplayer] Run command: quit, flags=9, args=[0]
[cplayer] EOF code: 6  
[cplayer] 
[ad] Uninit audio filters...
[af] Removing filter lavrresample 
[ad] Uninit audio decoder.
[vd] Uninit video.
[cplayer] 
[cplayer] Exiting... (Quit)
[ytdl_hook] Exiting...
[osc] Exiting...
[ao/alsa] draining...
[vo/opengl-hq/x11] Enabling screensaver.
[vo/opengl-hq/x11] uninit ...
```

**Comment by wm4** [comment]
Well, I don't know. We've had a lot of problem with vaapi's GLX interop. Try ``hwdec=vaapi-copy``.

**Comment by sjug** [comment]
Are there any other logs or configs I can provide that would be useful in debugging?

**Comment by Gusar321** [comment]
Does it also happen with --vo=vaapi? This would show if the problem is vaapi itself or if it's the GLX interop.

Perhaps mpv should consider moving from VA/GLX to texture_from_pixmap. By that I mean instead of using va*SurfaceGLX(), you do vaPutSurface() to a pixmap and then bind this pixmap to a texture with glXBindTexImageEXT(). XBMC/Kodi moved to that, as did libvdpau-va-gl, gstreamer-vaapi uses this method too. It seems to be more robust and it's also more efficient, because the point of texture_from_pixmap is zero-copy.

The libvdpau-va-gl commit is [here](https://github.com/i-rinat/libvdpau-va-gl/commit/8bec556e31919a4309c28e061e79946a9eeecae0), mplayer-vaapi implemented tfp in [this](https://gitorious.org/vaapi/mplayer/commit/4a4fd8d78668fc19e37dd480f60f35bba1aee220) commit.

**Comment by wm4** [comment]
That API is way more complex. Oh what am I expecting from Intel shit.

**Comment by wm4** [comment]
I implemented it. Now tell me if it's less broken, more broken, or equally broken.

**Comment by wm4** [comment]
PS: to clarify, in git master ``--vo=opengl --hwdec=vaapi`` uses texture-from-pixmap now.

**Comment by Gusar321** [comment]
I did not have problems before, but I don't have Broadwell like sjug does. Currently I can test Ironlake and Baytrail. And what I can report is, it still works. The turbostat output on Baytrail is interesting. Before:
```
Core     CPU Avg_MHz   %Busy Bzy_MHz TSC_MHz     SMI  CPU%c1  CPU%c6 CoreTmp Pkg%pc3 Pkg%pc6 PkgWatt CorWatt
   -       -     112   18.91     594    1600       0    2.36   78.74      46    0.00    0.00    0.95    0.19
   0       0     127   22.78     558    1600       0    3.61   73.61      45    0.00    0.00    0.95    0.19
   1       1      98   15.03     650    1600       0    1.10   83.87      46
```
Now:
```
Core     CPU Avg_MHz   %Busy Bzy_MHz TSC_MHz     SMI  CPU%c1  CPU%c6 CoreTmp Pkg%pc3 Pkg%pc6 PkgWatt CorWatt
   -       -     106   18.35     576    1600       0    1.05   80.60      44    0.00    0.00    0.73    0.19
   0       0      91   16.69     546    1600       0    0.97   82.33      44    0.00    0.00    0.73    0.19
   1       1     120   20.01     601    1600       0    1.12   78.87      44
```
This does hint at TFP being more efficient, especially the PkgWatt number. For comparison, the vaapi vo:
```
Core     CPU Avg_MHz   %Busy Bzy_MHz TSC_MHz     SMI  CPU%c1  CPU%c6 CoreTmp Pkg%pc3 Pkg%pc6 PkgWatt CorWatt
   -       -      75   13.73     550    1600       0    0.88   85.40      44    0.00    0.00    0.45    0.18
   0       0      75   13.65     546    1600       0    0.91   85.45      43    0.00    0.00    0.45    0.18
   1       1      76   13.81     554    1600       0    0.85   85.35      44
```
And without hardware decoding - as expected, significant difference in CPU utilization:
```
Core     CPU Avg_MHz   %Busy Bzy_MHz TSC_MHz     SMI  CPU%c1  CPU%c6 CoreTmp Pkg%pc3 Pkg%pc6 PkgWatt CorWatt
   -       -     283   48.09     589    1600       0    0.73   51.18      44    0.00    0.00    0.46    0.19
   0       0     276   46.82     589    1600       0    0.73   52.45      43    0.00    0.00    0.46    0.19
   1       1     291   49.36     589    1600       0    0.73   49.90      44
```

Running turbostat on Haswell should be interesting, there it also reports GfxWatt. I expect a big difference between vaapi and opengl, as opengl stresses the GPU, while vaapi uses fixed function hardware.

**Comment by sjug** [comment]
@wm4 you are awesome man, I'm working on testing this. I need to buy you a beer or something.

**Comment by sjug** [comment]
@Gusar321 how do you run turbostat against mpv playback?

**Comment by sjug** [comment]
Well this issue looks to be fixed, but I do see some other issues.
- Full screen with some videos with 0.8.3 showed full black no picture, with current git build it has a few frames of picture with a horizontal black bar and crazy non-stop black flicker
- Potential memory leak with current build, after panning and scanning back and forth (left and right arrow on KB) for a minute memory use increases 20%+ (--vo=opengl --hw-dec=vaapi)

Should we close this ticket any open a new one?

**Comment by Jiehong** [comment]
Intel has released a new version of its libva-intel-driver: 1.5.1 (http://www.freedesktop.org/software/vaapi/releases/libva-intel-driver/)

On Archlinux, we are still using the 1.5.0 though (the new version should be ready soon).

It may be worth checking if this bug has been fixed upstream as well, even if the updates seems to be mostly focused on the Gen8 graphics.

**Comment by Gusar321** [comment]
> how do you run turbostat against mpv playback?

Quite simple:
```
sudo turbostat -- mpv --really-quiet --no-loop --no-audio --hwdec=vaapi --vo=opengl-hq file.mp4
```
Once mpv finishes, turbostat will print the report. Use a file that isn't too long :). Repeat the process with different values for hwdec and vo.

Also, Jiehong's advice is good, you might want to switch libva and libva-intel-driver to 1.5.1. Broadwell is very new, so it's good to have the latest components of everything. Might even want to try the 4.0-rc6 kernel.

**Comment by sjug** [comment]
@Gusar321 Thanks for that, I guess because it's the root user forking the process that it doesn't read my user config file. As without the explicit hwdec and vo flags it doesn't use vaapi?

It's entirely possible it's a "new drivers" issue.

**Comment by mc4man** [comment]
While never broken on Haswell the new changes haven't caused any new issue.
(- if interested in turbostat compares before, (git-bf69edb)  & after,  (git-a18dc01)  - 
http://paste.ubuntu.com/10754110/
file used - Jellyfish-50 http://jell.yfish.us/

**Comment by sjug** [comment]
After moving to libva-intel-driver 1.5.1 and using the latest git-master build most of my issues are now resolved.

**Comment by wm4** [comment]
Good to hear. I'll close this, then.

I'm also wondering if I should switch ``--hwdec=auto`` back to using ``vaapi`` instead of ``vaapi-copy``.

**Comment by Gusar321** [comment]
I'd advocate switching. On SD video, vaapi-copy does no better than software decoding. Turbostat on my Haswell machine decoding 720x404: http://pastebin.ca/2969778

Things are a bit different with HD, turbostat when decoding 720p: http://pastebin.ca/2969780

BTW, what about making --hwdec=auto the default? Is Intel the reason this isn't done? Texture_from_pixmap has made a big difference, perhaps hardware decoding by default is now feasible.

**Comment by wm4** [comment]
>BTW, what about making --hwdec=auto the default? Is Intel the reason this isn't done? Texture_from_pixmap has made a big difference, perhaps hardware decoding by default is now feasible.

Intel was/is a big reason, and VDA probably too, but it's possible that both are fixed now. I still don't see much value with hw decoding on desktop though, and it also prevents some of the high quality filters in vo_opengl to work properly (because most hw decoding methods give us RGB instead of YUV).

**Comment by sjug** [comment]
I don't own a desktop and haven't for years, and on laptops power consumption is always a major concern.
