### ISSUE TITLE
Angled display stretching/tearing with drm backend on nouveau

### ISSUE THREAD

**Issue by hobbitalastair** [mpv-player/mpv#1979]
Using the DRM backend with nouveau hardware results in some strange stretching/tearing issues.
I'm using the Arch Linux build of mpv.

![screen](https://cloud.githubusercontent.com/assets/6619576/7790620/85d58918-02e2-11e5-9d56-f015cb7cbc36.png)

Screen shot is full size; I can shrink it if needed. Playback in Weston works fine.

    mpv <filename> -vo=drm

**Comment by Idlusen** [comment]
Same issue, using Intel graphics.
I also use the arch build but quickly testing with a git build doesn't seem to change anything.

**Comment by rr-** [comment]
What is your screen resolution and bit depth?

**Comment by hobbitalastair** [comment]
I'm assuming, based on the fbset output, 1366x768 by 32 bit. Note that I haven't tested other videos - I'll try again with something else later today.

    $> fbset
    mode "1366x768"
        geometry 1366 768 1366 768 32
        timings 0 0 0 0 0 0 0
        accel true
        rgba 8/16 8/8 8/0 0/0
    endmode

**Comment by rr-** [comment]
Is it possible for you to provide an uncompressed, 1:1 PNG screenshot of the source frame in the video and the same frame malformed in vo_drm so that I can compare how RGB data is being misplaced?

**Comment by hobbitalastair** [comment]
Possibly... I'll give it a go.

I tried running another video, which had the same issues.
With --video-unscaled, the small (510x217) video was stretched across the entire screen horizontally. Taking a screenshot within mpv works well, although it's not scaled. I can't seem to take a screenshot with ctrl-s within mpv, either.

Interestingly enough, fbgrab returns a mutilated image, even of just the console. So the image I put up before, although it looks similar to what I saw, is not correct...
I'll have to investigate that as well.
I've also got a machine with older intel graphics - I'll try that later today, and probably try downgrading to an older kernel on this machine.

**Comment by Gusar321** [comment]
> I can't seem to take a screenshot with ctrl-s within mpv, either.

No command with ctrl works, some interaction issue between mpv and the console, mpv will print "[input] No bind found for key 0x1" with different 0x values depending on which key your press together with ctrl (hmm, I think a bug should be opened about that :)). Bind "screenshot window" to something that doesn't use ctrl.

BTW, vo_drm works fine here on Intel graphics, as does fbgrab. Could be something weird in the current Arch kernel? I'm on Arch, but I use custom kernels, 4.1.0-rc3 currently. Try the linux-lts package.

**Comment by hobbitalastair** [comment]
Intel (G45) works, including fbgrab. At the moment, I'm leaning towards it just being an issue with the nouveau drm support on that particular GPU, but I'll try a few other things first. To me it looks a bit like each line of the video is shifted ~20 pixels to the left, although the effect is only obvious on a non-scaled video - scaling seems to muck it up further. I'll try with a different screen resolution and older kernel first, though.

@Idlusen : Intel graphics work for both me and Gusar321; what's unique about your setup?
@rr- : Apart from getting a screenshot, what else would be helpful?

**Comment by hobbitalastair** [comment]
An older kernel (linux-lts, 3.14.43) does not help. Unfortunately, plugging in an external monitor really stuffed things up (including the mouse driver???), so I'm leaving that for now. I'll call it beyond my expertise/amount of effort I wish to expend. I'll try to get a screenshot of the issue for @rr-...

**Comment by rr-** [comment]
So far my guess is that your hardware tells incorrect stride (an integer meaning "full" row size) to mpv, or vo_drm doesn't read something it should (but I have no idea what could that be).
The one thing that comes to my mind is to expose an user-configurable option to override stride reported by Linux DRM.

**Comment by hobbitalastair** [comment]
@rr- The machine with nvidia graphics is going back to it's original owner in another couple of weeks, so I'm not too worried. If you think it's a driver/hardware bug, just mark it as such - I haven't been able to get a decent screenshot either, so I suspect it's not an issue in mpv. I'm slightly surprised since fbv works, but...

[This thread](https://bbs.archlinux.org/viewtopic.php?id=113998), despite being old, seems similar. fbdump does work, but must do something a bit different since it only returns what's visible on the console, which is not the same as what is on the screen!

I'm possibly getting confused as to what each program is using - drm or fb devices - but hopefully this makes some sense.
My last thought was that the linked thread's OP has the same resolution screen as I do. Maybe there's an issue related to that?

**Comment by rr-** [comment]
I'm reluctant to dismiss the issue as a hardware problem without solid proof. For now it's just a theory. I'm going to try different screen modes at home.

**Comment by hobbitalastair** [comment]
OK.
If there's anything that I could do to help, I'd be happy to try...

**Comment by Idlusen** [comment]
Sorry for the late response.
I have basically the same problems as hobbitalastair to capture the output, plus the framebuffer sometimes freezes, which is quite unfortunate.
Nothing very special about my setup comes to my mind, I installed my current system a week ago to run live on usb and concerning graphics/multimedia left pretty much as it was out of the box.
I also start to wonder if it’s even an mpv issue, but providing this stride option wouldn’t hurt.

**Comment by Gusar321** [comment]
On the weekend, I'll have access to a machine connected to a 1366x768 monitor that I can put a Geforce GTS450 in (the machine usually runs on the internal Intel GPU). I'll play with nouveau then, see if I can reproduce. Should be fun, the EDID of the display, whose only input is VGA, specifies 1360x768 as the default resolution, so I need to explicitly set 1366x768 on the kernel commandline and/or X config. We'll see what happens. I too don't think it's a mpv issue, and it does seem as if resolution plays a role.

Kind of off-topic, but maybe useful in this case, I've been playing with a framebuffer vo. Basically, I took vo_fb.c from the wip branch, copied stuff from vo_drm to it and then did some tweaks to provide a non-fullscreen mode. I did it mainly for the heck of it, but also because I wanted the non-fullscreen like mplayer provides. Anyway, here's the result: https://gist.github.com/Gusar321/9bc556492bdf37890f20
Someone who actually knows how to code will probably cringe at how I did some things :), but it does work. Give it a go, see if it works or shows the same issue as vo_drm

**Comment by wm4** [comment]
Can someone tell us the exact pitch value the API reports, and what overridden value makes it work?

@rr-: did you verify whether the pitch value actually works with the rest of our code? Maybe some alignment issue or so.

>Kind of off-topic, but maybe useful in this case, I've been playing with a framebuffer vo. Basically, I took vo_fb.c from the wip branch, copied stuff from vo_drm to it

That's of course not optimal from a code sharing perspective.

> and then did some tweaks to provide a non-fullscreen mode. I did it mainly for the heck of it, but also because I wanted the non-fullscreen like mplayer provides.

What's non-fullscreen? There's no window manager.

**Comment by Gusar321** [comment]
> That's of course not optimal from a code sharing perspective.

It's basically the swscale setup. That one is already sort of duplicated in all software outputs (vo_x11, vo_drm, ...).

> What's non-fullscreen? There's no window manager.

True, but you can do something like "mpv --vo=fb --autofit=40%x40% --geometry=100%:0 somefile.mkv", then switch to a different VT, and you'll have the video playing in the top right corner, while you use the console for other stuff. You can even reuse the same VT if you do --really-quiet --input-file=/path/to/fifo and background the player.

It's basically a hack, image data is being copied into the framebuffer while the console is in text mode. But mplayer works like that, and in particular this blog about Linux adventures in the console often mentioned such usage, that's where I got the idea from: https://kmandla.wordpress.com/

**Comment by rr-** [comment]
That's actually pretty cool. (Sort of `libcaca` cool.)

**Comment by rr-** [comment]
Should be fixed in 5a1ef9d8db9a8f9fa5670a94c265e806e30517f1

**Comment by Idlusen** [comment]
> Can someone tell us the exact pitch value the API reports, and what overridden value makes it work?

I’m sorry I’m not sure of what/where I should look.
Anyway, rr-’s commit does fix the issue for me. Thanks.

**Comment by hobbitalastair** [comment]
@rr- Great, thanks! It kind-of works now...
However, on the previously-mentioned laptop, the video is now offset - not centred properly. I tried both scaled and unscaled...
It wraps around properly, though.
Should I open a separate issue for this?
I still can't take a screenshot, and the machine in question is slowly being stripped for parts, but I'll be able to test any changes for a while yet. I could take a photo, though, if that would help?

I'm impressed that it's not a driver issue - I'll have to be less hasty in the future. Perhaps, for those of us who don't know what we are talking about, you would care to elaborate on why the 'stride' might be different?

**Comment by rr-** [comment]
@hobbitalastair I think the offset is to be expected. You should try other modes `-vo=drm:mode=-1` to see list of available modes.

**Comment by Gusar321** [comment]
I don't think the offset with wraparound should be expected. I got it when testing vo_fb if things weren't set correctly. Very likely the shift value for memcpy_pic is wrong, so the first line doesn't start at the position it should. That would create the kind of wraparound effect hobbitalastair describes. Perhaps checking all values where you hardcode multiplying by 4 is in order.

**Comment by rr-** [comment]
>I don't think the offset with wraparound should be expected.

Well... what happens if you use a 640x480 resolution on a 16:9 device and play a 16:9 video in it?

This is how it looks in the software:

![img1](https://cloud.githubusercontent.com/assets/1045476/7880826/8dfe7244-05fd-11e5-916f-520db88298ae.png)

This is how it looks physically:

![result](https://cloud.githubusercontent.com/assets/1045476/7880850/b2f493e4-05fd-11e5-979c-f4e801bedf67.png)

Look closely what gets multiplied by 4.

**Comment by rr-** [comment]
Nevermind: I see `shift` is still using `device_w` rather than `front_buf->stride`. I'm going to fire another PR once I get home. (For my device the difference between stride and actual resolution was so small that I completely missed it. Sorry.)

**Comment by Gusar321** [comment]
Heh, I was right, it was the shift value :). And here a demonstration of how the wraparound looks like, I hardcoded a wrong offset to create it: http://imgur.com/g1ipcJU

**Comment by rr-** [comment]
Things should be better with 476371872857536e785e702811d845e9abd86b9d.

**Comment by hobbitalastair** [comment]
@rr- Just tested (the machine is back in one piece again...) and it works well, thanks!
Should this issue be closed?

**Comment by rr-** [comment]
Yep. I'm glad it worked.

**Comment by hobbitalastair** [comment]
Right. I believe that this is fixed; thanks to all that helped. Hopefully I'll find another movie I want to watch at some point, so I can try mpv out again :)
