### ISSUE TITLE
Inconsistent fullscreen OSC playlist scaling

### ISSUE THREAD

**Issue by Coacher** [mpv-player/mpv#4083]
Hello.

### mpv version and platform
I have mpv-git @ 9c90c90 on Gentoo amd64.

### Reproduction steps
1. Open several video files in fullscreen and make OSD playlist displayed e.g. by clicking `pl next`.
2. Open several audio files with attached album cover art in fullscreen and make OSD playlist displayed e.g. by clicking `pl next`.
3. Open several audio-only files with '--force-window=yes' option in fullscreen and make OSD playlist displayed e.g. by clicking `pl next`.

### Expected behavior
OSD playlist has the same scaling between all three windows since video area has the same size (whole screen).

### Actual behavior
OSD playlist has incorrect scaling with video files and makes playlist gigantic.
OSD playlists for audio files with and without coverart also have different scaling, but I don't see a reason for them to be.
Notice how OSC itself has incorrect scaling with audio-only files and forced window.

### Log file
Not sure if any logs required here. I'll gladly provide them if you need it.
Here are some screenshots though:
- video fullscreen: http://i.imgur.com/aO6vSoZ.jpg
- audio with album art fullscreen: http://i.imgur.com/9oR1ZRg.jpg
- audio only fullscreen: http://i.imgur.com/KxZ5QzW.jpg

Please fix.

**Comment by wm4** [comment]
That's the OSC, not OSD.

> Please fix.

Depends on whether we decide whether this is a bug.

**Comment by wiiaboo** [comment]
There's a separate option for force-window=yes which is scaleforcewindow which defaults to 2. This was before my changes.

I'll need any osc.conf options you setup and any osd options, since I can't reproduce with --no-config.

**Comment by Coacher** [comment]
This is reproducible with `--no-config` as well. Here's my config anyway:
osc.conf:
```
seekbarstyle=knob
```
mpv.conf:
```
ytdl-format=best[height<=?720]
hwdec=vaapi
ao=pulse
```

**Comment by wiiaboo** [comment]
The only issue is the first screenshot. The other two should be inconsistent because of scaleforcedwindow=2 default.
What's the resolution on the video of the first one?

**Comment by wiiaboo** [comment]
audio with album art:
https://i.fsbn.eu/bAHb.png
`--audio-display=no --force-window`:
https://i.fsbn.eu/82PU.png
`--audio-display=no --force-window --script-opts=osc-scaleforcedwindow=1`:
https://i.fsbn.eu/APXZ.png

**Comment by Coacher** [comment]
If I manually set `osc-scaleforcedwindow=1`, I can reproduce your behaviour and there are no inconsistencies.

In the case of videos there are multiple videos with resolutions 1280x720 or 480x360. No other resolutions in that playlist. The first video has resolution 1280x720. Videos were downloaded with `youtube-dl -f best`.

**Comment by wiiaboo** [comment]
Can't reproduce then. Unless it's some race condition, I can't tell by the code why the letters would be that big.
Can you reproduce it consistently?

**Comment by Coacher** [comment]
> Can you reproduce it consistently?

Yes, reproducible 100% of the time. I use mpv built against luajit-2.0.4 if it matters.

**Comment by wiiaboo** [comment]
OK, I think I got it now, what's the default sans-serif font in your system? If I use DejaVu Sans with large enough filenames it does wrap and start to look like your screenshot.

Ways to fix this would be to start downscaling with fewer lines, disallow wrapping, or changing osd-font-size. The first one seems more appropriate to me.

**Comment by Coacher** [comment]
> OK, I think I got it now, what's the default sans-serif font in your system?

DejaVu Sans for sans, DejaVu Serif for serif.

**Comment by wiiaboo** [comment]
Disabling wrapping would make osc list look like what wm4 implemented a few days ago, but not sure if this would make it useless to distinguish items:
![image](https://i.fsbn.eu/A51t.png)

Downscaling with fewer lines would temporarily fix this until you find large enough filenames again that it'd wrap to 3 lines for each item and then same problem.

**Comment by Coacher** [comment]
Long filenames are only a part of the problem.
Here's what happens with mpv-git @ 2493d9112 with `--no-config` after I shortened those video filenames: http://i.imgur.com/ziDXB4e.jpg
Compare to audio with cover art scaling: http://i.imgur.com/kaSaBHS.jpg
As you can see playlist scaling differs. OSC controls have the same scaling.

**Comment by wiiaboo** [comment]
Looks fine. What's the problem there?
The scaling changes depending on the number of lines. As is, it'll use osd-font-size until 7 items, then 80% of osd-font-size until 11 items, then no lower than 66% of osd-font-size. Number of max lines shown depends on osd-font-size as well.

**Comment by Coacher** [comment]
Ah, so the actual used font-size depends on the number of items in playlist?
Is there a way to tell mpv 'always use this font-size if you can fit playlist within the whole video area, scale only if playlist too big for the whole video area'?

**Comment by wiiaboo** [comment]
No, there's no way of knowing how much space the text occupies exactly. We wing it by assuming it won't wrap and X lines fit the screen.

**Comment by Coacher** [comment]
Ok, thank you for the explanation. I understand now what happens.
If you could improve behaviour with long lines, that would be great!
Having the same scaling with forced window would be nice, but it's ok if it stays at 2. It's easy to override.

**Comment by wiiaboo** [comment]
There's no 100% fix for this. You either delay the problem or make another one by not wrapping. What do you think is more reasonable other than telling people to just use a smaller osd-font-size?

**Comment by Coacher** [comment]
IMHO neither 'delay the problem', nor 'make another one by not wrapping' are clean solutions.
If mpv would just warn a user about what's happening with a hint towards 'osd-font-size', I wouldn't create this issue in the first place. Otherwise it looks just like smth is broken in OSC.

**Comment by Argon-** [comment]
>There's no 100% fix for this. You either delay the problem or make another one by not wrapping. What do you think is more reasonable other than telling people to just use a smaller osd-font-size?

Personally, I don't really like having a too small `osd-font-size` for the actual OSD "elements" (`osd-status-msg`) and therefore used to prefix stuff like `osc-playlist`, `osc-chapterlist` and `osc-tracklist` with a custom ASS sequence for smaller font size. However, this doesn't work anymore since these properties have own ASS styling.
Not sure how to circumvent this while retaining their formatting. Maybe two `osd-font-size`s?

**Comment by wiiaboo** [comment]
Fixed in  bcb2db0.

**Comment by cc978** [comment]
now, mpv 0.32 still too big fonts on playlist ....
settle it out with this third part script:
https://github.com/jonniek/mpv-playlistmanager
and set font with ASS like {\fnUbuntu\fs10\b0\bord1}, still do not know why the \q, wrap works incorrectly  @jonniek
