### ISSUE TITLE
EDL stream has unknown duration

### ISSUE THREAD

**Issue by Evidlo** [mpv-player/mpv#5156]
### mpv version and platform
Fedora 25
mpv 0.23.0 (C) 2000-2016 mpv/MPlayer/mplayer2 projects
 built on UNKNOWN
ffmpeg library versions:
   libavutil       55.28.100
   libavcodec      57.48.101
   libavformat     57.41.100
   libswscale      4.1.100
   libavfilter     6.47.100
   libswresample   2.1.100
ffmpeg version: 3.1.11

### Reproduction steps
    mpv --playlist='http://wdvx.stream.egihosting.com:8000/listen.pls'

After this, the stream plays for 1 second and exits with the message `EDL: source file xxxxxxx has unknown duration`

### Log file
[http://termbin.com/wd59](http://termbin.com/wd59)

**Comment by AstralStorm** [comment]
This is a bug in handling EDL entries with no length, specifically:
https://github.com/mpv-player/mpv/blob/8ebda75741e827823a8808a7ee084a9a81e91c17/demux/demux_edl.c#L276

In this case, since duration is actually infinite and offset is not given, we should end up with .start = 0 and .pts = 0 or -1 (anything that means "use from file")
Of course adding the offset if provided (0 otherwise just to use PTS from file.)

**Comment by wm4** [comment]
demux_edl isn't really designed to handle unknown lengths (and probably shouldn't).

The bug here is that ytdl.lua wraps this into EDL for no reason. Works with --no-ytdl. The script shouldn't even touch pls playlists.

**Comment by wiiaboo** [comment]
You can use this badly documented feature to exclude .pls from ytdl parsing: `--script-opts=ytdl_hook-exclude='%.pls$'`

**Comment by wiiaboo** [comment]
Should be fixed with https://github.com/mpv-player/mpv/commit/89f81da481c81cda1abd7c971b36f00ea80d80fe

**Comment by pabloab** [comment]
Not sure how to use [`on_load_fail`](https://github.com/mpv-player/mpv/commit/89f81da481c81cda1abd7c971b36f00ea80d80fe). I recently start to get this message but with `index.m3u8`, using `flatpak run io.mpv.Mpv --no-config --cache=yes --quiet --no-video --ytdl-format=best "https://youtu.be/jfKfPfyJRdk"` (mpv v0.37.0). `--script-opts=ytdl_hook-exclude='%.m3u8$'` didn't fix the issue (brings other worst errors). Should I file a new issue?
