### ISSUE TITLE
loop-playlist make to retry only 3 times on network issues

### ISSUE THREAD

**Issue by 532910** [mpv-player/mpv#5632]
### mpv version and platform

0.27.0-2 and 0.28.0-1 from debian sid and experimental

### Reproduction steps

```
wget https://somafm.com/groovesalad130.pls
# ifdown eth0
$ mpv --loop-playlist groovesalad130.pls
$ mpv groovesalad130.pls
```

### Expected behavior

with ```--loop-playlist``` mpv must loop playlist _forever_

### Actual behavior

```--loop-playlist``` changes nothing

### Log file
https://0x0.st/samL.log

**Comment by wm4** [comment]
Why do people keep skipping the issue template? It's there for a reason.

**Comment by c-e-p-x-u-o** [comment]
I have fixed, please remove 'ignored issue template'

**Comment by 532910** [comment]
Is it fixed?

**Comment by zc62** [comment]
That is not a mpv log file at all.

**Comment by sfan5** [comment]
0x0 has deleted your log file in the meantime.
Have you verified that your bug is not fixed with 0.29?

**Comment by 532910** [comment]
> That is not a mpv log file at all.

It was a year ago. The suggested 0x0.st overrides my log.

**Comment by 532910** [comment]
> Have you verified that your bug is not fixed with 0.29?

Yes, I've verified, it's not fixed.

**Comment by 532910** [comment]
```
% mpv --loop-playlist groovesalad130.pls
Playing: groovesalad130.pls

Playing: http://ice2.somafm.com/groovesalad-128-aac
[ffmpeg] tcp: Failed to resolve hostname ice2.somafm.com: Temporary failure in name resolution
Failed to open http://ice2.somafm.com/groovesalad-128-aac.
[ytdl_hook] ERROR: Unable to download webpage: <urlopen error [Errno -3] Temporary failure in name resolution> (caused by URLError(gaierror(-3, 'Temporary failure in name resolution')))
[ytdl_hook] youtube-dl failed: unexpected error ocurred 

Playing: http://ice4.somafm.com/groovesalad-128-aac
[ffmpeg] tcp: Failed to resolve hostname ice4.somafm.com: Temporary failure in name resolution
Failed to open http://ice4.somafm.com/groovesalad-128-aac.
[ytdl_hook] ERROR: Unable to download webpage: <urlopen error [Errno -3] Temporary failure in name resolution> (caused by URLError(gaierror(-3, 'Temporary failure in name resolution')))
[ytdl_hook] youtube-dl failed: unexpected error ocurred 

Playing: http://ice1.somafm.com/groovesalad-128-aac
[ffmpeg] tcp: Failed to resolve hostname ice1.somafm.com: Temporary failure in name resolution
Failed to open http://ice1.somafm.com/groovesalad-128-aac.
[ytdl_hook] ERROR: Unable to download webpage: <urlopen error [Errno -3] Temporary failure in name resolution> (caused by URLError(gaierror(-3, 'Temporary failure in name resolution')))
[ytdl_hook] youtube-dl failed: unexpected error ocurred 


Exiting... (Some errors happened)
zsh: exit 3     mpv --profile=$HOST --loop-playlist groovesalad130.pls
```

**Comment by garoto** [comment]
so you want to loop a playlist `inf` over a network error?

**Comment by 532910** [comment]
Yes.

**Comment by 532910** [comment]
In fact I'm looking for a way to listen to internet radio despite network issues.
And the only one I've found is ```while true; do mpv --network-timeout=2 URL; done```

But ```--loop-playlist``` should loop playlist infinitely, as described.

**Comment by zc62** [comment]
In order to loop errors, you need to use `--loop-playlist=force`, as very clearly described in the manual: https://mpv.io/manual/master/#options-loop-playlist
> The force mode is like inf, but does not skip playlist entries which have been marked as failing. This means the player might waste CPU time trying to loop a file that doesn't exist. But it might be useful for playing webradios under very bad network conditions.

**Comment by 532910** [comment]
@zc62, thank you! Is `force` new for 0.29 or I've missed it in 0.28-0.27?

**Comment by zc62** [comment]
It was introduced in 2015: https://github.com/mpv-player/mpv/commit/aee0978d50e21d8f114382fdb9c014c029f71a04. (`loop-playlist` was called `loop` at that time, then changed in https://github.com/mpv-player/mpv/commit/6dea8fceda981481798f6f492db54c6fd8708c3b.)

**Comment by kentherzz** [comment]
Still MPV skips very quickly files on a playlist that has network issues. Is there a way to keep MPV on the same file and constantly trying to open it, like VLC does....?

**Comment by wm4** [comment]
Other than invoking mpv in a loop, I don't think so.

**Comment by kentherzz** [comment]
What exactly is VLC doing when it has been set to repeat this one file? It is constantly on the same file and never skips, no matter what happens on the network. This behaviour is what we need on MPV as well... Im really surprised that this hasn't been implemented yet.

**Comment by kentherzz** [comment]
I think a "loop-file=force" option will do exactly what I'm describing.

**Comment by wm4** [comment]
Jesus Christ. The mpv behavior was implemented to NOT to endlessly burn CPU or whatever if the playlist has nothing playable. This kind of pisses me off so bye.
