### ISSUE TITLE
Videotoolbox fails when seeking

### ISSUE THREAD

**Issue by sovon** [mpv-player/mpv#5893]
### mpv version and platform
MPV 0.28.2 on macOS High Sierra 10.13.5

If you're not using git master or the latest release, update.
Releases are listed here: https://github.com/mpv-player/mpv/releases

### Reproduction steps

Valerian and the City of a Thousand Planets 4K from rutracker

Mediainfo - https://pastebin.com/ztBPfacQ

### Expected behavior

The hwdec should keep working, I guess.

### Actual behavior

After opening the file from terminal or application, if I drag (mouse click) on the timeline in screen controls, it fails hardware decoding and goes back to software method hence dragging down the battery of laptop with it.

### Log file

https://pastebin.com/dNCAYZhq

Providing a log file is strongly encouraged. It is very helpful for reproducing
bugs or getting important technical context. Without a log it might not be
possible to analyze and fix certain bugs, and your bug report will be closed
or ignored.

### Sample files

Sample files needed to reproduce this issue can be uploaded to https://0x0.st/
or similar sites. (Only needed if the issue cannot be reproduced without it.)
Do not use garbage like "cloud storage", especially not Google Drive.

**Comment by Akemi** [comment]
might be related to #5755, #5741 and/or #5609. @tmm1 suggested a few fixes on issue #5755, though we never got a confirmation if the last proposed fix worked. it's most likely a ffmpeg problem.

**Comment by Akemi** [comment]
a verbose log with `-v` or `--log-file=FILE` would be helpful, to at least know which ffmpeg you are using. some changes landed into ffmpeg recently that are hevc/videotoolbox related.

**Comment by sovon** [comment]
Here is the details log. It fails around the end.

https://pastebin.com/1gX5V64X

**Comment by Akemi** [comment]
try with a more recent ffmpeg version. your version is from 12th february, the fixes landed after that into ffmpeg.

**Comment by sovon** [comment]
I already had ffmpeg 4.0 installed. But mpv seems to be built with a version from Feb-14 2018. Anyways I installed mpv from brew with --HEAD and it shows the current version of ffmpeg is 4.0.

However the problem persists. here is the log. https://pastebin.com/18fG2imf

And weird. If I open the movie file from terminal mpv command, there is this blue flicker al over the place. This doesn't happen if I open from context menu. hardware still fails on both of the cases for OSC click drag.

**Comment by Akemi** [comment]
the related videotoolbox changes didn't make it into ffmpeg 4.0, it's only in master.

mpv from master uses a new rendering backend by default, so the blue flickering might be unrelated. try with `--vo=gpu` for testing and see if the flickering occurs there too. if no it's an unrelated problem, if yes it might be related.

**Comment by sovon** [comment]
Yep. The flicker is there. Tried with vo=gpu and vo=libmpv

**Comment by Akemi** [comment]
just to make sure, if it also happens with `--hwdec=no` it's unrelated and you should open another issue for the flickering.

if you could try with ffmpeg master too that would be nice.

**Comment by sovon** [comment]
I did try with hwdec option as well. I didn't do --hwdec=no. I just left that hwdec option out. I believe it defaults to no cause it's software decoding.

I'd definitely try with ffmpeg master if you can tell me how to do that.

**Comment by Akemi** [comment]
same as when you built mpv from master just with `brew --HEAD`.

so you had the blue flickering with `--hwdec=no` too?

**Comment by sovon** [comment]
ffmpeg and mpv both on --HEAD.

--hwdec=videotoolbox hardware fails & no blue flickering ( https://pastebin.com/6LxbsH49 ) 

--vo=gpu no flicker but hardware fails ( https://pastebin.com/K7M6ttD1 )

The hardware decoding fails only when I click on the OSC timeline. So frustrating. :(

**Comment by Akemi** [comment]
at least the blue flickering is gone, that's good.

try with `--vd-lavc-software-fallback=no` for testing. also a small sample of the video might be helpful. `dd if=IN_FILE of=OUT_FILE bs=1024 count=100000` to make a ~100MB sample file. make sure it works and the issue can be reproduced with.

**Comment by tmm1** [comment]
The blue flickering issue is a known bug in ffmpeg 4.0's videotoolbox
driver and has been fixed on ffmpeg master. It has also been cherry picked
to the 4.0 release branch for the next 4.x release.

**Comment by sovon** [comment]
I ran this command couple of times.

dd if=/Users/red/Downloads/In\ the\ Fade\ \(2017\)\ \[1080p\]\ \[YTS.ME\]/In.the.Fade.2017.1080p.BluRay.x264-\[YTS.ME\].mp4 of=abc.mp4 bs=1024 count=100000

But the output file turns out invalid. It's this file: https://rutracker.org/forum/viewtopic.php?t=5500402
(Puts on tinfoil hat) I don't do piracy.

And with software fallback option disabled, the CPU spike is gone. The errors of audio-video sync is there but it doesn't go back to software decode when it fails. This is good. Why isn't this a default setting? I'm adding this to my config file. Anywho, here is the log: https://pastebin.com/xdxAX50p

**Comment by Akemi** [comment]
yeah probably needs a bit more than just 100MB to work.

it's not the default because it could break in the case where hardware decoding can't recover at all. also hardware decoding isn't default and we don't really recommend it. using a number for `--vd-lavc-software-fallback=N` (default: 3) is a bit safer. it will try to recover N times and only fall back then.

**Comment by Akemi** [comment]
i uploaded a short sample [here](https://0x0.st/s_ge.mkv) (~1 minute). can you confirm that it works and you can reproduce the issue?

also in your comment before it seems like you tried to cut a different sample than the one you were having problems with.

**Comment by sovon** [comment]
Yeah, but I thought you might notice that. I tried with the main file in discussion at first. It didn't work. Then I tried with other files, also didn't work.

Anyways, here is the log for the file you shared. I can't believe you downloaded the entire movie for this tiny purpose only. :) I thank you for your time and effort in solving this.

Log: https://pastebin.com/NGvTBt5q

The problem is there. The timeline showed entire two hours in OSC so it was a bit difficult to drag within one minute but random clicks within first one minute of the timeline triggered the failure. No flicker but hardware fails.

**Comment by sovon** [comment]
This is happening with another film now.

Another UHD 4K blu-ray Superman Man of Steel. A 78GB stream. :(

**Comment by Akemi** [comment]
since we have a working sample file maybe @tmm1 can have a look at it now.

**Comment by sovon** [comment]
I thank you again for al your efforts in helping me. Just a question.

It's not because my hardware is slow right? Cause I just bought this laptop, 2017 MBP TB which has HEVC decoder in CPU chip. Kaby lake.

**Comment by Akemi** [comment]
nah it's not because of slow hardware. the hevc hw decoder in macOS is rather new still, so it's most likely a software problem.

**Comment by sovon** [comment]
I hope so. Eagerly waiting for a fix although I'm not sure how long it might take for  you guys.

**Comment by sovon** [comment]
Any update ? ☹️

**Comment by pxia** [comment]
I just tested with the ffmpeg 4.1, the issue still exists.

**Comment by bzq2810** [comment]
Just wondering that if anyone has found the solutions for this issue.

When I play the HEVC m2ts file from a UHD disc. The hardware acceleration only failed after manually seeking as others described. This issue exists on my new mac mini with i7-8700B (only Intel GPU UHD630) but not for my old MacBook Pro with additional Nvidia GT750M GPU card.

I find a temporary workaround that after I remux the m2ts into the mkv file, the problem is fixed. However, I hope that the issue can be fixed for the m2ts file.

**Comment by Akemi** [comment]
ffmpeg issue https://trac.ffmpeg.org/ticket/8732#ticket
