### ISSUE TITLE
--geometry doesn't position the window correctly

### ISSUE THREAD

**Issue by zubieta** [mpv-player/mpv#6453]
### mpv version and platform
* mpv 0.29.1
* macOS High Sierra 10.13.6
* Displays:
  + DELL P2717H 27-inch (1920 x 1080)
  + Built-in display 15.4-inch (2880 x 1800)

### Reproduction steps
1. You need a dual monitor setup (probably with different resolutions for the displays, I'm not completely sure)
2. Run mpv in the terminal like this: `mpv --ytdl-format=bestvideo+bestaudio --geometry=20%x20%+100%+100% --screen=1 <YOUTUBE_URL>`

### Expected behavior

mpv opens a small window that is `20%x20%` of the screen size, positioned in the bottom right corner of the external display (the one with lower resolution).
![expected](https://user-images.githubusercontent.com/25016815/51509962-af17a700-1dc0-11e9-9aa0-0f5f932d5357.png)

### Actual behavior
mpv opens the window with the right size  at the bottom of the external display but not in the right corner.

![actual](https://user-images.githubusercontent.com/25016815/51509935-93140580-1dc0-11e9-9da5-7850c50f0ef6.png)

### Log file
https://0x0.st/sFB3.log

### Extra context
I have this display arrangement but I'm not sure if that could influence the issue.
![arrangement](https://user-images.githubusercontent.com/25016815/51510241-ef2b5980-1dc1-11e9-8210-f2cca175e245.png)

**Comment by Akemi** [comment]
apparently apple changed the behaviour of the window [init function](https://developer.apple.com/documentation/appkit/nswindow/1419755-init), the contentRect is no longer completely relative to the provided screen anymore but the main screen (the one with the menu bar). setting an x/y origin smaller than the main screens width/height kinda works.

tested this in a minimal test in playground/xcode and there i can reproduce the same behaviour/error. tbh this is kinda ridiculous and i am pretty sure on 10.12 it worked properly, since i tested it there thoroughly. though no worries i will fix it.

**Comment by zubieta** [comment]
What I don't yet understand about your finding is why if I'm passing the screen id I still get the incorrect behavior.

As I understand the docs, if the screen id is not passed (`nil`) the origin of the coordinates corresponds to the screen with the menu bar, but if it is passed then the origin should correspond to the given screen as expected. Or is my understanding is incorrect?

And yes, I believe it was working correctly before the last update.

**Comment by Akemi** [comment]
no you didn't misunderstand our docs. what i am saying, Apple's provided API to create a window is broken (got broken) and its behaviour doesn't correspond to its documentation. from my tests it can only place windows correctly if they fall within the relative screen bounds of the main screen.

**Comment by zubieta** [comment]
Oh! I see now. Thanks for the explanation. Do you know how to open an issue against apple API or docs? Otherwise, I can search and do it.

**Comment by Akemi** [comment]
bug should be fixed with #6466. it's just a very dumb workaround for a problem that shouldn't exist in the first place. i also opened a bug report at Apple.

my findings can be found [here](https://github.com/Akemi/test_secondary_screen_window_position).

**Comment by zubieta** [comment]
Thanks a lot @Akemi. I just tried it and can confirm that it solves the issue.

**Comment by Akemi** [comment]
good to hear. thanks for testing.

**Comment by krlklm** [comment]
Is this fixed in the current Homebrew version of mpv (0.29.1_3)? Or would I have to compile it somehow on my own?

**Comment by Argon-** [comment]
What you are looking for is `--HEAD`

**Comment by krlklm** [comment]
This is probably too complicated for me. Hopefully the PR will be merged to the HEAD version soon. Thanks!

**Comment by StareInTheAir** [comment]
I'm afraid this bug is back. I'm running mpv 0.33.0 on macOS Big Sur 11.2.2 on an M1 MacBook Air. I have an 4k TV attached and the geometry option only works correctly if I make the 4k monitor my main display. If my internal 13.3" screen is the main display, I experience the same problems as initially described here.

**Comment by Akemi** [comment]
i am going to repeat myself like every time in such cases.

please don't comment on old closed issues. it's very unlikely that anyone will or can help you like this. this will not get your issues fixed. please open a proper issue and provide all infos we ask for if you want your problem to be fixed.

your issue is most likely not related to this one, since the fix is still in place it's more likely that apple broke something else again.
