### ISSUE TITLE
Feature request: transparent background (not just black)

### ISSUE THREAD

**Issue by daT4v1s** [mpv-player/mpv#6590]
example situations:
- playing audio with subtitles `.SRT` `.VTT` `.ASS` (allow to use window as overlay) with 
  **opaque** subtitles
    - with completely transparent or semi-transparent-black background
- playing custom rendered/composited RGBA videos 
   or any video with opacity/alpha channel (YV12+A)

(also nice if possible to make most of the window (non-OSD-GUI) click-through

**Comment by CounterPillow** [comment]
>playing custom rendered/composited RGBA videos
or any video with opacity/alpha channel (YV12+A)

Exists and is called `--alpha=yes`.

**Comment by daT4v1s** [comment]
apparently it does not work with linux, 
i've seen examples via wine [apps](https://www.softpedia.com/get/Multimedia/Graphic/Image-Convertors/Animated-Transparent-Jpeg-Maker.shtml) that do true-transparency
thus it is possible in linux

**Comment by wm4** [comment]
It's possible, but Mesa broke it. The mpv manpage even mentions the Mesa bug number.

**Comment by benjaminBrownlee** [comment]
I noticed that the referenced EGL Mesa bug ([67676](https://bugs.freedesktop.org/show_bug.cgi?id=67676)) is now resolved. Any update on this implementation? It still does not work on my machine.

**Comment by guidocella** [comment]
It seems that the merge request that closed the bug was reverted and now https://gitlab.freedesktop.org/mesa/mesa/-/merge_requests/2376 has to be merged.

**Comment by wm4** [comment]
I can try to look at it once all affected components have made it to something I can use and install. Is there any distro which has these changes yet? (Obviously I won't go too much out of may way for this.)

**Comment by wm4** [comment]
Also I think Mesa forgot to write the EGL_MESA_config_select_group specification.

**Comment by wm4** [comment]
OK, after looking some, the things mentioned above were reverted in Mesa. So this still can't be fixed. Blame Mesa.

**Comment by wm4** [comment]
It turns out that you can circumvent the mess with another (existing mess) - it's fixed now on X11.

**Comment by benjaminBrownlee** [comment]
Sweet, I guess I'll download the `mpv-git` AUR pkg and test it out. Thanks for your help!

**Comment by guidocella** [comment]
Any chance of making the alpha component affect `--background`?

**Comment by SaphiraKai** [comment]
I'm still having issues with this on Linux with X11, playing an RGBA video with `mpv --alpha=yes test.mov` and `mpv --alpha=yes --background=00000000 test.mov` both yield a solid black background. And yes I do have a compositor running

**Comment by Dudemanguy** [comment]
That's because it's still broken in Mesa. The commit that originally closed this issue may have possibly worked at the time as some weird hack, but it definitely doesn't work right now.

**Comment by cipricus** [comment]
There is the option to add a transparency value before the 6-digit hex number. Here is a list with all the transparency values ([souce](https://gist.github.com/lopspower/03fb1cc0ac9f32ef38f4#all-hex-value-from-100-to-0-alpha): here):

    100% — FF
    99% — FC
    98% — FA
    97% — F7
    96% — F5
    95% — F2
    94% — F0
    93% — ED
    92% — EB
    91% — E8
    90% — E6
    89% — E3
    88% — E0
    87% — DE
    86% — DB
    85% — D9
    84% — D6
    83% — D4
    82% — D1
    81% — CF
    80% — CC
    79% — C9
    78% — C7
    77% — C4
    76% — C2
    75% — BF
    74% — BD
    73% — BA
    72% — B8
    71% — B5
    70% — B3
    69% — B0
    68% — AD
    67% — AB
    66% — A8
    65% — A6
    64% — A3
    63% — A1
    62% — 9E
    61% — 9C
    60% — 99
    59% — 96
    58% — 94
    57% — 91
    56% — 8F
    55% — 8C
    54% — 8A
    53% — 87
    52% — 85
    51% — 82
    50% — 80
    49% — 7D
    48% — 7A
    47% — 78
    46% — 75
    45% — 73
    44% — 70
    43% — 6E
    42% — 6B
    41% — 69
    40% — 66
    39% — 63
    38% — 61
    37% — 5E
    36% — 5C
    35% — 59
    34% — 57
    33% — 54
    32% — 52
    31% — 4F
    30% — 4D
    29% — 4A
    28% — 47
    27% — 45
    26% — 42
    25% — 40
    24% — 3D
    23% — 3B
    22% — 38
    21% — 36
    20% — 33
    19% — 30
    18% — 2E
    17% — 2B
    16% — 29
    15% — 26
    14% — 24
    13% — 21
    12% — 1F
    11% — 1C
    10% — 1A
    9% — 17
    8% — 14
    7% — 12
    6% — 0F
    5% — 0D
    4% — 0A
    3% — 08
    2% — 05
    1% — 03
    0% — 00

So, to play mpv with a 80% transparency of a black subs background: `mpv  --sub-back-color=#CC000000 video.mp4`

**Comment by iiiGerardoiii** [comment]
that's cool @cipricus , but I think this bug is about trying to achieve full transparency of the video itself, not the subtitles.

e.g. opening a .png image of a circle and the corners of the image are showing whatever is behind the window, instead of a checkerboard pattern.

**Comment by cipricus** [comment]
> that's cool @cipricus , but I think this bug is about trying to achieve full transparency of the video itself, not the subtitles.
> 
> e.g. opening a .png image of a circle and the corners of the image are showing whatever is behind the window, instead of a checkerboard pattern.

Sorry, I must have misunderstood. Too eager to share !

**Comment by wick3dr0se** [comment]
@iiiGerardoiii even though @cipricus misunderstood, a valid point was made.. Hex accepts opacity and that means it should work fine. And it does!

`mpv FILE --background=#00000000 -- alpha=yes`

**Comment by digitalsignalperson** [comment]
thanks @wick3dr0se, confirmed here `--background=#00000000 --alpha=yes` working with a mpv wayland window and a `.mov` with transparency

**Comment by iiiGerardoiii** [comment]
> @iiiGerardoiii even though @cipricus misunderstood, a valid point was made.. Hex accepts opacity and that means it should work fine. And it does!
> 
> `mpv FILE --background=#00000000 -- alpha=yes`

wtf @cipricus was right all along

I stand corrected.

**Comment by birdguy-cs** [comment]
how do you do this now? as the api seems to have changed or something similar

**Comment by guidocella** [comment]
`--background=none --background-color=0/0`

It also needs `--gpu-api=opengl` on Xorg and `--d3d11-flip=no` on D3D11.

**Comment by kasper93** [comment]
`--background=none` is dangerous, because it will leave previous contents on the frame, `--background=color` should be used.

**Comment by na-na-hi** [comment]
> `--background=none` is dangerous, because it will leave previous contents on the frame

This is not true, according to documentation it should just leave the alpha on image as is, and there is no blending of previous contents on the frame. And it also causes no issues in practice.

**Comment by kasper93** [comment]
> > `--background=none` is dangerous, because it will leave previous contents on the frame
> 
> This is not true, according to documentation it should just leave the alpha on image as is, and there is no blending of previous contents on the frame. And it also causes no issues in practice.

I meant `--border-background=none`, my bad.
