### ISSUE TITLE
Demuxer cache is reading slowly from remote mounts, stream cache much faster

### ISSUE THREAD

**Issue by Marco01809** [mpv-player/mpv#6802]
### mpv 20190707-git-c379950 64bit (shinchiro builds) on Windows 10

Can also be reproduced using **20190316-git-dd83b66**, the first version after stream cache removal.
Issue is not present in **20190310-git-1d0349d**, which is the last version to still include the stream cache.

### Reproduction steps

1. Mount a filesystem that is backed by remote storage, specifically over the internet with high latency, but enough bandwidth. 
	* I used SSHFS to mount from a server with 55ms ping. Copying files from that SSHFS mount shows a stable ~2.9 MB/s read speed.
2. Run `mpv --no-config --cache=yes --cache-secs=30 --pause --vo=null file/from/that/mount.mkv`
	* (`--vo=null` is not relevant to the reproducability of this issue)
	* The file I'm testing with has a ~3mbps (=0.375 MiB/s) average total bitrate.

### Expected behavior

Since bandwidth >> bitrate, the cache should fill up quickly. Real-time playback should work without any lags.

**Note:** This is the actual behavior when using mpv builds <= 2019-03-10. That version specifically builds up the cache at a rate of ~1.0 MiB/s and fills up the 30 seconds in around 9 seconds.

### Actual behavior

Demuxer is reading the file very slowly, building up the cache at a rate of only ~60 KiB/s. Filling up the 30 seconds takes around 140 seconds. Real-time playback is impossible.

Playing back local files (from an SSD) works fine, the cache fills up much faster than realtime, even with bitrates as high as 140mbps.

### Log file

Log of running the above command on mpv 2019-07-07 is available on https://0x0.st/z9PG.log, but it doesn't seem to contain anything useful. mpv was closed after 30 seconds cache filled up.

### Sample files

(Does not apply.)

**Comment by petersenj** [comment]
I'm not sure restoring the stream cache alone is a good solution let alone necessary; I've done some more testing with mpv-20190707 because the 1.0 MiB/s rate seen with the old stream cache on 20190310 is also much too low.

Piping from ssh directly using `ssh <remote> "cat file.mkv" | mpv ... -` yields a cache rate of ~3.6 MiB/s (which happens to saturate the internet connection).

Streaming using HTTPS from the same server with `mpv ... https://<remote>/file.mkv` also saturates the connection at 3.6 MiB/s.

So that opens up the question what kind of reads mpv does on filesystems that give SSHFS such trouble keeping up (whereas a simple sequential read gives much higher rates). Potentially there are some improvements to be made to sshfs/sshfs-win to remedy this problem as well.

**Comment by petersenj** [comment]
I've dived a bit into mpv's source to figure out what determines the size of the reads mpv does and I've found a solution that doesn't require the stream cache on latest mpv (20190714 as of now).

With `--demuxer=+lavf --demuxer-lavf-buffersize=4194304` cache rate is *much higher*, on par with sequential read speed, effectively saturating the internet connection.

Using the lavf:// stream adapter (and keeping the mkv demuxer) also helps a lot (but is still much slower and can just barely play that 3mbps file in realtime).

**Comment by wm4** [comment]
So what cause did you make out? Many small reads? Seeks? One of those has to trigger it somehow.

**Comment by Marco01809** [comment]
I _suspect_ it's too small reads combined with bad readahead/caching from sshfs-win. VLC performs pretty much the same as mpv + lavf demuxer.

Quick test I ran just now with latest shinchiro and stock demuxer settings:
file copy: ~2000 KiB/s
mpv + webm/mkv file: ~60 KiB/s cache speed
mpv + mp4 file: ~250-350 KiB/s cache speed
mpv + webm/mkv + demuxer=lavf + 2MB buffersize: ~2000-2600 KiB/s cache speed
VLC 3.0.8 + webm/mkv/mp4 file: ~150-350 KiB/s cache speed (as per Codec Information -> Statistics -> Input birate)

One could argue that mpv isn't at fault here to expect the underlying filesystem to readahead/cache the file, but with some kind of stream cache it would probably be way more robust to help with cases like this.

**Comment by Marco01809** [comment]
Related: https://github.com/billziss-gh/sshfs-win/issues/104

**Comment by wm4** [comment]
Just demuxing mkv typically doesn't seek. It may seek to the end and back on opening, depending on the file. So it must be due to small reads. mpv by default reads only in 2 KB blocks, but may read more in one call if media packets are larger.

How large is the ideal read block size in this case?

**Comment by Marco01809** [comment]
I don't know the actual size of the reads the lavf demuxer does, but setting demuxer-lavf-buffersize to 1MB is just enough to hover around 30mbps throughput. Seeks on remote files are somewhat sluggish, local files are still fine. With 2MB the connection is saturated consistently, but seeking takes several seconds on remote files, and even on local files seeks seem a bit less responsive.

**Comment by wm4** [comment]
Try this branch: https://github.com/mpv-player/mpv/tree/stream_shit
It has a --stream-buffer-size option.
Be careful with it, it's unstable enough that I didn't dare to push it to git master.

**Comment by Marco01809** [comment]
That seeems to perform quite well. I've tried with several mkv and mp4 files and didn't hit any bugs.

Quick cache speed tests with an mkv file:
--demuxer=lavf: ~350 KB/s
--demuxer=lavf --demuxer-lavf-buffersize=1048576: ~2500 KB/s
--demuxer=lavf --demuxer-lavf-buffersize=2097152: ~2900 KB/s
(nothing): ~30 KB/s
--stream-buffer-size=1MiB: ~2100 KB/s
--stream-buffer-size=2MiB: ~2600 KB/s
--stream-buffer-size=4MiB: ~3000 KB/s

Seek duration in remote files is similiar no matter the buffersize, but lavf generally restarts playback considerably faster. I think that's due to the mkv demuxer, not the stream cache implementation, because --demuxer=lavf --stream-buffer-size=2MiB performs just as well as (if not slightly better than) --demuxer=lavf --demuxer-lavf-buffersize=1048576.

**Comment by wm4** [comment]
>  but lavf seeks considerably faster (0,5-1,5s). I think that's due to the mkv demuxer,

Does this happen on all seeks, or only when seeking to regions that have not been demuxed yet? Does --index=recreate change anything with the internal mkv demuxer? (That will download all data until the seek target though.)

**Comment by Marco01809** [comment]
Seeks within demuxed regions are instant with both mkv and lavf. --index=recreate only has a visible impact on seeks outside demuxed regions in that it takes significantly longer (as expected).

I've tried with other mkv files and I think it's not as much about speed but rather consistency. lavf consistently seeks in ~1s, while mkv takes anywhere between 1-3s. It's not that big a deal anyway, mkv demuxer is still good enough.

**Comment by wm4** [comment]
libavformat has an internal index for every packet it has read since opening the file (even if the packet data itself is not available anymore). So for regions already demuxed, seeks could be faster, even if the data is not in any of the caches anymore. Moreover, lavf probably does not read the file's index (usually located at the end of the file for mkv), while mpv's demuxer always reads this index on the first seek (unless the seek is within mpv's demuxer cache).

Anyway, there's no fundamental reason why lavf would be faster here. But maybe it's one of the corner cases that makes mpv perform less efficient reads.

I've pushed more to the branch and added the following debugging options:

- ``--stream-seek-threshold=<bytesize>``: control the seek distance after which it performs a raw seek instead of skipping data on forward seeks (default is 0, which is a magic value that is replaced with the --stream-buffer-size value)
- ``--stream-shadow-buffer=<yes|no>``: always perform low level read calls with the full size possible (instead of allowing shorter calls because of the ringbuffer), default is "no"
- ``--stream-log-debug=<yes|no>``: if set to yes, logs every low level read and seek call
- ``--stream-force-buffer=<yes|no>``: always go through the read buffer, instead of allowing read calls larger than the buffer size to side step the buffer, default is "no"

Would be great if you could play with these and determine the optimal parameters. Then we might see what is going on.

**Comment by Marco01809** [comment]
I didn't have time to test very thoroughly (and I only have small time windows to test this when I'm not home, because I can't recreate the shitty performance of the peering between two ISPs). Tested e103f629aba9aeb4442b867360ff8f28c3f4dd25 using one ~3mbps mkv file and stream-buffer-size=4MiB (the smallest ^2 that still shows significant throughput improvements).

Not sure about stream-seek-threshold, it seems to have the same effect as --index=recreate and could only potentially improve small relative seeks. Didn't really test with it.

Neither lavf nor mkv demuxer seem to be influenced by shadow or force at all. The first read after a seek is always equal to the buffer-size, and all reads afterwards are half the buffer size (This equally applies to precise/relative seeks and whether or not it seeks into an already demuxed region). When opening the file, both demuxers once seek to the end of the file, then back. The only difference I can see is that on the first seek, lavf once again seeks to the end, then back, but it never does that again.

Logs of me opening the file, performing 3 +1min seeks, each after playback resumed:
- [demuxer=mkv force=no shadow=no](https://0x0.st/zg1L.log)
- [demuxer=mkv force=yes shadow=yes](https://0x0.st/zg19.log)
- [demuxer=lavf force=no shadow=no](https://0x0.st/zg1O.log)
- [demuxer=lavf force=yes shadow=yes](https://0x0.st/zg1f.log)

**Comment by wm4** [comment]
Thanks for the feedback. I will have a closer look at this later. Feel free to perform more tests if you can. The preliminary result that force/shadow do not help is good though, because that was much more messy to implement than without.

**Comment by wm4** [comment]
OK, looked at it closer. The "seek request" logging was a bit useless, because it logs the underlying position as "from" value (the position the end of the buffer points to), and the logical pos as "to" value (the demuxer pos, which can be within the buffer), which is also why it looks like it's seeking back all the time.

The mkv demuxer has many small seeks because there are disabled streams, so it uses seeks to jump over the packets. I think there's some mess-up in the code here, since normally this should use the skipping code directly, while according to the log, it goes through stream_seek, and then skips anyway instead of doing a low level seek (in theory they should be the same condition, but one of them doesn't take the buffer offset into account). In any case, neither results into an actual seek, so it doesn't affect network performance.

The lavf demuxer has its own buffer (the one which you use in your third post to workaround the problem without my branch). I'm not exactly sure what it's trying to do when skipping unneeded packets (does it read them and then discard then? does it seek?), but mpv's stream layer doesn't see any of this. If it seeks, lavf's default buffer size must be large enough.

So in summary, the debug options do nothing because the configured buffer size is large enough anyway.

I've noticed that mpv's demuxer needs 1.5 seconds longer to print the stream list (the one you see in the terminal) than libavformat's.  Both seek to the end of the file and then back before this is printed. I think this is because mpv reads at least a packet before handing back control to the player, while lavf returns immediately, and in exchange lavf needs more time to read the first package when actual demuxing starts? The filesystem seems to respond to seeks immediately, probably makes sense for a network FS.

The first manual seek you issue seems to have rather similar performance (even though lavf seeks to the end of the stream again, while mpv doesn't).

(Some more blabla about theoretical performance: the filesystem doesn't seem to do short reads. That makes perfect sense, because the file access API of Windows and UNIX don't allow that, even if the filesystem is a network FS. Slightly unfortunate, it could lead to playback pauses in certain cases that might be unavoidable. Using some sort of library would be better...)


OK, I wrote a lot of text, but I'm still not sure what to do. I could just push the change (without the debug additions), but then the user would still have to tune this manually.

Also, can you make a log with the default buffer size, and mpv/lavf demuxers? No need for a manual seek or trying the other debug options.

**Comment by Marco01809** [comment]
For the record: All measurements so far were done with sshfs-win.

- [demuxer=mkv buffer-size=default @ sshfs-win]()
- [demuxer=mkv buffer-size=default @ sshfs-win]()
- [demuxer=mkv buffer-size=default @ sshfs-win]()

I can make logs over the slow connection with sshfs-win and sshfs on linux the saturday.

**Comment by wm4** [comment]
Thanks for your tests, that's very useful. I think the sshs-win people need to improve the performance of their drivers. Regardless of that, it would probably do no harm bumping the default buffer size to 128 KB, or maybe adding a "network stream" heuristic for a larger default buffer size again.

Seek performance should be testable by using the time difference between the point when the demuxer executes the seek, and the first byte block is read after the seek. Since the driver seems to delay the seek until the first read, this first read needs to be taken into account.

**Comment by wm4** [comment]
I pushed something similar to master. Though it feels like I should just have said "no", since sshfs-win is obviously quite broken, and doesn't justify all this effort and possible fallout. Anyway.

**Comment by wm4** [comment]
I guess it can stay this way. I don't think the new default buffer size is causing any problems anywhere. Closing.
