### ISSUE TITLE
v0.30.0 caching remote video files very poorly, constantly freezing with 0-1s cache reported

### ISSUE THREAD

**Issue by hart0** [mpv-player/mpv#7152]
### mpv version and platform
 
Fedora Linux (30 and 31)
 
> mpv --version
mpv 0.30.0 Copyright © 2000-2019 mpv/MPlayer/mplayer2 projects
 built on UNKNOWN
ffmpeg library versions:
   libavutil       56.31.100
   libavcodec      58.54.100
   libavformat     58.29.100
   libswscale      5.5.100
   libavfilter     7.57.100
   libswresample   3.5.100
ffmpeg version: 4.2.1
 
### Problem details
 
After updating to mpv 0.30.0 on Fedora 30, as well as after installing a fresh install of the new Fedora 31, mpv will not play any remote video, regardless of size/resolution/format from my local network's samba server (mounted locally on my laptop via "mount -t cifs ..." - so essentially the server appears to be part of the local filesystem to the applications) without freezing for large amounts of time waiting for the cache to catch up or get ahead. Eg, 2 seconds of video play, 2 seconds of pausing, then 2 more seconds play unless I pause the video and wait long periods of time for it to load more into cache.
 
The caches increase by anywhere from 30kb/s to 1-2mb/s, depending on the size/bitrate of the video in question. Essentially, not even a low res small video file is able to be played without freezing every few seconds, and the issue seems to be even more exacerbated the larger file/bitrate is.
 
This isn't a network issue, I have made no changes to the samba server, or the network, haven't changed any mpv settings, and have no issues copying files to/from the server at ~30MB/s. Videos play fine with no freezing on vlc, and play fine and immediately cache large portions/amounts of time when I test via an appimage of mpv version 0.29.1. Eg, on 0.29.1, a small video will instantly load the whole thing as cache, and large 1080p/2160p videos will instantly load 10-20 seconds ahead at a time.
 
I have also tried adding "cache=yes" and "cache-secs=10" to the mpv config, which didn't change anything. Running in verbose mode with --v doesn't show any kind of error messages when it's freezing and loading more into the cache.
 
### Video demonstrating problem
 
Here is a video showing what happens when I load the same small, low bitrate video into mpv 0.30.0 (left, freezing, won't cache ahead) and 0.29.1 (right, instantly caches the entire video, no freezing)
 
https://streamable.com/q66pr
 
### Reproduction steps
 
Have a samba server with video files of any type mounted locally to the machine via "mount" in linux
 
Attempt to play any of the video files
 
### Expected behavior

mpv should play any video fine, and immediately cache several seconds to several minutes of the video and play it with no freezing, like it did in 0.29.1.

### Notes

I also did the same test as in the video above on a locally mounted (sshfs) remote webserver, and didn’t experience any stuttering, both 0.29.1 and 0.30.0 downloaded ~3mbps and played at least that video with no stuttering.

**Comment by wm4** [comment]
Try with mpv git master.

**Comment by hart0** [comment]
> Try with mpv git master.

```
./mpv/build/mpv --version
mpv 0.30.0-144-g8d4e012bfa Copyright © 2000-2019 mpv/MPlayer/mplayer2 projects
 built on Fri Nov 15 06:19:02 EST 2019
ffmpeg library versions:
   libavutil       56.35.101
   libavcodec      58.62.100
   libavformat     58.35.100
   libswscale      5.6.100
   libavfilter     7.66.100
   libswresample   3.6.100
ffmpeg version: N-95733-g73ee53f317
```
I built it with [this](https://github.com/mpv-player/mpv-build), and although there doesn't appear to be an OSD and nothing happens when I press i, the same stuttering happens as on the 0.30.0 release with any of the remote videos I tried.

**Comment by wm4** [comment]
Try with various --stream-buffer-size arguments.

**Comment by hart0** [comment]
> Try with various --stream-buffer-size arguments.

Tried with sizes going from 16KiB to 128MiB (a lot smaller/larger and it didn’t work) and it didn’t seem to change the stuttering. 

If it helps, I figured out the master build with 199aabd from March 10, 2019 is the one where the stuttering starts, everything before that doesn’t have any stuttering

**Comment by wm4** [comment]
Post a log file.

**Comment by hart0** [comment]
https://pastebin.com/raw/0EvmEfeK

**Comment by wm4** [comment]
With master, I mean.
Also try with the branch mentioned in #6802 and instructions there.

**Comment by hart0** [comment]
[Master with stream buffer size of 2MiB](https://pastebin.com/raw/5J73yA3j), [master with 64MiB](https://pastebin.com/raw/jKZfzgtw), it has the same amounts of freezing regardless of what I set the stream-buffer-size to. I build [this one](https://github.com/mpv-player/mpv/tree/stream_shit) and it seems like the same, no value I give stream-buffer-size makes it stop freezing. I tried the lavf demuxer setting and copied some of the other run time arguments and it didn't seem to change either. What they are describing in the thread looks like the same problem, although in my testing I don't have any problems with sshfs mounts (same between 0.30.0 and 0.29.1, it was caching quickly and steadily way ahead of where the video was), only samba which is local with a much better connection.

**Comment by wm4** [comment]
Your new log link is broken.

Too large sizes will lead to worse behavior, because the filesystem will block until all data is downloaded.

In any case, this is strange. You could try to bisect (and in a way that doesn't end on a merge commit), but I bet it'll be the stream cache change anyway.

**Comment by hart0** [comment]
> Your new log link is broken.
> 
> Too large sizes will lead to worse behavior, because the filesystem will block until all data is downloaded.
> 
> In any case, this is strange. You could try to bisect (and in a way that doesn't end on a merge commit), but I bet it'll be the stream cache change anyway.

Oops my bad not sure what happened with the log, edited it again.

Something I noticed is that after installing and running iotop -o on the Samba server, I tested playing back a 4K video on my laptop and if using newer mpv’s with the lagging, ioctl shows the samba daemon using Disk Read of 3.97M/s for a split second, then nothing for a few seconds, over and over during the stuttering. With 0.29.1, it reports a continuous stream of larger disk reads immediately, Eg 25M/s, 20M/s, 25M/s until it gets to whatever cache it wants to get to, then does the same 3.97 M/s reads every second or so as the cache increases while keeping 30-60 seconds ahead.

And I’m not sure if samba has some kind of internal caching or something, but if I were to close the video and try again, it would often not show any disk usage on the samba server while playing the beginning of the video again, but still has the same amount of freezing regardless.

**Comment by wm4** [comment]
Also try --cache=yes (small possibility the heuristic to detect the samba mount as network FS fails).

**Comment by hart0** [comment]
```
./mpv/build/mpv --player-operation-mode=pseudo-gui --v --log-file=~~/log --no-config --cache=yes --stream-buffer-size=36MiB
./mpv/build/mpv --player-operation-mode=pseudo-gui --v --log-file=~~/log --no-config --cache=yes --stream-buffer-size=4096KiB
./mpv/build/mpv --player-operation-mode=pseudo-gui --v --log-file=~~/log --no-config --cache=yes --stream-buffer-size=512KiB
./mpv/build/mpv --player-operation-mode=pseudo-gui --v --log-file=~~/log --no-config --cache=yes --stream-buffer-size=64KiB
./mpv/build/mpv --player-operation-mode=pseudo-gui --v --log-file=~~/log --no-config --cache=yes --stream-buffer-size=4096Kib --cache-pause-initial=yes
./mpv/build/mpv --player-operation-mode=pseudo-gui --v --log-file=~~/log --no-config --cache=auto
./mpv/build/mpv --player-operation-mode=pseudo-gui --v --log-file=~~/log --no-config --cache=no --stream-buffer-size=4096KiB
```

Tried all of these on the current master, playing the same video file and there is no difference in the apparent amount/pattern of stuttering or anything else between them. Did cache=no to see if any of these settings were actually being applied or not, but they must be because that's the only one where letting it load ~30 seconds of the video and then going back to the beginning of the video continues to have stuttering, since it's having to reload that segment due to not having cache enabled.

**Comment by wm4** [comment]
>Is stream-buffer-size supposed to be how big each section it’s trying to load is? Because regardless of what settings I try,

Yes, typically (but not always). The problem with the other linked issue was that the read calls were too small, but I guess this can be excluded in your case.

> it seems to try to load based on time lengths - since even very small videos won’t load more than a few seconds at a time (without keeping it paused and waiting for it to load the whole thing into cache). Smaller videos will be a few hundred KB/s then freezes, large 2160p videos might be 5MB/s then freezes, etc

It's really hard to say what's going on. Possibilities include:

- it's like that other issue and the read size chosen makes the network filesystem behave inefficiently
- somehow your mpv configuration limits prefetch (doesn't seem to be the case)
- it's because your file is mp4, and it triggers excessive seeks (the debug output from the stream_shit branch should log them and I don't think I've seen such seeks)
- somehow your CPU is so weak that demuxing takes long enough to bottleneck I/O, or you have very little RAM and the demuxer cache triggers paging to a slow swap partition (very unlikely)

To me it's actually a bigger mystery why 0.29 would work better. It had a cache ring buffer on a separate thread, but that shouldn't make much if a difference. The stream_shit branch actually has some options to make the new code behave more like the old one.

**Comment by mmowchenko** [comment]
I'm having this exact freezing issue after updating Solus OS last week. They use gnome-mpv 0.16. I thought I had it narrowed down to the updated libheif, x264 and x265 packages breaking it, but everything is so tightly integrated that things stop working if you start being specific.

Like your experience, no cache options work when streamed off my file server and copying certainly doesn't have any speed issues.

**Comment by hart0** [comment]
>It's really hard to say what's going on. Possibilities include:

> * it's because your file is mp4, and it triggers excessive seeks (the debug output from the stream_shit branch should log them and I don't think I've seen such seeks)
> * somehow your CPU is so weak that demuxing takes long enough to bottleneck I/O, or you have very little RAM and the demuxer cache triggers paging to a slow swap partition (very unlikely)

To answer these 2, it is a new laptop with an 8665u CPU, 16GB ram (no swap usage) and happens with any kind of video/container (mp4, mkv, webms)

> Like your experience, no cache options work when streamed off my file server and copying certainly doesn't have any speed issues.

It looks like they updated to 0.30.0 late last month/early this month, is that your version?

Is this with samba/cifs too? In addition to my previous test using sshfs on a webserver not having the issue, I switched to connecting to my media server with sshfs instead of samba and mpv works great like it used to (although I get abysmal file transfer to/from speed due to downsides with the protocol)

**Comment by mmowchenko** [comment]
0.30 is the version with the issues for me.

My file server is freenas 9.10.2-u6 served off samba/cifs.

Curiously when I stream the same mkv off a samba share on another Solus computer the freezing goes away and the cache works again. Are you using freenas too by chance?

I may have to give sshfs a try, thanks for the tip.

**Comment by hart0** [comment]
> My file server is freenas 9.10.2-u6 served off samba/cifs.
> 
> Curiously when I stream the same mkv off a samba share on another Solus computer the freezing goes away and the cache works again. Are you using freenas too by chance?

I am not using freenas, just a Linux server running samba. My server has Samba version 4.5.16-Debian according to “samba --version” which is sort of old (March 2018 release); since you said the issue goes away if you use a samba server on Solus (which appears to be newer version 4.10.8 according to my search), can you see what version Freenas uses? If they are both similarly old the bug might have been fixed in a subsequent samba release

**Comment by mmowchenko** [comment]
Samba on my freenas is at 4.5.11 and my Solus is at 4.10.10. I'm going to see if I can update it on freenas to at least my desktop's version.

**Comment by themoken** [comment]
I just encountered this streaming from an OpenWRT router (Samba 3.6) with mpv from the Arch repos (0.30.0). It reported ~1s of cache and constantly bottomed out, but mpv-git works like a charm and reports close to 200s cached without any server side changes. This may be fixed now.

**Comment by wm4** [comment]
The people in this issue reported that this problem also happens with git master, though. Yes, it was fixed in most cases.

**Comment by themoken** [comment]
Sure, but as you know git master has moved since the last comment claiming it was broken 10-17 days ago. I reproduced the issue on 0.30.0, but got different behavior from git from 7 hours ago, without changing any package but mpv. Might be worth hart0/mmowchenko re-checking.

**Comment by wm4** [comment]
Nothing about caching was changed in the code.

**Comment by hart0** [comment]
I just compiled master again and didn’t see any improvements with the stuttering on smb

**Comment by mmowchenko** [comment]
The issue still exists for me but I just wanted to add that nfs doesn't seem to have the same caching issue that samba does.

**Comment by wm4** [comment]
Can anyone confirm whether this is fixed with git master?

**Comment by Azenet** [comment]
It works for me, yes. Thank you.

**Comment by Temtaime** [comment]
Hello.
This is still an issue for 0.34 for me. Windows.
Cache is populated only when video is paused. When paying, cache is not populated at all and it shutters.
What settings i have to set ?
