### ISSUE TITLE
Smooth motion like madvr?

### ISSUE THREAD

**Issue by Soukyuu** [mpv-player/mpv#731]
I have recently tried mpv again, just to compare it against mpc-hc with madvr output. The first thing that I noticed is that all the 23.976fps videos appeared less smooth on pans on my 60Hz monitor. 

madVR has a feature called "smooth motion", where it converts the framerate on-the-fly, allowing to keep the smoothness of video playback. It would be really nice to have something like that in mpv in the future.

**Comment by Soukyuu** [comment]
I have just tried the latest commit, and the L/R stutter is gone.
I have also found out that enabling smooth motion causes both my 8600m GT and the Radeon 6130 to drop frames :( 

I assume this is also the reason why with smooth motion enabled it appears more jerky than without it. Running with --vo=opengl:smoothmotion appears less jerky, but about the same number of frames is reported as dropped. Both GPUs were able to handle madvr's SM.

**Comment by pigoz** [comment]
keep in mind that the framedrop count is busted (it reports as drops stuff that is not a real drop)

**Comment by Soukyuu** [comment]
Oh, didn't know that. With the new revision, no frames are reported as dropped, but the jerkiness with SM enabled still appears to be higher for me as described above.

**Comment by Soukyuu** [comment]
I managed to compile a cygwin build on my windows 8.1 x64 machine and it runs a lot better on a 260GTX. It's definitely an improvement over SM disabled and it also seems to be less blurry than madvr, unless I'm seeing things. 

There are a few jerks now and then though, which only happen randomly: replaying the scene, parts that didn't stutter might stutter and vice versa. If you need me to provide any information, just ask.

**Comment by pigoz** [comment]
Maybe on your particular configuration mpv is missing some vsyncs (as opposed to madvr we don't prerender frames). If this started being an issue in the latest commits, I can make the code a little smarter  and draw as soon as possible (to avoid being late for the vsync), and then sleep until the vsync.

**Comment by Soukyuu** [comment]
I'm not sure if it started happening on latest commits, because I always attributed the jerking to the lack of smooth motion. It's happening on all 3 machines though and on different OSes, plus they're all fairly low end by today's standards, so maybe that's it.

Why is mpv not pre-rendering frames though? That could improve performance for lower end hardware.

**Comment by pigoz** [comment]
In the last commits I changed slightly the timing at which each frame is prerendered (before it was at early as possible, now it's at most 4ms before vsync but that could cause problems with bad hardware), so that's why I asked specifically.

From my understanding, MadVR also prerenders several frames in advance, but that would be very hard to do in a simple way within mpv.

**Comment by wm4** [comment]
>Why is mpv not pre-rendering frames though? 

I'm not confident that this would be possible in OpenGL without running into severe problems and overcomplications.

**Comment by Soukyuu** [comment]
I'm not sure if I'm not just getting hit by a performance penalty because of compiling and running mpv via cygwin. Are there native build instructions for windows? How are the binaries by @lachs0r compiled?

About buffering, good to know. My openGL knowledge is pretty basic, hence the question.

**Comment by kevmitch** [comment]
@Soukyuu There are three ways to get a native build:

* [msys](https://gist.github.com/rossy/169d7e871bef5ed1bf6c): fully native build on windows for windows. I haven't tested this myself
* [mxe](https://github.com/mpv-player/mpv/blob/master/DOCS/crosscompile-mingw.md#example-with-mxe): build on linux to run on windows using released versions of dependencies
* [mingw-w64-cmake](https://github.com/lachs0r/mingw-w64-cmake): build on linux to run on windows using latest development versions (e.g. git head) for dependencies where available.

mingw-w64-cmake is what lachs0r uses for the windows builds. I however find mxe easier as it has fewer intermittent failures due to constantly changing dependencies. I haven't tried msys, although it sounds pretty straightforward.

**Comment by Soukyuu** [comment]
- msys: fails to see includes/ffmpeg even though packages are installed
- mxe: link doesn't work - 404
- mingw-w64-cmake: fails at building binutils because all warnings are treated as errors. Same after I added -Wno-error in it's Makefile, and I'm not seeing any -Werror flags anywhere.

**Comment by wm4** [comment]
The instructions for mxe and msys2 are now on the same page: https://github.com/mpv-player/mpv/blob/master/DOCS/compile-windows.md

**Comment by Soukyuu** [comment]
I'm giving up. mxe builds binutils fine, but fails to build bzip2 because
```
make[2]: x86_64-w64-mingw32.static-gcc: Command not found
```
That's on two separate PCs.

The pre-made mingw64-cmake env vmdk image fails at download/verify/extract openssl step

**Comment by lachs0r** [comment]
You can also try using the VM image linked in the mingw-w64-cmake README. That’s almost the same environment I use for the Windows builds, and should generally work.

**Comment by Soukyuu** [comment]
That's what I meant by pre-made mingw64  image

**Comment by lachs0r** [comment]
Yesterday it worked. Seems like openssl.org fucked up and deleted the source archive.

**Comment by lachs0r** [comment]
Let’s just wait until openssl.org stops being terrible at everything they do and gets the archive back up.

**Comment by Soukyuu** [comment]
I guess. 
Any idea why waf is being blind about the include/lib paths even though I set the prefix as mentioned in the instructions?

**Comment by lachs0r** [comment]
They’ve *just now* released a new version. It built successfully here so I’ve pushed the update to mingw-w64-cmake.

**Comment by Soukyuu** [comment]
Well, I don't know. 
```
[24/272] Perorming patch step for 'enca'
 FAILED
Applying: Lazy cross compile fix
error: patch failed: configure.ac:97
error: configure.ac: patch does not apply
error: patch failed: tools/Makefile.am:31
error: tools/Makefile.am: patch does not apply
```

**Comment by lachs0r** [comment]
Does it work if you rm -rf packages/enca-prefix and retry?

**Comment by Soukyuu** [comment]
Yes. I'm stuck at ffmpeg step now with the same problem, and removing ffmpeg-prefix doesn't solve it.

I was able to get msys working though (was starting msys2.bat, not mingw64-shell.bat) and it turns out the performance is on par with the cygwin build. It also shows exactly the same behavior, so I think it's something about the code.

Another interesting thing is that enabling smooth motion pushes my CPU usage to 60% per core (AMD Phenom II X4 970@3,4GHz), while GPU usage does not increase, or rather, is really low.

- madvr: 16% CPU / 48% GPU
- madvr + sm 16% CPU / 51% GPU
- mpv opengl: 10% CPU / 2% GPU
- mpv opengl:smoothmotion: 60% CPU / 4%GPU

That's a really huge impact on CPU...

**Comment by wm4** [comment]
That seems pretty wrong. Maybe some active waiting or so.

**Comment by lachs0r** [comment]
(The ffmpeg problem is fixed now, git pull and remove ffmpeg-prefix.)

**Comment by Soukyuu** [comment]
Well, fwiw, the impact on my linux machine (core2duo T7250@2GHz) is not that big, only about 10%

(I managed to finish compiling mpv in VM, but it crashes on start with a generic "stopped working" message even without any options specified)

**Comment by lachs0r** [comment]
That would indicate the mpv repo isn’t updating properly.

Sigh.

**Comment by Soukyuu** [comment]
Well, [from what I saw](http://www.cmake.org/cmake/help/v3.0/module/ExternalProject.html) I had to modify packages/mpv.cmake and add a 
```
GIT_TAG smooth-motion
```
to it under the GIT_REPOSITORY. Maybe that broke it?
Though the log says "HEAD is now at 75dbe8b bo_opengl: add smoothmotion frame blending", so it seems to be the smooth motion branch...

**Comment by lachs0r** [comment]
Okay. The fix that went into master earlier isn’t in the smooth-motion branch 
yet.

**Comment by pigoz** [comment]
Now this is in master with some changes. If the result doesn't look ok on your system, please open another ticket.
