### ISSUE TITLE
MPV wont play RAR files properly anymore?

### ISSUE THREAD

**Issue by mark12121** [mpv-player/mpv#8280]
I have searched and weirdly this issue isn't getting much attention?
Loads and loads of videos online are in rar files, like loads and loads. I am sure whoever make this awesome media player must know this.
MPV has always been my goto player, but not playing rars is like not playing mp4s. Please please fix asap :))
MPV always used to do this no problem at all:

Techie bits:

### Important Information
- mpv 0.32
- Archlinux and/or Fedora

### Reproduction steps
mpv file.rar (multiset rars e.g. r01 r02.. rar)

### Expected behavior
mpv plays and seeks through the content perfectly as it did before, and as VLC does.

### Actual behavior
[libarchive] possibly unsupported seeking - switching to reopening
[libarchive] Truncated RAR file data
[libarchive] fatal error received - closing archive
[libarchive] Seek failed (to 2697056756, size 2697148405)
[mkv] Failed to seek when reading header element.
[libarchive] Truncated RAR file data
[libarchive] fatal error received - closing archive
[libarchive] Seek failed (to 2697146887, size 2697148405)
[mkv] Failed to seek when reading header element.

**Comment by Akemi** [comment]
no we believe videos in (multi) rar files are bad and should not be used. this is a libarchive issue and should be reported to them. there are already various issues like this which are closed now.

the old rar demuxer was removed because of maintainability. it's not likely to return.

https://github.com/mpv-player/mpv/wiki/FAQ#What_is_the_rar_file_format_and_why_is_it_stupid

**Comment by mark12121** [comment]
> no we believe videos in (multi) rar files are bad and should not be used. this is a libarchive issue and should be reported to them. there are already various issues like this which are closed now.
> 
> the old rar demuxer was removed because of maintainability. it's not likely to return.
> 
> https://github.com/mpv-player/mpv/wiki/FAQ#What_is_the_rar_file_format_and_why_is_it_stupid

Oh hmmz.. in the politest way possible and without trying to sound like a smartass or anything, that wiki entry is very wrong. I am sure the development team are much smarter than I, but they appear to have missed this one.

I would suggest whoever wrote that have a good ol' google session and read up on the history and present methods of video sharing online. I would guestimate that about half of all video ever played in MPV came from a RARset at some point. Apprecaite this might sound bonkers as it is an old format, but there are very good reasons. It's an interesting read and rabbit hole to go down, very worth the time. People are capable of amazing feats of anonymous organisation!

I don't program myself, so my suggestions might (probably) have technical reasons why they wont work.. but could:
- The original 'demuxer' be reinstated, it shouldn't need maintenance as the RAR format is fixed and likely here to stay a long while?
- VLC doesn't currently seem to have this issue, could the method they use be adopted?

I will also direct my efforts toward the 'libarchive' developers. Can anyone explain in laymen's why 'libarchive' might doesnt work?

**Comment by Akemi** [comment]
there is nothing wrong with that wiki entry i linked. it doesn't claim anything that is wrong. the history behind that is completely pointless to us. how files are distributed depends heavily on the community they come from and there are many and huge ones that don't consider (multi) rar files be a suitable and acceptable format to distribute video files. we had this discussion many times before and i would appreciate if it wouldn't start again.

it was already suggested many times before and the answer is always the same:
everything needs to be maintained. just because the format is fixed doesn't mean the implementation within a program doesn't need to change. that's a common occurrence when refactoring for example. the old demuxer is gone and won't come back in the form it was removed.

it was removed because none wanted to maintain it. if someone wants to maintain it and/or port the VLC demuxer to mpv they are very welcome to do so and try.

**Comment by jeeb** [comment]
Multi-part RAR support should have improved in April: https://github.com/mpv-player/mpv/commits/master/stream/stream_libarchive.c

I've still heard reports that it still fails with some archives, but I don't think there's been a note regarding where the issue is. Here or on libarchive's side.

**Comment by mark12121** [comment]
> Multi-part RAR support should have improved in April: https://github.com/mpv-player/mpv/commits/master/stream/stream_libarchive.c
> 
> I've still heard reports that it still fails with some archives, but I don't think there's been a note regarding where the issue is. Here or on libarchive's side.

Thank you JEEB.

**Comment by mark12121** [comment]
> there is nothing wrong with that wiki entry i linked. it doesn't claim anything that is wrong. the history behind that is completely pointless to us. how files are distributed depends heavily on the community they come from and there are many and huge ones that don't consider (multi) rar files be a suitable and acceptable format to distribute video files. we had this discussion many times before and i would appreciate if it wouldn't start again.
> 
> it was already suggested many times before and the answer is always the same:
> everything needs to be maintained. just because the format is fixed doesn't mean the implementation within a program doesn't need to change. that's a common occurrence when refactoring for example. the old demuxer is gone and won't come back in the form it was removed.
> 
> it was removed because none wanted to maintain it. if someone wants to maintain it and/or port the VLC demuxer to mpv they are very welcome to do so and try.

Curious, why does it need to be maintained? If the format is static?

Also do google, there are many video sharing communities yes.. but there is also the community that is the reason compressed video players exist.
