### ISSUE TITLE
mpv flickering/damage issue on sway with gpu-context=waylandvk and profile=gpu-hq

### ISSUE THREAD

**Issue by RPigott** [mpv-player/mpv#8476]
### Important Information

Provide following Information:
- mpv version, Linux Distribution and Version, Source of the mpv binary
Arch Linux, mpv from the official [community] repository.
```
$ pacman -Q linux mpv
linux 5.10.7.arch1-1
mpv 1:0.33.0-3
```
- If known which version of mpv introduced the problem
Unknown, but I first noticed it about a week ago. Probably introduced within the last ~6 weeks, but maybe not by a code change in mpv.

- Window Manager and version, GPU driver and version
```
$ lspci -kd::300
00:02.0 VGA compatible controller: Intel Corporation HD Graphics 630 (rev 04)
	DeviceName:  Onboard IGD
	Subsystem: Dell Device 07be
	Kernel driver in use: i915
	Kernel modules: i915
$ pacman -Q {sway,wlroots}-git mesa vulkan-intel vulkan-icd-loader
sway-git r6577.915ba01f-1
wlroots-git 0.12.0.r247.g32c30481-1
mesa 20.3.3-1
vulkan-intel 20.3.3-1
vulkan-icd-loader 1.2.166-1
```
I can also reproduce on the release versions of sway/wlroots.

- Possible screenshot or video of visual glitches
When the glitch occurs, the mpv window is completely black with possible damage artifacts instead of showing a video frame.

### Reproduction steps + Expected/Actual Behavior

1. Play any video with `mpv --no-config --gpu-context=waylandvk --profile=gpu-hq $video`
2. Observe that the video content in the mpv window flickers
3. Pause the video and repeatedly seek backward 1 frame until you find a broken/black frame
4. Wait and observe parts of the window change as the compositor damages mpv's window. On sway I can see the mpv window switching from black to fine and back to black every 5 second interval, when my statusbar updates the timestamp on my display. You may need to be careful not to disturb the mpv window with your cursor or other windows updating if you want to observe this behavior.

This looks like a buffer damage issue. You can reproduce the exact same behavior with a trivial wayland client that attaches/commits an all black buffer, then writes any image to the buffer and commits it, but does not commit any damage.

This issue is not reproducible for me with --gpu-context=wayland instead of waylandvk. It seems possible the behavior was introduced by a change in mesa or some project other than mpv, but it's not clear to me where the bug lies.

### Log file

In this log I play a video and waited until I observed a black flicker (a few seconds), then paused the video and used the comma key to step backward by frame until the video appeared black again and showed the characteristic damage artifacts. Then I exited the player.

<details>
<summary>mpv.log</summary>

```
[cplayer] Command line options: '-v' '--no-config' '--gpu-context=waylandvk' '--profile=gpu-hq' '/home/ronan/videos/example.mp4'
[cplayer] mpv 0.33.0 Copyright \u00a9 2000-2020 mpv/MPlayer/mplayer2 projects
[cplayer]  built on UNKNOWN
[cplayer] FFmpeg library versions:
[cplayer]    libavutil       56.51.100
[cplayer]    libavcodec      58.91.100
[cplayer]    libavformat     58.45.100
[cplayer]    libswscale      5.7.100
[cplayer]    libavfilter     7.85.100
[cplayer]    libswresample   3.7.100
[cplayer] FFmpeg version: n4.3.1
[cplayer] 
[cplayer] Configuration: /usr/bin/waf configure --prefix=/usr --confdir=/etc/mpv --enable-cdda --enable-dvb --enable-dvdnav --enable-libarchive --enable-libmpv-shared --disable-build-date
[cplayer] List of enabled features: 52arch alsa asm caca cdda cplayer cplugins cuda-hwaccel cuda-interop debug-build drm dvbin dvdnav egl egl-drm egl-helpers egl-x11 ffmpeg ffnvcodec gbm gbm.h gl gl-wayland glibc-thread-name glob glob-posix gpl iconv jack javascript jpeg lcms2 libarchive libass libavdevice libbluray libdl libm libmpv-shared libplacebo librt linux-fstatfs linux-input-event-codes lua memfd_create optimize plain-gl posix posix-or-mingw pthreads pulse rubberband shaderc shaderc-shared stdatomic uchardet vaapi vaapi-drm vaapi-egl vaapi-vulkan vaapi-wayland vaapi-x-egl vaapi-x11 vdpau vt.h vulkan wayland wayland-protocols x11 xv zlib
[cplayer] Setting option 'v' = '' (flags = 8)
[cplayer] Setting option 'config' = 'no' (flags = 8)
[cplayer] Setting option 'gpu-context' = 'waylandvk' (flags = 8)
[cplayer] Setting option 'profile' = 'gpu-hq' (flags = 8)
[cplayer] Applying profile 'gpu-hq'...
[cplayer] Setting option 'scale' = 'spline36' (flags = 12)
[cplayer] Setting option 'cscale' = 'spline36' (flags = 12)
[cplayer] Setting option 'dscale' = 'mitchell' (flags = 12)
[cplayer] Setting option 'dither-depth' = 'auto' (flags = 12)
[cplayer] Setting option 'correct-downscaling' = 'yes' (flags = 12)
[cplayer] Setting option 'linear-downscaling' = 'yes' (flags = 12)
[cplayer] Setting option 'sigmoid-upscaling' = 'yes' (flags = 12)
[cplayer] Setting option 'deband' = 'yes' (flags = 12)
[cplayer] Waiting for scripts...
[osd/libass] Shaper: FriBidi 1.0.10 (SIMPLE) HarfBuzz-ng 2.7.4 (COMPLEX)
[osd/libass] Setting up fonts...
[osd/libass] Using font provider fontconfig
[osd/libass] Done.
[cplayer] Set property: shared-script-properties -> 1
[cplayer] Done loading scripts.
[cplayer] Running hook: ytdl_hook/on_load
[ytdl_hook] ytdl:// hook 
[ytdl_hook] not a ytdl:// url 
[ifo_dvdnav] Opening /home/ronan/videos/example.mp4
[bdmv/bluray] Opening /home/ronan/videos/example.mp4
[file] Opening /home/ronan/videos/example.mp4
[demux] Trying demuxers for level=normal.
[cplayer] Set property: shared-script-properties -> 1
[osd/libass] Shaper: FriBidi 1.0.10 (SIMPLE) HarfBuzz-ng 2.7.4 (COMPLEX)
[osd/libass] Setting up fonts...
[lavf] Found 'mov,mp4,m4a,3gp,3g2,mj2' at score=100 size=2048.
[file] stream level seek from 131072 to 4121077
[file] stream level seek from 4142667 to 44
[file] stream level seek from 131116 to 4142667
[demux] Detected file format: mov,mp4,m4a,3gp,3g2,mj2 (libavformat)
[cplayer] Opening done: /home/ronan/videos/example.mp4
[osd/libass] Using font provider fontconfig
[osd/libass] Done.
[find_files] Loading external files in /home/ronan/videos/
[cplayer] Running hook: ytdl_hook/on_preloaded
[lavf] select track 0
[lavf] select track 1
[cplayer]  (+) Video --vid=1 (*) (vp9 1280x720 23.976fps)
[cplayer]  (+) Audio --aid=1 --alang=jpn (*) (aac 2ch 48000Hz)
[vo/gpu/vulkan] Initializing GPU context 'waylandvk'
[vo/gpu/vulkan/libplacebo] Initialized libplacebo v72
[vo/gpu/vulkan/libplacebo] Creating vulkan instance with extensions:
[vo/gpu/vulkan/libplacebo]     VK_KHR_get_physical_device_properties2
[vo/gpu/vulkan/libplacebo]     VK_KHR_surface
[vo/gpu/vulkan/libplacebo]     VK_KHR_external_memory_capabilities
[vo/gpu/vulkan/libplacebo]     VK_KHR_external_semaphore_capabilities
[vo/gpu/vulkan/libplacebo]     VK_KHR_surface
[vo/gpu/vulkan/libplacebo]     VK_KHR_wayland_surface
[vo/gpu/wayland] Registered for protocol wl_shm
[vo/gpu/wayland] Registered for protocol wl_compositor
[vo/gpu/wayland] Registered for protocol wl_data_device_manager
[vo/gpu/wayland] Registered for protocol zwp_idle_inhibit_manager_v1
[vo/gpu/wayland] Registered for protocol xdg_wm_base
[vo/gpu/wayland] Registered for protocol zxdg_decoration_manager_v1
[vo/gpu/wayland] Registered for protocol wp_presentation
[vo/gpu/wayland] Registered for protocol wl_seat
[vo/gpu/wayland] Registered for protocol wl_output
[vo/gpu/wayland] Enabling server decorations
[vo/gpu/vulkan/libplacebo] Probing for vulkan devices:
[vo/gpu/vulkan/libplacebo]     GPU 0: Intel(R) HD Graphics 630 (KBL GT2) (integrated)
[vo/gpu/vulkan/libplacebo]            uuid: 08:77:37:4D:04:A0:FC:E6:4A:D7:89:3F:A0:05:06:C5
[vo/gpu/vulkan/libplacebo] Vulkan device properties:
[vo/gpu/vulkan/libplacebo]     Device Name: Intel(R) HD Graphics 630 (KBL GT2)
[vo/gpu/vulkan/libplacebo]     Device ID: 8086:591b
[vo/gpu/vulkan/libplacebo]     Device UUID: 08:77:37:4D:04:A0:FC:E6:4A:D7:89:3F:A0:05:06:C5
[vo/gpu/vulkan/libplacebo]     Driver version: 83898371
[vo/gpu/vulkan/libplacebo]     API version: 1.2.145
[vo/gpu/vulkan/libplacebo] Queue families supported by device:
[vo/gpu/vulkan/libplacebo]     QF 0: flags 0x7 num 1
[vo/gpu/vulkan/libplacebo] Using graphics queue (QF 0)
[vo/gpu/vulkan/libplacebo] Creating vulkan device with extensions:
[vo/gpu/vulkan/libplacebo]     VK_KHR_swapchain
[vo/gpu/vulkan/libplacebo]     VK_KHR_swapchain
[vo/gpu/vulkan/libplacebo]     VK_KHR_push_descriptor
[vo/gpu/vulkan/libplacebo]     VK_KHR_external_memory_fd
[vo/gpu/vulkan/libplacebo]     VK_EXT_external_memory_dma_buf
[vo/gpu/vulkan/libplacebo]     VK_KHR_external_semaphore_fd
[vo/gpu/vulkan/libplacebo]     VK_EXT_pci_bus_info
[vo/gpu/vulkan/libplacebo] Initializing SPIR-V compiler 'shaderc'
[vo/gpu/vulkan/libplacebo] Memory heaps supported by device:
[vo/gpu/vulkan/libplacebo]     heap 0: flags 0x1 size 12471057408
[vo/gpu/vulkan/libplacebo] Memory types supported by device:
[vo/gpu/vulkan/libplacebo]     type 0: flags 0xf heap 0
[vo/gpu/vulkan/libplacebo] GPU information:
[vo/gpu/vulkan/libplacebo]     GLSL version: 450 (vulkan)
[vo/gpu/vulkan/libplacebo]     Capabilities: 0x19
[vo/gpu/vulkan/libplacebo]     Limits:
[vo/gpu/vulkan/libplacebo]       max_tex_1d_dim:            16384
[vo/gpu/vulkan/libplacebo]       max_tex_2d_dim:            16384
[vo/gpu/vulkan/libplacebo]       max_tex_3d_dim:            2048
[vo/gpu/vulkan/libplacebo]       max_pushc_size:            128
[vo/gpu/vulkan/libplacebo]       max_xfer_size:             18446744073709551615
[vo/gpu/vulkan/libplacebo]       max_ubo_size:              134217728
[vo/gpu/vulkan/libplacebo]       max_ssbo_size:             1073741824
[vo/gpu/vulkan/libplacebo]       max_buffer_texels:         134217728
[vo/gpu/vulkan/libplacebo]       min_gather_offset:         -32
[vo/gpu/vulkan/libplacebo]       max_gather_offset:         31
[vo/gpu/vulkan/libplacebo]       max_shmem_size:            65536
[vo/gpu/vulkan/libplacebo]       max_group_threads:         1792
[vo/gpu/vulkan/libplacebo]       max_group_size[0]:         1792
[vo/gpu/vulkan/libplacebo]       max_group_size[1]:         1792
[vo/gpu/vulkan/libplacebo]       max_group_size[2]:         1792
[vo/gpu/vulkan/libplacebo]       max_dispatch[0]:           65535
[vo/gpu/vulkan/libplacebo]       max_dispatch[1]:           65535
[vo/gpu/vulkan/libplacebo]       max_dispatch[2]:           65535
[vo/gpu/vulkan/libplacebo]       align_tex_xfer_stride:     128
[vo/gpu/vulkan/libplacebo]       align_tex_xfer_offset:     128
[vo/gpu/vulkan/libplacebo]     External API interop:
[vo/gpu/vulkan/libplacebo]       UUID: 08:77:37:4D:04:A0:FC:E6:4A:D7:89:3F:A0:05:06:C5
[vo/gpu/vulkan/libplacebo]       PCI: 0000:00:02:0
[vo/gpu/vulkan/libplacebo]       buf export caps: 0x9
[vo/gpu/vulkan/libplacebo]       buf import caps: 0x9
[vo/gpu/vulkan/libplacebo]       tex export caps: 0x9
[vo/gpu/vulkan/libplacebo]       tex import caps: 0x9
[vo/gpu/vulkan/libplacebo]       sync export caps: 0x1
[vo/gpu/vulkan/libplacebo]       sync import caps: 0x0
[vo/gpu] Testing FBO format rgba16f
[vo/gpu/vulkan/libplacebo] Allocating 1048576 memory of type 0xf (id 0) in heap 0
[vo/gpu] Using FBO format rgba16f.
[vo/gpu/wayland] Registered output Sharp Corporation 0x1453 (0x23):
[vo/gpu/wayland] 	x: 0px, y: 0px
[vo/gpu/wayland] 	w: 1920px (350mm), h: 1080px (190mm)
[vo/gpu/wayland] 	scale: 1
[vo/gpu/wayland] 	Hz: 59.934000
[vo/gpu] Resize: 0x0
[vd] Container reported FPS: 23.976024
[vd] Codec list:
[vd]     vp9 - Google VP9
[vd]     vp9_v4l2m2m (vp9) - V4L2 mem2mem VP9 decoder wrapper
[vd]     libvpx-vp9 (vp9) - libvpx VP9
[vd]     vp9_cuvid (vp9) - Nvidia CUVID VP9 decoder
[vd]     vp9_qsv (vp9) - VP9 video (Intel Quick Sync Video acceleration)
[vd] Opening decoder vp9
[vd] No hardware decoding requested.
[vd] Using software decoding.
[vd] Detected 8 logical cores.
[vd] Requesting 9 threads for decoding.
[vd] Selected codec: vp9 (Google VP9)
[vf] User filter list:
[vf]   (empty)
[ad] Codec list:
[ad]     aac - AAC (Advanced Audio Coding)
[ad]     aac_fixed (aac) - AAC (Advanced Audio Coding)
[ad] Opening decoder aac
[ad] Requesting 1 threads for decoding.
[ad] Selected codec: aac (AAC (Advanced Audio Coding))
[af] User filter list:
[af]   (empty)
[cplayer] Starting playback...
[file] stream level seek from 4142667 to 67
[vo/gpu/vulkan/libplacebo] Allocating 11305216 memory of type 0xf (id 0) in heap 0
[vo/gpu/vulkan/libplacebo] Allocating 45220864 memory of type 0xf (id 0) in heap 0
[vd] Using software decoding.
[vd] Decoder format: 1280x720 [0:1] yuv420p10 auto/auto/auto/limited/auto CL=unknown
[vd] Using container aspect ratio.
[vf] [in] 1280x720 yuv420p10 bt.709/bt.709/bt.1886/limited/display SP=1.000000 CL=mpeg2/4/h264
[vf] [userdeint] 1280x720 yuv420p10 bt.709/bt.709/bt.1886/limited/display SP=1.000000 CL=mpeg2/4/h264
[vf] [userdeint] (disabled)
[vf] [autorotate] 1280x720 yuv420p10 bt.709/bt.709/bt.1886/limited/display SP=1.000000 CL=mpeg2/4/h264
[vf] [autorotate] (disabled)
[vf] [convert] 1280x720 yuv420p10 bt.709/bt.709/bt.1886/limited/display SP=1.000000 CL=mpeg2/4/h264
[vf] [convert] (disabled)
[vf] [out] 1280x720 yuv420p10 bt.709/bt.709/bt.1886/limited/display SP=1.000000 CL=mpeg2/4/h264
[af] [in] 48000Hz stereo 2ch floatp
[af] [userspeed] 48000Hz stereo 2ch floatp
[af] [userspeed] (disabled)
[af] [convert] 48000Hz stereo 2ch floatp
[ao] Trying audio driver 'pulse'
[ao/pulse] requested format: 48000 Hz, stereo channels, floatp
[ao/pulse] Library version: 14.1.0
[ao/pulse] Proto: 34
[ao/pulse] Server proto: 4294967295
[ao/pulse] Channel layouts:
[ao/pulse]  - #fl
[ao/pulse]  - #fr
[ao/pulse]  - #fc
[ao/pulse]  - #lfe
[ao/pulse]  - #bl
[ao/pulse]  - #br
[ao/pulse]  - #flc
[ao/pulse]  - #frc
[ao/pulse]  - #bc
[ao/pulse]  - #sl
[ao/pulse]  - #sr
[ao/pulse]  - #tc
[ao/pulse]  - #tfl
[ao/pulse]  - #tfc
[ao/pulse]  - #tfr
[ao/pulse]  - #tbl
[ao/pulse]  - #tbc
[ao/pulse]  - #tbr
[ao/pulse] result: stereo
[ao/pulse] device buffer: 4800 samples.
[ao/pulse] using soft-buffer of 9600 samples.
[cplayer] AO: [pulse] 48000Hz stereo 2ch float
[cplayer] AO: Description: PulseAudio audio output
[autoconvert] inserting resampler
[swresample] format change, reinitializing resampler
[swresample] 48000Hz stereo floatp -> 48000Hz stereo float
[af] [out] 48000Hz stereo 2ch float
[cplayer] VO: [gpu] 1280x720 yuv420p10
[cplayer] VO: Description: Shader-based GPU Renderer
[vo/gpu] reconfig to 1280x720 yuv420p10 bt.709/bt.709/bt.1886/limited/display SP=1.000000 CL=mpeg2/4/h264
[vo/gpu/wayland] Reconfiguring!
[vo/gpu] Resize: 1280x720
[vo/gpu] Window size: 1280x720 (Borders: l=0 t=0 r=0 b=0)
[vo/gpu] Video source: 1280x720 (1:1)
[vo/gpu] Video display: (0, 0) 1280x720 -> (0, 0) 1280x720
[vo/gpu] Video scale: 1.000000/1.000000
[vo/gpu] OSD borders: l=0 t=0 r=0 b=0
[vo/gpu] Video borders: l=0 t=0 r=0 b=0
[vo/gpu] Texture for plane 0: 1280x720
[vo/gpu/vulkan/libplacebo] Allocating 7536640 memory of type 0xf (id 0) in heap 0
[vo/gpu] Texture for plane 1: 640x360
[vo/gpu] Texture for plane 2: 640x360
[vo/gpu] Testing FBO format rgba16f
[vo/gpu] Using FBO format rgba16f.
[vo/gpu/wayland] Handling resize on the vk side
[vo/gpu/vulkan/libplacebo] (Re)creating swapchain of size 1280x720
[vo/gpu] Resize: 1280x720
[vo/gpu] Window size: 1280x720 (Borders: l=0 t=0 r=0 b=0)
[vo/gpu] Video source: 1280x720 (1:1)
[vo/gpu] Video display: (0, 0) 1280x720 -> (0, 0) 1280x720
[vo/gpu] Video scale: 1.000000/1.000000
[vo/gpu] OSD borders: l=0 t=0 r=0 b=0
[vo/gpu] Video borders: l=0 t=0 r=0 b=0
[vo/gpu] DR enabled: yes
[vo/gpu/vulkan/libplacebo] Allocating 1048576 memory of type 0xf (id 0) in heap 0
[vo/gpu/vulkan/libplacebo] Allocating 1048576 memory of type 0xf (id 0) in heap 0
[vo/gpu/vulkan/libplacebo] Allocating 30244944 memory of type 0xf (id 0) in heap 0
[vo/gpu/vulkan/libplacebo] Allocating 1048576 memory of type 0xf (id 0) in heap 0
[vo/gpu] Dither to 8.
[vo/gpu/wayland] Given DND offer with mime type text/plain
[vo/gpu/wayland] Given DND offer with mime type text/plain;charset=utf-8
[vo/gpu/wayland] Resizing due to xdg from 1280x720 to 945x1038
[cplayer] first video frame after restart shown
[vo/gpu] Resize: 1280x720
[vo/gpu] Window size: 1280x720 (Borders: l=0 t=0 r=0 b=0)
[vo/gpu] Video source: 1280x720 (1:1)
[vo/gpu] Video display: (0, 0) 1280x720 -> (0, 0) 1280x720
[vo/gpu] Video scale: 1.000000/1.000000
[vo/gpu] OSD borders: l=0 t=0 r=0 b=0
[vo/gpu] Video borders: l=0 t=0 r=0 b=0
[vo/gpu/wayland] Handling resize on the vk side
[vo/gpu/vulkan/libplacebo] (Re)creating swapchain of size 945x1038
[vo/gpu] Resize: 945x1038
[vo/gpu] Window size: 945x1038 (Borders: l=0 t=0 r=0 b=0)
[vo/gpu] Video source: 1280x720 (1:1)
[vo/gpu] Video display: (0, 0) 1280x720 -> (0, 253) 945x531
[vo/gpu] Video scale: 0.738281/0.737500
[vo/gpu] OSD borders: l=0 t=253 r=0 b=254
[vo/gpu] Video borders: l=0 t=253 r=0 b=254
[cplayer] audio ready
[cplayer] delaying audio start 0.000000 vs. 0.000000, diff=0.000000
[cplayer] playback restart complete @ 0.000000, audio=ready, video=playing
[statusline] AV: 00:00:00 / 00:00:39 (0%) A-V:  0.000
[cplayer] starting audio playback
[ao/pulse] starting AO
[vo/gpu/vulkan/libplacebo] Allocating 120979776 memory of type 0xf (id 0) in heap 0
[vo/gpu/wayland] Surface entered output Sharp Corporation 0x1453 (0x23), scale = 1
[vo/gpu/wayland] Enabling idle inhibitor
[vo/gpu] Assuming 59.934000 FPS for display sync.
[statusline] AV: 00:00:00 / 00:00:39 (0%) A-V:  0.000
[cplayer] Set property: shared-script-properties -> 1
[cplayer] Set property: shared-script-properties -> 1
[statusline] AV: 00:00:01 / 00:00:39 (3%) A-V:  0.000
[cplayer] Set property: pause -> 1
[statusline] (Paused) AV: 00:00:01 / 00:00:39 (3%) A-V:  0.000
[vo/gpu/wayland] Disabling the idle inhibitor
[statusline] (Paused) AV: 00:00:01 / 00:00:39 (3%) A-V:  0.000
[lavf] queuing seek to 0.709542
[lavf] execute seek (to 0.709542 flags 32)
[lavf] seek done
[cplayer] hr-seek, skipping to 1.209542 (no framedrop) (backstep)
[vd] Decoder format: 1280x720 [0:1] yuv420p10 auto/auto/auto/limited/auto CL=unknown
[vd] Using container aspect ratio.
[statusline] (Paused) AV: 00:00:01 / 00:00:39 (3%) A-V:  0.000
[cplayer] first video frame after restart shown
[cplayer] audio ready
[cplayer] starting audio playback
[cplayer] playback restart complete @ 1.167833, audio=playing, video=playing (paused)
[statusline] (Paused) AV: 00:00:01 / 00:00:39 (3%) A-V:  0.000
[lavf] queuing seek to 0.667833
[lavf] execute seek (to 0.667833 flags 32)
[lavf] seek done
[cplayer] hr-seek, skipping to 1.167833 (no framedrop) (backstep)
[vd] Decoder format: 1280x720 [0:1] yuv420p10 auto/auto/auto/limited/auto CL=unknown
[vd] Using container aspect ratio.
[statusline] (Paused) AV: 00:00:01 / 00:00:39 (3%) A-V:  0.000
[cplayer] first video frame after restart shown
[cplayer] audio ready
[cplayer] starting audio playback
[cplayer] playback restart complete @ 1.126125, audio=playing, video=playing (paused)
[statusline] (Paused) AV: 00:00:01 / 00:00:39 (3%) A-V:  0.000
[cplayer] Set property: shared-script-properties -> 1
[osd/libass] fontselect: (sans-serif, 400, 0) -> /usr/share/fonts/TTF/DejaVuSans.ttf, 0, DejaVuSans
[osd/libass] fontselect: (mpv-osd-symbols, 400, 0) -> mpv-osd-symbols-Regular, 0, mpv-osd-symbols-Regular
[vo/gpu] Reallocating OSD texture to 1024x256.
[statusline] (Paused) AV: 00:00:01 / 00:00:39 (3%) A-V:  0.000
[cplayer] Set property: shared-script-properties -> 1
[statusline] (Paused) AV: 00:00:01 / 00:00:39 (3%) A-V:  0.000
[cplayer] EOF code: 5  
[cplayer] finished playback, success (reason 3)
[cplayer] 
[cplayer] Exiting... (Quit)
[cplayer] Set property: shared-script-properties -> 1
[vo/gpu/vulkan/libplacebo] Freed slab of size 1048576
[vo/gpu/vulkan/libplacebo] Freed slab of size 7536640
[vo/gpu/vulkan/libplacebo] Freed slab of size 30244944
[vo/gpu/vulkan/libplacebo] Freed slab of size 120979776
[vo/gpu/vulkan/libplacebo] Freed slab of size 11305216
[vo/gpu/vulkan/libplacebo] Freed slab of size 45220864
[vo/gpu/vulkan/libplacebo] Freed slab of size 1048576
[vo/gpu/vulkan/libplacebo] Freed slab of size 1048576
[vo/gpu/vulkan/libplacebo] Freed slab of size 1048576
[vo/gpu/wayland] Deregistering output Sharp Corporation 0x1453 (0x23)
```
</details>

### Sample files

The issue occurs with every sample video I tried. I assume it happens for any video file.

**Comment by Dudemanguy** [comment]
Sounds like a driver bug. I can't reproduce this on either of my machines (RX 550 and a Sandy Bridge). As you point out, it shouldn't be an mpv issue so I'll go ahead and close this.

**Comment by RPigott** [comment]
Sounds fine, thanks for looking. So your guess is the bug lies in mesa?

**Comment by Dudemanguy** [comment]
Should be mesa I would think since this specifically happens with vulkan (and that's where its implemented).

**Comment by TRPB** [comment]
I'm having this same issue. `gpu-api=vulkan` causes flickering on intel graphics. Strangely it only happens to me on 4k videos, 1080p is fine and I don't have any special profiles set up based on video size.  Turning off `gpu-api=vulkan` fixes it but I get worse performance (dropped frames).

**Comment by Dudemanguy** [comment]
If it's only with HDR videos, that sounds like a different bug (tonemapping weirdness???) although I do not know what is at fault here. It seems vulkan is completely broken on my intel machine now for whatever reason.

**Comment by RPigott** [comment]
My current mesa version is 21.0.1 and I can no longer reproduce this issue as described, so I'm going to assume it was fixed in mesa.

**Comment by unresolvedsymbol** [comment]
Strangely this vulkan issue started happening *after* I upgraded mesa one day. It hasn't been working since. I have integrated intel hd 5500 graphics. For now I'm using opengl and the opengl-hq profile makes it extremely smooth with minimal output drops that aren't even noticeable at 60fps.

**Comment by Dudemanguy** [comment]
Mesa would be one of the potential culprits so it's not particularly surprising if there's a regression somewhere.

**Comment by unresolvedsymbol** [comment]
It's quite a shame, vulkan has 10-20% less CPU usage than OpenGL on my machine (i7 laptop.) 
Update: I did some more testing and it seems deband=yes may be the culprit in the hq profiles

**Comment by AtticFinder65536** [comment]
I have the same issue as @unresolvedsymbol. Months later it's still not fixed yet. I'm on sway, using `gpu-api=vulkan` and `gpu-context=waylandvk`.

In the meantime, it's a lot more bearable when using `vo=gpu-next` and `video-sync=display-resample`. With `vo=gpu-next`, the flickering only occurs on the OSD, OSC, and subtitles, and not the video. And with `video-sync=display-resample`, the flickering reduces hugely. It doesn't happen often at all now, and I've never seen the flickering on the subtitles, just the OSD when showing the stats overlay. Only on one video it's quite annoying, it's a video that contains bad apple encoded in vectorised ass subtitles. The flickering happens quite a lot on that video still.
