### ISSUE TITLE
Changing window-scale via commands should keep the video centered

### ISSUE THREAD

**Issue by c02y** [mpv-player/mpv#8581]
Before requesting a new feature make sure it hasn't been requested yet.
https://github.com/mpv-player/mpv/labels/meta%3Afeature-request

### Expected behavior of the wanted feature
When I set window-scale using bindings written in input.conf, the video window is not centered after that which is very annoying since I'll always center the window manually after I set window-scale.

There is an issue https://github.com/mpv-player/mpv/issues/3164 with the same feature request, but it is requested for Windows, it was solved by modifying the code of mpv, but only for Windows platform, a feature shouldn't be working only on one platform not on others unless it is impossible or not worth the time.

It is suggested that I should open a new issue at that issue page, so I open this feature request for both macOS and Linux, although I'm only using Linux.

BTW: 
```
$ mpv -v
mpv 0.33.0-dirty Copyright © 2000-2020 mpv/MPlayer/mplayer2 projects
 built on UNKNOWN
FFmpeg library versions:
   libavutil       56.51.100
   libavcodec      58.91.100
   libavformat     58.45.100
   libswscale      5.7.100
   libavfilter     7.85.100
   libswresample   3.7.100
FFmpeg version: n4.3.1

$ uname -a
Linux chz 5.9.16-1-MANJARO #1 SMP PREEMPT Mon Dec 21 22:00:46 UTC 2020 x86_64 GNU/Linux

Manjaro-Linux Cinnamon DE

```
### Log file

Even if you think it's not necessary at first, it might help us later to find
possible issues. Make a log file made with -v -v or --log-file=output.txt, paste
it to https://0x0.st/ or attach it to the github issue, and replace this text
with a link to it.

**Comment by Dudemanguy** [comment]
Not sure how it works on xorg but isn't it somewhat window manager dependent? This is impossible on wayland for what it's worth.

**Comment by c02y** [comment]
Don't know about wayland, but most distroes are still using xorg, wmctrl can do it, so I believe it can be done wm-independently.
https://askubuntu.com/a/104190/345798

**Comment by Akemi** [comment]
this is already the case for macOS btw.

**Comment by avih** [comment]
On Windows it seems to keep the same center as before the change, which to me looks like a reasonable behavior.

On X11 it seems to keep the same origin, which is not strictly bad IMO, but different than on Windows and apparently OSX.

**Comment by Akemi** [comment]
it would be helpful if you could provide the infos that we ask for on the "Report a Linux Issue" template. since this is very vo specific we would like to know where exactly your problem is.

**Comment by avih** [comment]
For reference, that's where it was fixed for win32: https://github.com/mpv-player/mpv/commit/5a3c299ca1afcaf943576a144aad92716deb5cf9

And that's the x11 code which likely needs to be modified: https://github.com/mpv-player/mpv/blob/master/video/out/x11_common.c#L1906-L1920

**Comment by c02y** [comment]
@Akemi Sorry about that, I saw that old issue page for request only for Windows and the commit was only for Windows, so I was guessing macOS and Linux don't have this feature. And this is not an issue, it is more like a feature request, so I believe "Request a new Feature" instead of "Report a Linux Issue" is OK.

But you can check the original post on this page, I've provided extra info in "Report a Linux Issue" template.

**Comment by Akemi** [comment]
i didn't imply you chose the wrong template, we just need the additional info. a log file would still be appreciated though.

since some prefer one or the other behaviour it most likely needs an option to configure it(?).

**Comment by c02y** [comment]
Anyone needs a log here? If it is a bug, I can provide a log file, this is a feature request, I don't understand why anyone needs a log file in this situation.

Since Windows and macOS already have this feature as you said, we should make it platform-independent, if Windows/macOS has an option, provide an option for Linux too, the name of the option should be the same, and I believe the option been enabled should be the default behavior. If no option is already provided and the developers think no option is necessary, it should be fixed in the code.

**Comment by Akemi** [comment]
because i asked you nicely to provide a log and making a log probably takes less time then writing up those comments. i want to know which vo and possibly what gpu backend you use. so the one tackling the problem can actually fix your problem and doesn't fix your problem for a different backend on linux. if you are not aware on linux we have several backends (x11, gpu:x11, gpu:wayland, ...) and they might not share that code responsible for it. a log file would just answer that questions and possible other questions that might come up. it's not just as simple as "fix this on linux pls". this is also one of the reasons why the issue template asks for a log in the first place.

it's not as easy than saying 'make it platform independent' it takes effort and keeping the status quo (by keeping it in the platform/vo/backend dependent code) might be the way to go for now.

**Comment by Akemi** [comment]
because i asked you nicely to provide a log and making a log probably takes less time then writing up those comments. i want to know which vo and possibly what gpu backend you use. so the one tackling the problem can actually fix your problem and doesn't fix your problem for a different backend on linux. if you are not aware on linux we have several backends (x11, gpu:x11, gpu:wayland, ...) and they might not share that code responsible for it. a log file would just answer that questions and possible other questions that might come up. it's not just as simple as "fix this on linux pls". this is also one of the reasons why the issue template asks for a log in the first place.

it's not as easy than saying 'make it platform independent' it takes effort and keeping the status quo (by keeping it in the platform/vo/backend dependent code) might be the way to go for now.

**Comment by c02y** [comment]
Sorry about the misunderstanding, I just provided the log in the original post on this page.

**Comment by Akemi** [comment]
thx for the log, but that doesn't seem like a complete log but rather being cut off. you can also use the `--log-file=PATH_TO_LOG.log` option to create a log.

**Comment by c02y** [comment]
@Akemi They are almost the same, check the attached log file.

**Comment by avih** [comment]
Please stop wasting everybody's time and post a FULL log. Don't cut it. Just the whole file.

**Comment by c02y** [comment]
@avih I didn't cut anything, the text I pasted or the log file, they are the full text I got, if you insist, please tell me what I've cut.
![2021-02-21_00-38](https://user-images.githubusercontent.com/2135996/108602518-422acd00-73dd-11eb-8a8d-6ae2af56634c.png)

**Comment by avih** [comment]
The log file includes information about the opened clip and the VO used. Yours doesn't. That's the only part we need, and none of your logs have it. We still don't know which VO gets used.

**Comment by c02y** [comment]
@avih I know why you said I've cut the log, since I got "really-quiet" in my mpv.conf, I've replaced the log file in the first post on this page.

**Comment by Akemi** [comment]
thanks for the updated log. on a side note, i think that really-quiet influences the output of log-file (at least negative) is not intended behaviour and i think that should be changed/fixed. i will raise that point on irc.

**Comment by Dudemanguy** [comment]
>This is impossible on wayland for what it's worth.

Actually it's possible now. Clients can control how they resize via wl_surface.offset. I'll revisit this.
