### ISSUE TITLE
mpv crashes on Fedora 35 + GNOME + Wayland + Nvidia

### ISSUE THREAD

**Issue by Paveloom** [mpv-player/mpv#9393]
### Important Information

- **mpv version**:  0.34.0
- **Linux Distribution and Version**: Fedora Linux 35
- **Source of the mpv binary**: RPM package (0.34.0-1.fc35)
- **Window Manager and version**: GNOME 41.1
- **GPU driver and version**:
  ```
  Graphics:
    Device-1: Intel Skylake GT2 [HD Graphics 520] driver: i915 v: kernel 
    Device-2: NVIDIA GM108M [GeForce 940MX] driver: nvidia v: 495.44 
    Device-3: Cheng Uei Precision Industry (Foxlink) XiaoMi USB 2.0 Webcam 
    type: USB driver: uvcvideo 
    Display: wayland server: X.Org 1.21.1.2 driver: loaded: intel,nvidia 
    unloaded: fbdev,modesetting,nouveau,vesa resolution: 1920x1080~60Hz 
    OpenGL: renderer: Mesa Intel HD Graphics 520 (SKL GT2) v: 4.6 Mesa 21.2.5
  ```

### Reproduction steps

1. Try to play any file.

### Expected behavior

mpv plays the file.

### Actual behavior

mpv crashes with

```
 (+) Video --vid=1 (*) (h264 1280x720 24.000fps)
 (+) Audio --aid=1 (*) (aac 2ch 44100Hz)
[vo/gpu/wayland] GNOME's wayland compositor lacks support for the idle inhibit protocol. This means the screen can blank during playback.
AO: [pulse] 44100Hz stereo 2ch float
VO: [gpu] 1280x720 yuv420p
[destroyed object]: error 7: failed to import supplied dmabufs: Arguments are inconsistent (for example, a valid context requires buffers not supplied by a 
[vo/gpu/wayland] Error occurred on the display fd, closing

Exiting... (Quit)
```

### Log file

[log.txt](https://github.com/mpv-player/mpv/files/7474202/log.txt)

### Notes

This is most likely an upstream issue, but I think it needs to be documented.

**Comment by jeeb** [comment]
Does not sound like a crash according to the log (the VO exits as it cannot get the fd), but I do wonder if #9384 helps with this.

**Comment by Dudemanguy** [comment]
>[destroyed object]: error 7: failed to import supplied dmabufs

Yeah I'm going to say this is a NVIDIA bug. Probably, the compositor is trying to import dmabufs at some point and something goes wrong at the driver level. This causes the compositor to send mpv an error on the display fd which is fatal and it exits. You could try `--opengl-es=yes` to force GLES maybe the result will be magically different (or it could be the same who knows).

**Comment by monarc99** [comment]
maybe https://github.com/NVIDIA/egl-wayland/issues/41
-> I wonder if it's still trying to use nvidias EGL library instead of mesa's.

 try running mpv with the environment variable __EGL_VENDOR_LIBRARY_FILENAMES=/usr/share/glvnd/egl_vendor.d/50_mesa.json

**Comment by Paveloom** [comment]
Nope, `--opengl-es=yes` gives the same result, but `__EGL_VENDOR_LIBRARY_FILENAMES=/usr/share/glvnd/egl_vendor.d/50_mesa.json` actually fixes the problem. So yeah, this is an upstream issue.

[opengl-es.txt](https://github.com/mpv-player/mpv/files/7485615/opengl-es.txt)
[nvidia-egl.txt](https://github.com/mpv-player/mpv/files/7485596/nvidia-egl.txt)

**Comment by VihagChaturvedi** [comment]
experiencing similar issues on F35 + Gnome 41 + Wayland + Nvidia

mpv has already crashed gnome session for me once.

**Comment by oboff** [comment]
> `__EGL_VENDOR_LIBRARY_FILENAMES=/usr/share/glvnd/egl_vendor.d/50_mesa.json` 
the above prefix to `mpv` and `celluloid` worked like a charm thank you

**Comment by solinium** [comment]
With latest fedora updates it seems to be fixed for me. Would like other people to confirm this. (F35, GNOME 41.1, Wayland, NVIDIA + integrated AMD graphics)

**Comment by Paveloom** [comment]
@solinium The package update was [submitted for stable](https://bodhi.fedoraproject.org/updates/FEDORA-2021-0526645c86) today.

**Comment by Paveloom** [comment]
Fixed upstream.

**Comment by rodhash** [comment]
Installed Fedora 36 w/ Gnome Wayland, facing the same issue. 

Variable `__EGL_VENDOR_LIBRARY_FILENAMES` saved the day, I'm creating an alias for mpv because I'm unsure whether or not the issue is back.

**Comment by davuses** [comment]
Had the same problem on Ubuntu22 with Wayland.

Setting env variable `__EGL_VENDOR_LIBRARY_FILENAMES=/usr/share/glvnd/egl_vendor.d/50_mesa.json` solved the issue.

I Also find that launching mpv with video output drivers option `--vo=gpu`, which is the default, will fail. But it works with option `--vo=wlshm`, which I think is to disable hardware acceleration. I guess the problem is on the nvidia driver.

**Comment by Paveloom** [comment]
That's weird, it works fine for me on Fedora 36 /w Gnome Wayland.
