### ISSUE TITLE
distorted colors when playing a specific video on old hardware

### ISSUE THREAD

**Issue by YousefSaber** [mpv-player/mpv#9565]
my PC specs
```
[jsaber@192 ~]$ screenfetch 
           /:-------------:\          jsaber@192.168.1.5
        :-------------------::        OS: Fedora 
      :-----------/shhOHbmp---:\      Kernel: x86_64 Linux 5.15.6-200.fc35.x86_64
    /-----------omMMMNNNMMD  ---:     Uptime: 1h 39m
   :-----------sMMMMNMNMP.    ---:    Packages: 1375
  :-----------:MMMdP-------    ---\   Shell: bash 5.1.8
 ,------------:MMMd--------    ---:   Resolution: No X Server
 :------------:MMMd-------    .---:   DE: LXQt 0.17.0
 :----    oNMMMMMMMMMNho     .----:   WM: OpenBox
 :--     .+shhhMMMmhhy++   .------/   WM Theme: Clearlooks
 :-    -------:MMMd--------------:    GTK Theme: Adwaita [GTK3]
 :-   --------/MMMd-------------;     Disk: 5.9G / 295G (3%)
 :-    ------/hMMMy------------:      CPU: Intel Core2 Duo E8500 @ 2x 3.166GHz
 :-- :dMNdhhdNMMNo------------;       GPU: Mesa DRI Intel(R) G33 
 :---:sdNMMMMNds:------------:        RAM: 1603MiB / 3903MiB
 :------:://:-------------::         
 :---------------------://   
```
when playing a [specific video](https://www.youtube.com/watch?v=vK-SwsWnEmo) ( this doesn't apply to all videos) I see some distorted colors here's the log file
[mpv.log](https://github.com/mpv-player/mpv/files/7661296/mpv.log)

**Comment by LaserEyess** [comment]
Can you fill out the issue template? It's impossible to fix your issue without it, in particular:

>- Possible screenshot or video of visual glitches

Because I tried your video and there's no distorted colors.

**Comment by LaserEyess** [comment]
Just to confirm, when viewed in youtube this video has the correct colors? Can you try `--no-config --vo=xv` or `--no-config --vo=x11` and see if the issue persists?

**Comment by YousefSaber** [comment]
@LaserEyess I discovered the issue the res of my monitor was `1440 x 900` while the video was streaming at higher res `2560 x 1440` this caused the color distortion when including the following line in the configuration file (I'm sorry I forgot to configure the configuration file on my old machine)
```
ytdl-format='bestvideo[height<=1080][fps<=60] + bestaudio'
```
in the configuration file and streaming the video at `1920 x 1080` the issue is fixed.

**Comment by LaserEyess** [comment]
No, that does not solve the issue at all. Resolution should not matter for the colors in the video, but now you've found a new, interesting datapoint.

**Comment by haasn** [comment]
> [   4.399][e][vo/gpu/opengl] after rendering: OpenGL error INVALID_OPERATION.

This seems like the culprit. Can you try `--gpu-debug`? With some luck you might get more information about the cause. (If not, you'd have to resort to e.g. `apitrace`)

**Comment by haasn** [comment]
I've also managed to confirm what's happening here: the luma plane is being sampled as constant 0.0. I can successfully replicate the screenshot using this shader:

```glsl
//!HOOK LUMA
//!BIND HOOKED

vec4 hook()
{
    return vec4(0.0);
}
```

So possibly what's happening is that the 1440p sized luma plane somehow exceeds the resource capabilities of your card (in some fashion) causing it to be absent/undefined, or perhaps the shader doesn't like downscaling while sampling, causing it to fail reading from the luma texture at all. It's also entirely possible that what's actually failing is the texture *upload*. (Possibly the 1440p luma stride is somehow misaligned in a way that 1080p or 720p isn't)

In any case, the issue is that the luma texture is not being read properly.

**Comment by YousefSaber** [comment]
> Just to confirm, when viewed in youtube this video has the correct colors? Can you try `--no-config --vo=xv` or `--no-config --vo=x11` and see if the issue persists?

using `--no-config --vo=xv  `

```
[jsaber@fedora ~]$ mpv --no-config --vo=xv  https://www.youtube.com/watch?v=vK-SwsWnEmo
 (+) Video --vid=1 (*) (vp9 2560x1440 30.000fps)
 (+) Audio --aid=1 --alang=eng (*) (opus 2ch 48000Hz)
File tags:
 Uploader: GNOME
 Channel_URL: https://www.youtube.com/channel/UCH9zoXlRn8iiaiSmuazAFZw
[vo/xv] Warning: this legacy VO has bad quality and performance, and will in particular result in blurry OSD and subtitles. You should fix your graphics drivers, or not force the xv VO.
AO: [pulse] 48000Hz stereo 2ch float
VO: [xv] 2560x1440 yuv420p
[vo/xv] Source image dimensions are too high: 2560x1440 (maximum is 2048x2048)
Could not initialize video chain.
Video: no video
A: 00:00:10 / 00:01:04 (16%) Cache: 53s/2MB

Exiting... (Quit)
```
using the above parameters the window doesn't even appear I can only hear audio 

but these parameters completely fix the problem at the highest res and best quality `-no-config --vo=x11`

**Comment by haasn** [comment]
> [vo/xv] Source image dimensions are too high: 2560x1440 (maximum is 2048x2048)

That'll probably be it. Just to confirm, if you use `--vo=gpu-next` it should print the maximum texture size supported by the hardware, which it seems like (in this case) is 2048x2048?

**Comment by YousefSaber** [comment]
@haasn here's the new log file with the highest verbosity details level using the parameters `--msg-level=all=trace` the full command is 
```
mpv --no-config --gpu-debug --log-file=mpvnew.log --msg-level=all=trace  https://www.youtube.com/watch?v=vK-SwsWnEmo
```

the new log file 
[mpvnew.log](https://github.com/mpv-player/mpv/files/7678497/mpvnew.log)

**Comment by YousefSaber** [comment]
> > [vo/xv] Source image dimensions are too high: 2560x1440 (maximum is 2048x2048)
> 
> That'll probably be it. Just to confirm, if you use `--vo=gpu-next` it should print the maximum texture size supported by the hardware, which it seems like (in this case) is 2048x2048?

I don't know how to run this command nor it's referenced in the official docs 
```
[jsaber@fedora ~]$ mpv --no-config --vo=gpu-next https://www.youtube.com/watch?v=vK-SwsWnEmo
 (+) Video --vid=1 (*) (vp9 2560x1440 30.000fps)
 (+) Audio --aid=1 --alang=eng (*) (opus 2ch 48000Hz)
File tags:
 Uploader: GNOME
 Channel_URL: https://www.youtube.com/channel/UCH9zoXlRn8iiaiSmuazAFZw
[vo] Video output gpu-next not found!
Error opening/initializing the selected video_out (--vo) device.                                                                              
Video: no video                                                                                                                               

Exiting... (Errors when loading file)
```
```
[jsaber@fedora ~]$ mpv --vo=gpu-next
mpv 0.34.0 Copyright © 2000-2021 mpv/MPlayer/mplayer2 projects
 built on UNKNOWN
FFmpeg library versions:
   libavutil       56.70.100
   libavcodec      58.134.100
   libavformat     58.76.100
   libswscale      5.9.100
   libavfilter     7.110.100
   libswresample   3.9.100
FFmpeg version: 4.4.1

Usage:   mpv [options] [url|path/]filename

Basic options:
 --start=<time>    seek to given (percent, seconds, or hh:mm:ss) position
 --no-audio        do not play sound
 --no-video        do not play video
 --fs              fullscreen playback
 --sub-file=<file> specify subtitle file to use
 --playlist=<file> specify playlist file

 --list-options    list all mpv options
 --h=<string>      print options which contain the given string in their name

```

**Comment by LaserEyess** [comment]
`--vo=gpu-next` requires git master for mpv.
